// Code generated by ent, DO NOT EDIT.

package manifestblob

import (
	"time"
	"uuid"

	"github.com/lesomnus/cr/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Id filters vertices based on their Id field.
func Id(id uuid.UUID) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldEQ(FieldId, id))
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id uuid.UUID) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldEQ(FieldId, id))
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id uuid.UUID) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldNEQ(FieldId, id))
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...uuid.UUID) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldIn(FieldId, ids...))
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...uuid.UUID) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldNotIn(FieldId, ids...))
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id uuid.UUID) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldGT(FieldId, id))
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id uuid.UUID) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldGTE(FieldId, id))
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id uuid.UUID) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldLT(FieldId, id))
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id uuid.UUID) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldLTE(FieldId, id))
}

// Repo applies equality check predicate on the "repo" field. It's identical to RepoEQ.
func Repo(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldEQ(FieldRepo, v))
}

// Manifest applies equality check predicate on the "manifest" field. It's identical to ManifestEQ.
func Manifest(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldEQ(FieldManifest, v))
}

// Blob applies equality check predicate on the "blob" field. It's identical to BlobEQ.
func Blob(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldEQ(FieldBlob, v))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldEQ(FieldDateCreated, v))
}

// RepoEQ applies the EQ predicate on the "repo" field.
func RepoEQ(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldEQ(FieldRepo, v))
}

// RepoNEQ applies the NEQ predicate on the "repo" field.
func RepoNEQ(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldNEQ(FieldRepo, v))
}

// RepoIn applies the In predicate on the "repo" field.
func RepoIn(vs ...string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldIn(FieldRepo, vs...))
}

// RepoNotIn applies the NotIn predicate on the "repo" field.
func RepoNotIn(vs ...string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldNotIn(FieldRepo, vs...))
}

// RepoGT applies the GT predicate on the "repo" field.
func RepoGT(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldGT(FieldRepo, v))
}

// RepoGTE applies the GTE predicate on the "repo" field.
func RepoGTE(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldGTE(FieldRepo, v))
}

// RepoLT applies the LT predicate on the "repo" field.
func RepoLT(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldLT(FieldRepo, v))
}

// RepoLTE applies the LTE predicate on the "repo" field.
func RepoLTE(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldLTE(FieldRepo, v))
}

// RepoContains applies the Contains predicate on the "repo" field.
func RepoContains(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldContains(FieldRepo, v))
}

// RepoHasPrefix applies the HasPrefix predicate on the "repo" field.
func RepoHasPrefix(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldHasPrefix(FieldRepo, v))
}

// RepoHasSuffix applies the HasSuffix predicate on the "repo" field.
func RepoHasSuffix(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldHasSuffix(FieldRepo, v))
}

// RepoEqualFold applies the EqualFold predicate on the "repo" field.
func RepoEqualFold(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldEqualFold(FieldRepo, v))
}

// RepoContainsFold applies the ContainsFold predicate on the "repo" field.
func RepoContainsFold(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldContainsFold(FieldRepo, v))
}

// ManifestEQ applies the EQ predicate on the "manifest" field.
func ManifestEQ(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldEQ(FieldManifest, v))
}

// ManifestNEQ applies the NEQ predicate on the "manifest" field.
func ManifestNEQ(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldNEQ(FieldManifest, v))
}

// ManifestIn applies the In predicate on the "manifest" field.
func ManifestIn(vs ...string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldIn(FieldManifest, vs...))
}

// ManifestNotIn applies the NotIn predicate on the "manifest" field.
func ManifestNotIn(vs ...string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldNotIn(FieldManifest, vs...))
}

// ManifestGT applies the GT predicate on the "manifest" field.
func ManifestGT(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldGT(FieldManifest, v))
}

// ManifestGTE applies the GTE predicate on the "manifest" field.
func ManifestGTE(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldGTE(FieldManifest, v))
}

// ManifestLT applies the LT predicate on the "manifest" field.
func ManifestLT(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldLT(FieldManifest, v))
}

// ManifestLTE applies the LTE predicate on the "manifest" field.
func ManifestLTE(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldLTE(FieldManifest, v))
}

// ManifestContains applies the Contains predicate on the "manifest" field.
func ManifestContains(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldContains(FieldManifest, v))
}

// ManifestHasPrefix applies the HasPrefix predicate on the "manifest" field.
func ManifestHasPrefix(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldHasPrefix(FieldManifest, v))
}

// ManifestHasSuffix applies the HasSuffix predicate on the "manifest" field.
func ManifestHasSuffix(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldHasSuffix(FieldManifest, v))
}

// ManifestEqualFold applies the EqualFold predicate on the "manifest" field.
func ManifestEqualFold(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldEqualFold(FieldManifest, v))
}

// ManifestContainsFold applies the ContainsFold predicate on the "manifest" field.
func ManifestContainsFold(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldContainsFold(FieldManifest, v))
}

// BlobEQ applies the EQ predicate on the "blob" field.
func BlobEQ(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldEQ(FieldBlob, v))
}

// BlobNEQ applies the NEQ predicate on the "blob" field.
func BlobNEQ(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldNEQ(FieldBlob, v))
}

// BlobIn applies the In predicate on the "blob" field.
func BlobIn(vs ...string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldIn(FieldBlob, vs...))
}

// BlobNotIn applies the NotIn predicate on the "blob" field.
func BlobNotIn(vs ...string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldNotIn(FieldBlob, vs...))
}

// BlobGT applies the GT predicate on the "blob" field.
func BlobGT(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldGT(FieldBlob, v))
}

// BlobGTE applies the GTE predicate on the "blob" field.
func BlobGTE(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldGTE(FieldBlob, v))
}

// BlobLT applies the LT predicate on the "blob" field.
func BlobLT(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldLT(FieldBlob, v))
}

// BlobLTE applies the LTE predicate on the "blob" field.
func BlobLTE(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldLTE(FieldBlob, v))
}

// BlobContains applies the Contains predicate on the "blob" field.
func BlobContains(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldContains(FieldBlob, v))
}

// BlobHasPrefix applies the HasPrefix predicate on the "blob" field.
func BlobHasPrefix(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldHasPrefix(FieldBlob, v))
}

// BlobHasSuffix applies the HasSuffix predicate on the "blob" field.
func BlobHasSuffix(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldHasSuffix(FieldBlob, v))
}

// BlobEqualFold applies the EqualFold predicate on the "blob" field.
func BlobEqualFold(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldEqualFold(FieldBlob, v))
}

// BlobContainsFold applies the ContainsFold predicate on the "blob" field.
func BlobContainsFold(v string) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldContainsFold(FieldBlob, v))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldLTE(FieldDateCreated, v))
}

// DateCreatedIsNil applies the IsNil predicate on the "date_created" field.
func DateCreatedIsNil() predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldIsNull(FieldDateCreated))
}

// DateCreatedNotNil applies the NotNil predicate on the "date_created" field.
func DateCreatedNotNil() predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.FieldNotNull(FieldDateCreated))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ManifestBlob) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ManifestBlob) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ManifestBlob) predicate.ManifestBlob {
	return predicate.ManifestBlob(sql.NotPredicates(p))
}
