// Code generated by ent, DO NOT EDIT.

package manifest

import (
	"github.com/protobuf-orm/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the manifest type in the database.
	Label = "manifest"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// FieldRepo holds the string denoting the repo field in the database.
	FieldRepo = "repo"
	// FieldDigest holds the string denoting the digest field in the database.
	FieldDigest = "digest"
	// FieldMediaType holds the string denoting the media_type field in the database.
	FieldMediaType = "media_type"
	// FieldArtifactType holds the string denoting the artifact_type field in the database.
	FieldArtifactType = "artifact_type"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldAnnotations holds the string denoting the annotations field in the database.
	FieldAnnotations = "annotations"
	// FieldDatePulled holds the string denoting the date_pulled field in the database.
	FieldDatePulled = "date_pulled"
	// FieldDateUpdated holds the string denoting the date_updated field in the database.
	FieldDateUpdated = "date_updated"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// Table holds the table name of the manifest in the database.
	Table = "manifest"
)

// Columns holds all SQL columns for manifest fields.
var Columns = []string{
	FieldId,
	FieldRepo,
	FieldDigest,
	FieldMediaType,
	FieldArtifactType,
	FieldSubject,
	FieldSize,
	FieldAnnotations,
	FieldDatePulled,
	FieldDateUpdated,
	FieldDateCreated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Manifest queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}

// ByRepo orders the results by the repo field.
func ByRepo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepo, opts...).ToFunc()
}

// ByDigest orders the results by the digest field.
func ByDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDigest, opts...).ToFunc()
}

// ByMediaType orders the results by the media_type field.
func ByMediaType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMediaType, opts...).ToFunc()
}

// ByArtifactType orders the results by the artifact_type field.
func ByArtifactType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtifactType, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByDatePulled orders the results by the date_pulled field.
func ByDatePulled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDatePulled, opts...).ToFunc()
}

// ByDateUpdated orders the results by the date_updated field.
func ByDateUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateUpdated, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}
