// Code generated by ent, DO NOT EDIT.

package manifest

import (
	"time"
	"uuid"

	"github.com/lesomnus/cr/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Id filters vertices based on their Id field.
func Id(id uuid.UUID) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldId, id))
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id uuid.UUID) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldId, id))
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id uuid.UUID) predicate.Manifest {
	return predicate.Manifest(sql.FieldNEQ(FieldId, id))
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...uuid.UUID) predicate.Manifest {
	return predicate.Manifest(sql.FieldIn(FieldId, ids...))
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...uuid.UUID) predicate.Manifest {
	return predicate.Manifest(sql.FieldNotIn(FieldId, ids...))
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id uuid.UUID) predicate.Manifest {
	return predicate.Manifest(sql.FieldGT(FieldId, id))
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id uuid.UUID) predicate.Manifest {
	return predicate.Manifest(sql.FieldGTE(FieldId, id))
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id uuid.UUID) predicate.Manifest {
	return predicate.Manifest(sql.FieldLT(FieldId, id))
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id uuid.UUID) predicate.Manifest {
	return predicate.Manifest(sql.FieldLTE(FieldId, id))
}

// Repo applies equality check predicate on the "repo" field. It's identical to RepoEQ.
func Repo(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldRepo, v))
}

// Digest applies equality check predicate on the "digest" field. It's identical to DigestEQ.
func Digest(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldDigest, v))
}

// MediaType applies equality check predicate on the "media_type" field. It's identical to MediaTypeEQ.
func MediaType(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldMediaType, v))
}

// ArtifactType applies equality check predicate on the "artifact_type" field. It's identical to ArtifactTypeEQ.
func ArtifactType(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldArtifactType, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldSubject, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldSize, v))
}

// DatePulled applies equality check predicate on the "date_pulled" field. It's identical to DatePulledEQ.
func DatePulled(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldDatePulled, v))
}

// DateUpdated applies equality check predicate on the "date_updated" field. It's identical to DateUpdatedEQ.
func DateUpdated(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldDateUpdated, v))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldDateCreated, v))
}

// RepoEQ applies the EQ predicate on the "repo" field.
func RepoEQ(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldRepo, v))
}

// RepoNEQ applies the NEQ predicate on the "repo" field.
func RepoNEQ(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldNEQ(FieldRepo, v))
}

// RepoIn applies the In predicate on the "repo" field.
func RepoIn(vs ...string) predicate.Manifest {
	return predicate.Manifest(sql.FieldIn(FieldRepo, vs...))
}

// RepoNotIn applies the NotIn predicate on the "repo" field.
func RepoNotIn(vs ...string) predicate.Manifest {
	return predicate.Manifest(sql.FieldNotIn(FieldRepo, vs...))
}

// RepoGT applies the GT predicate on the "repo" field.
func RepoGT(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldGT(FieldRepo, v))
}

// RepoGTE applies the GTE predicate on the "repo" field.
func RepoGTE(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldGTE(FieldRepo, v))
}

// RepoLT applies the LT predicate on the "repo" field.
func RepoLT(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldLT(FieldRepo, v))
}

// RepoLTE applies the LTE predicate on the "repo" field.
func RepoLTE(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldLTE(FieldRepo, v))
}

// RepoContains applies the Contains predicate on the "repo" field.
func RepoContains(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldContains(FieldRepo, v))
}

// RepoHasPrefix applies the HasPrefix predicate on the "repo" field.
func RepoHasPrefix(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldHasPrefix(FieldRepo, v))
}

// RepoHasSuffix applies the HasSuffix predicate on the "repo" field.
func RepoHasSuffix(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldHasSuffix(FieldRepo, v))
}

// RepoEqualFold applies the EqualFold predicate on the "repo" field.
func RepoEqualFold(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEqualFold(FieldRepo, v))
}

// RepoContainsFold applies the ContainsFold predicate on the "repo" field.
func RepoContainsFold(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldContainsFold(FieldRepo, v))
}

// DigestEQ applies the EQ predicate on the "digest" field.
func DigestEQ(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldDigest, v))
}

// DigestNEQ applies the NEQ predicate on the "digest" field.
func DigestNEQ(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldNEQ(FieldDigest, v))
}

// DigestIn applies the In predicate on the "digest" field.
func DigestIn(vs ...string) predicate.Manifest {
	return predicate.Manifest(sql.FieldIn(FieldDigest, vs...))
}

// DigestNotIn applies the NotIn predicate on the "digest" field.
func DigestNotIn(vs ...string) predicate.Manifest {
	return predicate.Manifest(sql.FieldNotIn(FieldDigest, vs...))
}

// DigestGT applies the GT predicate on the "digest" field.
func DigestGT(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldGT(FieldDigest, v))
}

// DigestGTE applies the GTE predicate on the "digest" field.
func DigestGTE(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldGTE(FieldDigest, v))
}

// DigestLT applies the LT predicate on the "digest" field.
func DigestLT(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldLT(FieldDigest, v))
}

// DigestLTE applies the LTE predicate on the "digest" field.
func DigestLTE(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldLTE(FieldDigest, v))
}

// DigestContains applies the Contains predicate on the "digest" field.
func DigestContains(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldContains(FieldDigest, v))
}

// DigestHasPrefix applies the HasPrefix predicate on the "digest" field.
func DigestHasPrefix(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldHasPrefix(FieldDigest, v))
}

// DigestHasSuffix applies the HasSuffix predicate on the "digest" field.
func DigestHasSuffix(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldHasSuffix(FieldDigest, v))
}

// DigestEqualFold applies the EqualFold predicate on the "digest" field.
func DigestEqualFold(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEqualFold(FieldDigest, v))
}

// DigestContainsFold applies the ContainsFold predicate on the "digest" field.
func DigestContainsFold(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldContainsFold(FieldDigest, v))
}

// MediaTypeEQ applies the EQ predicate on the "media_type" field.
func MediaTypeEQ(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldMediaType, v))
}

// MediaTypeNEQ applies the NEQ predicate on the "media_type" field.
func MediaTypeNEQ(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldNEQ(FieldMediaType, v))
}

// MediaTypeIn applies the In predicate on the "media_type" field.
func MediaTypeIn(vs ...string) predicate.Manifest {
	return predicate.Manifest(sql.FieldIn(FieldMediaType, vs...))
}

// MediaTypeNotIn applies the NotIn predicate on the "media_type" field.
func MediaTypeNotIn(vs ...string) predicate.Manifest {
	return predicate.Manifest(sql.FieldNotIn(FieldMediaType, vs...))
}

// MediaTypeGT applies the GT predicate on the "media_type" field.
func MediaTypeGT(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldGT(FieldMediaType, v))
}

// MediaTypeGTE applies the GTE predicate on the "media_type" field.
func MediaTypeGTE(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldGTE(FieldMediaType, v))
}

// MediaTypeLT applies the LT predicate on the "media_type" field.
func MediaTypeLT(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldLT(FieldMediaType, v))
}

// MediaTypeLTE applies the LTE predicate on the "media_type" field.
func MediaTypeLTE(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldLTE(FieldMediaType, v))
}

// MediaTypeContains applies the Contains predicate on the "media_type" field.
func MediaTypeContains(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldContains(FieldMediaType, v))
}

// MediaTypeHasPrefix applies the HasPrefix predicate on the "media_type" field.
func MediaTypeHasPrefix(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldHasPrefix(FieldMediaType, v))
}

// MediaTypeHasSuffix applies the HasSuffix predicate on the "media_type" field.
func MediaTypeHasSuffix(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldHasSuffix(FieldMediaType, v))
}

// MediaTypeEqualFold applies the EqualFold predicate on the "media_type" field.
func MediaTypeEqualFold(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEqualFold(FieldMediaType, v))
}

// MediaTypeContainsFold applies the ContainsFold predicate on the "media_type" field.
func MediaTypeContainsFold(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldContainsFold(FieldMediaType, v))
}

// ArtifactTypeEQ applies the EQ predicate on the "artifact_type" field.
func ArtifactTypeEQ(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldArtifactType, v))
}

// ArtifactTypeNEQ applies the NEQ predicate on the "artifact_type" field.
func ArtifactTypeNEQ(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldNEQ(FieldArtifactType, v))
}

// ArtifactTypeIn applies the In predicate on the "artifact_type" field.
func ArtifactTypeIn(vs ...string) predicate.Manifest {
	return predicate.Manifest(sql.FieldIn(FieldArtifactType, vs...))
}

// ArtifactTypeNotIn applies the NotIn predicate on the "artifact_type" field.
func ArtifactTypeNotIn(vs ...string) predicate.Manifest {
	return predicate.Manifest(sql.FieldNotIn(FieldArtifactType, vs...))
}

// ArtifactTypeGT applies the GT predicate on the "artifact_type" field.
func ArtifactTypeGT(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldGT(FieldArtifactType, v))
}

// ArtifactTypeGTE applies the GTE predicate on the "artifact_type" field.
func ArtifactTypeGTE(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldGTE(FieldArtifactType, v))
}

// ArtifactTypeLT applies the LT predicate on the "artifact_type" field.
func ArtifactTypeLT(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldLT(FieldArtifactType, v))
}

// ArtifactTypeLTE applies the LTE predicate on the "artifact_type" field.
func ArtifactTypeLTE(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldLTE(FieldArtifactType, v))
}

// ArtifactTypeContains applies the Contains predicate on the "artifact_type" field.
func ArtifactTypeContains(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldContains(FieldArtifactType, v))
}

// ArtifactTypeHasPrefix applies the HasPrefix predicate on the "artifact_type" field.
func ArtifactTypeHasPrefix(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldHasPrefix(FieldArtifactType, v))
}

// ArtifactTypeHasSuffix applies the HasSuffix predicate on the "artifact_type" field.
func ArtifactTypeHasSuffix(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldHasSuffix(FieldArtifactType, v))
}

// ArtifactTypeEqualFold applies the EqualFold predicate on the "artifact_type" field.
func ArtifactTypeEqualFold(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEqualFold(FieldArtifactType, v))
}

// ArtifactTypeContainsFold applies the ContainsFold predicate on the "artifact_type" field.
func ArtifactTypeContainsFold(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldContainsFold(FieldArtifactType, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.Manifest {
	return predicate.Manifest(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.Manifest {
	return predicate.Manifest(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.Manifest {
	return predicate.Manifest(sql.FieldContainsFold(FieldSubject, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.Manifest {
	return predicate.Manifest(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.Manifest {
	return predicate.Manifest(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.Manifest {
	return predicate.Manifest(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.Manifest {
	return predicate.Manifest(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.Manifest {
	return predicate.Manifest(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.Manifest {
	return predicate.Manifest(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.Manifest {
	return predicate.Manifest(sql.FieldLTE(FieldSize, v))
}

// AnnotationsIsNil applies the IsNil predicate on the "annotations" field.
func AnnotationsIsNil() predicate.Manifest {
	return predicate.Manifest(sql.FieldIsNull(FieldAnnotations))
}

// AnnotationsNotNil applies the NotNil predicate on the "annotations" field.
func AnnotationsNotNil() predicate.Manifest {
	return predicate.Manifest(sql.FieldNotNull(FieldAnnotations))
}

// DatePulledEQ applies the EQ predicate on the "date_pulled" field.
func DatePulledEQ(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldDatePulled, v))
}

// DatePulledNEQ applies the NEQ predicate on the "date_pulled" field.
func DatePulledNEQ(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldNEQ(FieldDatePulled, v))
}

// DatePulledIn applies the In predicate on the "date_pulled" field.
func DatePulledIn(vs ...time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldIn(FieldDatePulled, vs...))
}

// DatePulledNotIn applies the NotIn predicate on the "date_pulled" field.
func DatePulledNotIn(vs ...time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldNotIn(FieldDatePulled, vs...))
}

// DatePulledGT applies the GT predicate on the "date_pulled" field.
func DatePulledGT(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldGT(FieldDatePulled, v))
}

// DatePulledGTE applies the GTE predicate on the "date_pulled" field.
func DatePulledGTE(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldGTE(FieldDatePulled, v))
}

// DatePulledLT applies the LT predicate on the "date_pulled" field.
func DatePulledLT(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldLT(FieldDatePulled, v))
}

// DatePulledLTE applies the LTE predicate on the "date_pulled" field.
func DatePulledLTE(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldLTE(FieldDatePulled, v))
}

// DatePulledIsNil applies the IsNil predicate on the "date_pulled" field.
func DatePulledIsNil() predicate.Manifest {
	return predicate.Manifest(sql.FieldIsNull(FieldDatePulled))
}

// DatePulledNotNil applies the NotNil predicate on the "date_pulled" field.
func DatePulledNotNil() predicate.Manifest {
	return predicate.Manifest(sql.FieldNotNull(FieldDatePulled))
}

// DateUpdatedEQ applies the EQ predicate on the "date_updated" field.
func DateUpdatedEQ(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldDateUpdated, v))
}

// DateUpdatedNEQ applies the NEQ predicate on the "date_updated" field.
func DateUpdatedNEQ(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldNEQ(FieldDateUpdated, v))
}

// DateUpdatedIn applies the In predicate on the "date_updated" field.
func DateUpdatedIn(vs ...time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldIn(FieldDateUpdated, vs...))
}

// DateUpdatedNotIn applies the NotIn predicate on the "date_updated" field.
func DateUpdatedNotIn(vs ...time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldNotIn(FieldDateUpdated, vs...))
}

// DateUpdatedGT applies the GT predicate on the "date_updated" field.
func DateUpdatedGT(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldGT(FieldDateUpdated, v))
}

// DateUpdatedGTE applies the GTE predicate on the "date_updated" field.
func DateUpdatedGTE(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldGTE(FieldDateUpdated, v))
}

// DateUpdatedLT applies the LT predicate on the "date_updated" field.
func DateUpdatedLT(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldLT(FieldDateUpdated, v))
}

// DateUpdatedLTE applies the LTE predicate on the "date_updated" field.
func DateUpdatedLTE(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldLTE(FieldDateUpdated, v))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.Manifest {
	return predicate.Manifest(sql.FieldLTE(FieldDateCreated, v))
}

// DateCreatedIsNil applies the IsNil predicate on the "date_created" field.
func DateCreatedIsNil() predicate.Manifest {
	return predicate.Manifest(sql.FieldIsNull(FieldDateCreated))
}

// DateCreatedNotNil applies the NotNil predicate on the "date_created" field.
func DateCreatedNotNil() predicate.Manifest {
	return predicate.Manifest(sql.FieldNotNull(FieldDateCreated))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Manifest) predicate.Manifest {
	return predicate.Manifest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Manifest) predicate.Manifest {
	return predicate.Manifest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Manifest) predicate.Manifest {
	return predicate.Manifest(sql.NotPredicates(p))
}
