// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/binding.proto

package schema

import (
	ent "github.com/protobuf-orm/ent"
	entsql "github.com/protobuf-orm/ent/dialect/entsql"
	schema "github.com/protobuf-orm/ent/schema"
	edge "github.com/protobuf-orm/ent/schema/edge"
	field "github.com/protobuf-orm/ent/schema/field"
	index "github.com/protobuf-orm/ent/schema/index"
)

type Binding struct {
	ent.Schema
}

func (Binding) Fields() []ent.Field {
	return []ent.Field{
		field.Uuid("id").
			Unique().
			Immutable(),
		field.String("alias"),
		field.String("desc"),
		field.String("subject"),
		field.String("group"),
		field.String("repo"),
		field.Json("actions", []string{}).
			Optional(),
		field.Json("when", map[string]string{}).
			Optional(),
		field.Time("date_erased").
			Nillable().
			Optional(),
		field.Time("date_updated"),
		field.Time("date_created").
			Immutable().
			Optional(),
		field.Uuid("tenant_id").
			Immutable(),
	}
}

func (Binding) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("tenant", Tenant.Type).
			Unique().
			Field("tenant_id").
			Required().
			Immutable(),
	}
}

func (Binding) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("date_created", "id"),
		index.Fields("alias").
			Edges("tenant").
			Unique().
			Annotations(entsql.IndexWhere("date_erased IS NULL")),
	}
}

func (Binding) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "binding"},
	}
}
