// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
	"uuid"

	"github.com/lesomnus/cr/internal/ent/binding"
	"github.com/lesomnus/cr/internal/ent/tenant"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Binding is the model entity for the Binding schema.
type Binding struct {
	config `json:"-"`
	// Id of the ent.
	Id uuid.UUID `json:"id,omitempty"`
	// Alias holds the value of the "alias" field.
	Alias string `json:"alias,omitempty"`
	// Desc holds the value of the "desc" field.
	Desc string `json:"desc,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// Group holds the value of the "group" field.
	Group string `json:"group,omitempty"`
	// Repo holds the value of the "repo" field.
	Repo string `json:"repo,omitempty"`
	// Actions holds the value of the "actions" field.
	Actions []string `json:"actions,omitempty"`
	// When holds the value of the "when" field.
	When map[string]string `json:"when,omitempty"`
	// DateErased holds the value of the "date_erased" field.
	DateErased *time.Time `json:"date_erased,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated time.Time `json:"date_updated,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// TenantId holds the value of the "tenant_id" field.
	TenantId uuid.UUID `json:"tenant_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BindingQuery when eager-loading is set.
	Edges        BindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BindingEdges holds the relations/edges for other nodes in the graph.
type BindingEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BindingEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Binding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case binding.FieldActions, binding.FieldWhen:
			values[i] = new([]byte)
		case binding.FieldAlias, binding.FieldDesc, binding.FieldSubject, binding.FieldGroup, binding.FieldRepo:
			values[i] = new(sql.NullString)
		case binding.FieldDateErased, binding.FieldDateUpdated, binding.FieldDateCreated:
			values[i] = new(sql.NullTime)
		case binding.FieldId, binding.FieldTenantId:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Binding fields.
func (_m *Binding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case binding.FieldId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.Id = *value
			}
		case binding.FieldAlias:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alias", values[i])
			} else if value.Valid {
				_m.Alias = value.String
			}
		case binding.FieldDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field desc", values[i])
			} else if value.Valid {
				_m.Desc = value.String
			}
		case binding.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case binding.FieldGroup:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group", values[i])
			} else if value.Valid {
				_m.Group = value.String
			}
		case binding.FieldRepo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo", values[i])
			} else if value.Valid {
				_m.Repo = value.String
			}
		case binding.FieldActions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field actions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Actions); err != nil {
					return fmt.Errorf("unmarshal field actions: %w", err)
				}
			}
		case binding.FieldWhen:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field when", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.When); err != nil {
					return fmt.Errorf("unmarshal field when: %w", err)
				}
			}
		case binding.FieldDateErased:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_erased", values[i])
			} else if value.Valid {
				_m.DateErased = new(time.Time)
				*_m.DateErased = value.Time
			}
		case binding.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = value.Time
			}
		case binding.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case binding.FieldTenantId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantId = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Binding.
// This includes values selected through modifiers, order, etc.
func (_m *Binding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the Binding entity.
func (_m *Binding) QueryTenant() *TenantQuery {
	return NewBindingClient(_m.config).QueryTenant(_m)
}

// Update returns a builder for updating this Binding.
// Note that you need to call Binding.Unwrap() before calling this method if this Binding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Binding) Update() *BindingUpdateOne {
	return NewBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Binding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Binding) Unwrap() *Binding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Binding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Binding) String() string {
	var builder strings.Builder
	builder.WriteString("Binding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.Id))
	builder.WriteString("alias=")
	builder.WriteString(_m.Alias)
	builder.WriteString(", ")
	builder.WriteString("desc=")
	builder.WriteString(_m.Desc)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("group=")
	builder.WriteString(_m.Group)
	builder.WriteString(", ")
	builder.WriteString("repo=")
	builder.WriteString(_m.Repo)
	builder.WriteString(", ")
	builder.WriteString("actions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Actions))
	builder.WriteString(", ")
	builder.WriteString("when=")
	builder.WriteString(fmt.Sprintf("%v", _m.When))
	builder.WriteString(", ")
	if v := _m.DateErased; v != nil {
		builder.WriteString("date_erased=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("date_updated=")
	builder.WriteString(_m.DateUpdated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantId))
	builder.WriteByte(')')
	return builder.String()
}

// BindingList is a parsable slice of Binding.
type BindingList []*Binding
