// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/lesomnus/cr/internal/ent/binding"
	"github.com/lesomnus/cr/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/dialect/sql/sqljson"
	"github.com/protobuf-orm/ent/schema/field"
)

// BindingUpdate is the builder for updating Binding entities.
type BindingUpdate struct {
	config
	hooks     []Hook
	mutation  *BindingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BindingUpdate builder.
func (_u *BindingUpdate) Where(ps ...predicate.Binding) *BindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAlias sets the "alias" field.
func (_u *BindingUpdate) SetAlias(v string) *BindingUpdate {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *BindingUpdate) SetNillableAlias(v *string) *BindingUpdate {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *BindingUpdate) SetDesc(v string) *BindingUpdate {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *BindingUpdate) SetNillableDesc(v *string) *BindingUpdate {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *BindingUpdate) SetSubject(v string) *BindingUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *BindingUpdate) SetNillableSubject(v *string) *BindingUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetGroup sets the "group" field.
func (_u *BindingUpdate) SetGroup(v string) *BindingUpdate {
	_u.mutation.SetGroup(v)
	return _u
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_u *BindingUpdate) SetNillableGroup(v *string) *BindingUpdate {
	if v != nil {
		_u.SetGroup(*v)
	}
	return _u
}

// SetRepo sets the "repo" field.
func (_u *BindingUpdate) SetRepo(v string) *BindingUpdate {
	_u.mutation.SetRepo(v)
	return _u
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (_u *BindingUpdate) SetNillableRepo(v *string) *BindingUpdate {
	if v != nil {
		_u.SetRepo(*v)
	}
	return _u
}

// SetActions sets the "actions" field.
func (_u *BindingUpdate) SetActions(v []string) *BindingUpdate {
	_u.mutation.SetActions(v)
	return _u
}

// AppendActions appends value to the "actions" field.
func (_u *BindingUpdate) AppendActions(v []string) *BindingUpdate {
	_u.mutation.AppendActions(v)
	return _u
}

// ClearActions clears the value of the "actions" field.
func (_u *BindingUpdate) ClearActions() *BindingUpdate {
	_u.mutation.ClearActions()
	return _u
}

// SetWhen sets the "when" field.
func (_u *BindingUpdate) SetWhen(v map[string]string) *BindingUpdate {
	_u.mutation.SetWhen(v)
	return _u
}

// ClearWhen clears the value of the "when" field.
func (_u *BindingUpdate) ClearWhen() *BindingUpdate {
	_u.mutation.ClearWhen()
	return _u
}

// SetDateErased sets the "date_erased" field.
func (_u *BindingUpdate) SetDateErased(v time.Time) *BindingUpdate {
	_u.mutation.SetDateErased(v)
	return _u
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_u *BindingUpdate) SetNillableDateErased(v *time.Time) *BindingUpdate {
	if v != nil {
		_u.SetDateErased(*v)
	}
	return _u
}

// ClearDateErased clears the value of the "date_erased" field.
func (_u *BindingUpdate) ClearDateErased() *BindingUpdate {
	_u.mutation.ClearDateErased()
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *BindingUpdate) SetDateUpdated(v time.Time) *BindingUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *BindingUpdate) SetNillableDateUpdated(v *time.Time) *BindingUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// Mutation returns the BindingMutation object of the builder.
func (_u *BindingUpdate) Mutation() *BindingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BindingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BindingUpdate) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Binding.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BindingUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BindingUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(binding.Table, binding.Columns, sqlgraph.NewFieldSpec(binding.FieldId, field.TypeUuid))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(binding.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(binding.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(binding.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Group(); ok {
		_spec.SetField(binding.FieldGroup, field.TypeString, value)
	}
	if value, ok := _u.mutation.Repo(); ok {
		_spec.SetField(binding.FieldRepo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(binding.FieldActions, field.TypeJson, value)
	}
	if value, ok := _u.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, binding.FieldActions, value)
		})
	}
	if _u.mutation.ActionsCleared() {
		_spec.ClearField(binding.FieldActions, field.TypeJson)
	}
	if value, ok := _u.mutation.When(); ok {
		_spec.SetField(binding.FieldWhen, field.TypeJson, value)
	}
	if _u.mutation.WhenCleared() {
		_spec.ClearField(binding.FieldWhen, field.TypeJson)
	}
	if value, ok := _u.mutation.DateErased(); ok {
		_spec.SetField(binding.FieldDateErased, field.TypeTime, value)
	}
	if _u.mutation.DateErasedCleared() {
		_spec.ClearField(binding.FieldDateErased, field.TypeTime)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(binding.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(binding.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{binding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BindingUpdateOne is the builder for updating a single Binding entity.
type BindingUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BindingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetAlias sets the "alias" field.
func (_u *BindingUpdateOne) SetAlias(v string) *BindingUpdateOne {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *BindingUpdateOne) SetNillableAlias(v *string) *BindingUpdateOne {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *BindingUpdateOne) SetDesc(v string) *BindingUpdateOne {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *BindingUpdateOne) SetNillableDesc(v *string) *BindingUpdateOne {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *BindingUpdateOne) SetSubject(v string) *BindingUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *BindingUpdateOne) SetNillableSubject(v *string) *BindingUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetGroup sets the "group" field.
func (_u *BindingUpdateOne) SetGroup(v string) *BindingUpdateOne {
	_u.mutation.SetGroup(v)
	return _u
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_u *BindingUpdateOne) SetNillableGroup(v *string) *BindingUpdateOne {
	if v != nil {
		_u.SetGroup(*v)
	}
	return _u
}

// SetRepo sets the "repo" field.
func (_u *BindingUpdateOne) SetRepo(v string) *BindingUpdateOne {
	_u.mutation.SetRepo(v)
	return _u
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (_u *BindingUpdateOne) SetNillableRepo(v *string) *BindingUpdateOne {
	if v != nil {
		_u.SetRepo(*v)
	}
	return _u
}

// SetActions sets the "actions" field.
func (_u *BindingUpdateOne) SetActions(v []string) *BindingUpdateOne {
	_u.mutation.SetActions(v)
	return _u
}

// AppendActions appends value to the "actions" field.
func (_u *BindingUpdateOne) AppendActions(v []string) *BindingUpdateOne {
	_u.mutation.AppendActions(v)
	return _u
}

// ClearActions clears the value of the "actions" field.
func (_u *BindingUpdateOne) ClearActions() *BindingUpdateOne {
	_u.mutation.ClearActions()
	return _u
}

// SetWhen sets the "when" field.
func (_u *BindingUpdateOne) SetWhen(v map[string]string) *BindingUpdateOne {
	_u.mutation.SetWhen(v)
	return _u
}

// ClearWhen clears the value of the "when" field.
func (_u *BindingUpdateOne) ClearWhen() *BindingUpdateOne {
	_u.mutation.ClearWhen()
	return _u
}

// SetDateErased sets the "date_erased" field.
func (_u *BindingUpdateOne) SetDateErased(v time.Time) *BindingUpdateOne {
	_u.mutation.SetDateErased(v)
	return _u
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_u *BindingUpdateOne) SetNillableDateErased(v *time.Time) *BindingUpdateOne {
	if v != nil {
		_u.SetDateErased(*v)
	}
	return _u
}

// ClearDateErased clears the value of the "date_erased" field.
func (_u *BindingUpdateOne) ClearDateErased() *BindingUpdateOne {
	_u.mutation.ClearDateErased()
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *BindingUpdateOne) SetDateUpdated(v time.Time) *BindingUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *BindingUpdateOne) SetNillableDateUpdated(v *time.Time) *BindingUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// Mutation returns the BindingMutation object of the builder.
func (_u *BindingUpdateOne) Mutation() *BindingMutation {
	return _u.mutation
}

// Where appends a list predicates to the BindingUpdate builder.
func (_u *BindingUpdateOne) Where(ps ...predicate.Binding) *BindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BindingUpdateOne) Select(field string, fields ...string) *BindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Binding entity.
func (_u *BindingUpdateOne) Save(ctx context.Context) (*Binding, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BindingUpdateOne) SaveX(ctx context.Context) *Binding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BindingUpdateOne) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Binding.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BindingUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BindingUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BindingUpdateOne) sqlSave(ctx context.Context) (_node *Binding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(binding.Table, binding.Columns, sqlgraph.NewFieldSpec(binding.FieldId, field.TypeUuid))
	id, ok := _u.mutation.Id()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Binding.id" for update`)}
	}
	_spec.Node.Id.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, binding.FieldId)
		for _, f := range fields {
			if !binding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != binding.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(binding.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(binding.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(binding.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Group(); ok {
		_spec.SetField(binding.FieldGroup, field.TypeString, value)
	}
	if value, ok := _u.mutation.Repo(); ok {
		_spec.SetField(binding.FieldRepo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actions(); ok {
		_spec.SetField(binding.FieldActions, field.TypeJson, value)
	}
	if value, ok := _u.mutation.AppendedActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, binding.FieldActions, value)
		})
	}
	if _u.mutation.ActionsCleared() {
		_spec.ClearField(binding.FieldActions, field.TypeJson)
	}
	if value, ok := _u.mutation.When(); ok {
		_spec.SetField(binding.FieldWhen, field.TypeJson, value)
	}
	if _u.mutation.WhenCleared() {
		_spec.ClearField(binding.FieldWhen, field.TypeJson)
	}
	if value, ok := _u.mutation.DateErased(); ok {
		_spec.SetField(binding.FieldDateErased, field.TypeTime, value)
	}
	if _u.mutation.DateErasedCleared() {
		_spec.ClearField(binding.FieldDateErased, field.TypeTime)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(binding.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(binding.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Binding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{binding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
