// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/gc_run.proto

package ent

import (
	api "github.com/lesomnus/cr/api"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *GcRun) Proto() *api.GcRun {
	x := &api.GcRun{}
	x.SetId(e.Id[:])
	x.SetKind(e.Kind)
	x.SetTrigger(e.Trigger)
	x.SetState(e.State)
	x.SetError(e.Error)
	x.SetStages(e.Stages)
	x.SetTags(e.Tags)
	x.SetManifests(e.Manifests)
	x.SetRepositories(e.Repositories)
	x.SetBlobs(e.Blobs)
	x.SetBytes(e.Bytes)
	x.SetMissing(e.Missing)
	if e.DateFinished != nil {
		x.SetDateFinished(timestamppb.New(*e.DateFinished))
	}
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
