// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/cr/internal/ent/gcrun"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// GcRunCreate is the builder for creating a GcRun entity.
type GcRunCreate struct {
	config
	mutation *GcRunMutation
	hooks    []Hook
}

// SetKind sets the "kind" field.
func (_c *GcRunCreate) SetKind(v string) *GcRunCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetTrigger sets the "trigger" field.
func (_c *GcRunCreate) SetTrigger(v string) *GcRunCreate {
	_c.mutation.SetTrigger(v)
	return _c
}

// SetState sets the "state" field.
func (_c *GcRunCreate) SetState(v string) *GcRunCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetError sets the "error" field.
func (_c *GcRunCreate) SetError(v string) *GcRunCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetStages sets the "stages" field.
func (_c *GcRunCreate) SetStages(v int64) *GcRunCreate {
	_c.mutation.SetStages(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *GcRunCreate) SetTags(v int64) *GcRunCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetManifests sets the "manifests" field.
func (_c *GcRunCreate) SetManifests(v int64) *GcRunCreate {
	_c.mutation.SetManifests(v)
	return _c
}

// SetRepositories sets the "repositories" field.
func (_c *GcRunCreate) SetRepositories(v int64) *GcRunCreate {
	_c.mutation.SetRepositories(v)
	return _c
}

// SetBlobs sets the "blobs" field.
func (_c *GcRunCreate) SetBlobs(v int64) *GcRunCreate {
	_c.mutation.SetBlobs(v)
	return _c
}

// SetBytes sets the "bytes" field.
func (_c *GcRunCreate) SetBytes(v int64) *GcRunCreate {
	_c.mutation.SetBytes(v)
	return _c
}

// SetMissing sets the "missing" field.
func (_c *GcRunCreate) SetMissing(v []string) *GcRunCreate {
	_c.mutation.SetMissing(v)
	return _c
}

// SetDateFinished sets the "date_finished" field.
func (_c *GcRunCreate) SetDateFinished(v time.Time) *GcRunCreate {
	_c.mutation.SetDateFinished(v)
	return _c
}

// SetNillableDateFinished sets the "date_finished" field if the given value is not nil.
func (_c *GcRunCreate) SetNillableDateFinished(v *time.Time) *GcRunCreate {
	if v != nil {
		_c.SetDateFinished(*v)
	}
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *GcRunCreate) SetDateUpdated(v time.Time) *GcRunCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *GcRunCreate) SetDateCreated(v time.Time) *GcRunCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *GcRunCreate) SetNillableDateCreated(v *time.Time) *GcRunCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetId sets the "id" field.
func (_c *GcRunCreate) SetId(v uuid.UUID) *GcRunCreate {
	_c.mutation.SetId(v)
	return _c
}

// Mutation returns the GcRunMutation object of the builder.
func (_c *GcRunCreate) Mutation() *GcRunMutation {
	return _c.mutation
}

// Save creates the GcRun in the database.
func (_c *GcRunCreate) Save(ctx context.Context) (*GcRun, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GcRunCreate) SaveX(ctx context.Context) *GcRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GcRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GcRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GcRunCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "GcRun.kind"`)}
	}
	if _, ok := _c.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "GcRun.trigger"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "GcRun.state"`)}
	}
	if _, ok := _c.mutation.Error(); !ok {
		return &ValidationError{Name: "error", err: errors.New(`ent: missing required field "GcRun.error"`)}
	}
	if _, ok := _c.mutation.Stages(); !ok {
		return &ValidationError{Name: "stages", err: errors.New(`ent: missing required field "GcRun.stages"`)}
	}
	if _, ok := _c.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "GcRun.tags"`)}
	}
	if _, ok := _c.mutation.Manifests(); !ok {
		return &ValidationError{Name: "manifests", err: errors.New(`ent: missing required field "GcRun.manifests"`)}
	}
	if _, ok := _c.mutation.Repositories(); !ok {
		return &ValidationError{Name: "repositories", err: errors.New(`ent: missing required field "GcRun.repositories"`)}
	}
	if _, ok := _c.mutation.Blobs(); !ok {
		return &ValidationError{Name: "blobs", err: errors.New(`ent: missing required field "GcRun.blobs"`)}
	}
	if _, ok := _c.mutation.Bytes(); !ok {
		return &ValidationError{Name: "bytes", err: errors.New(`ent: missing required field "GcRun.bytes"`)}
	}
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "GcRun.date_updated"`)}
	}
	return nil
}

func (_c *GcRunCreate) sqlSave(ctx context.Context) (*GcRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		if id, ok := _spec.Id.Value.(*uuid.UUID); ok {
			_node.Id = *id
		} else {
			var v sql.Null[uuid.UUID]
			if err := v.Scan(_spec.Id.Value); err != nil {
				return nil, err
			}
			_node.Id = v.V
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *GcRunCreate) createSpec() (*GcRun, *sqlgraph.CreateSpec) {
	var (
		_node = &GcRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gcrun.Table, sqlgraph.NewFieldSpec(gcrun.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		_spec.Id.Value = &id
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(gcrun.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Trigger(); ok {
		_spec.SetField(gcrun.FieldTrigger, field.TypeString, value)
		_node.Trigger = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(gcrun.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(gcrun.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.Stages(); ok {
		_spec.SetField(gcrun.FieldStages, field.TypeInt64, value)
		_node.Stages = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(gcrun.FieldTags, field.TypeInt64, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Manifests(); ok {
		_spec.SetField(gcrun.FieldManifests, field.TypeInt64, value)
		_node.Manifests = value
	}
	if value, ok := _c.mutation.Repositories(); ok {
		_spec.SetField(gcrun.FieldRepositories, field.TypeInt64, value)
		_node.Repositories = value
	}
	if value, ok := _c.mutation.Blobs(); ok {
		_spec.SetField(gcrun.FieldBlobs, field.TypeInt64, value)
		_node.Blobs = value
	}
	if value, ok := _c.mutation.Bytes(); ok {
		_spec.SetField(gcrun.FieldBytes, field.TypeInt64, value)
		_node.Bytes = value
	}
	if value, ok := _c.mutation.Missing(); ok {
		_spec.SetField(gcrun.FieldMissing, field.TypeJson, value)
		_node.Missing = value
	}
	if value, ok := _c.mutation.DateFinished(); ok {
		_spec.SetField(gcrun.FieldDateFinished, field.TypeTime, value)
		_node.DateFinished = &value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(gcrun.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(gcrun.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	return _node, _spec
}

// GcRunCreateBulk is the builder for creating many GcRun entities in bulk.
type GcRunCreateBulk struct {
	config
	err      error
	builders []*GcRunCreate
}

// Save creates the GcRun entities in the database.
func (_c *GcRunCreateBulk) Save(ctx context.Context) ([]*GcRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GcRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GcRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GcRunCreateBulk) SaveX(ctx context.Context) []*GcRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GcRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GcRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
