// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/lesomnus/cr/internal/ent/manifest"
	"github.com/lesomnus/cr/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// ManifestUpdate is the builder for updating Manifest entities.
type ManifestUpdate struct {
	config
	hooks     []Hook
	mutation  *ManifestMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ManifestUpdate builder.
func (_u *ManifestUpdate) Where(ps ...predicate.Manifest) *ManifestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAnnotations sets the "annotations" field.
func (_u *ManifestUpdate) SetAnnotations(v map[string]string) *ManifestUpdate {
	_u.mutation.SetAnnotations(v)
	return _u
}

// ClearAnnotations clears the value of the "annotations" field.
func (_u *ManifestUpdate) ClearAnnotations() *ManifestUpdate {
	_u.mutation.ClearAnnotations()
	return _u
}

// SetDatePulled sets the "date_pulled" field.
func (_u *ManifestUpdate) SetDatePulled(v time.Time) *ManifestUpdate {
	_u.mutation.SetDatePulled(v)
	return _u
}

// SetNillableDatePulled sets the "date_pulled" field if the given value is not nil.
func (_u *ManifestUpdate) SetNillableDatePulled(v *time.Time) *ManifestUpdate {
	if v != nil {
		_u.SetDatePulled(*v)
	}
	return _u
}

// ClearDatePulled clears the value of the "date_pulled" field.
func (_u *ManifestUpdate) ClearDatePulled() *ManifestUpdate {
	_u.mutation.ClearDatePulled()
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *ManifestUpdate) SetDateUpdated(v time.Time) *ManifestUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *ManifestUpdate) SetNillableDateUpdated(v *time.Time) *ManifestUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// Mutation returns the ManifestMutation object of the builder.
func (_u *ManifestUpdate) Mutation() *ManifestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ManifestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManifestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ManifestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManifestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ManifestUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ManifestUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ManifestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(manifest.Table, manifest.Columns, sqlgraph.NewFieldSpec(manifest.FieldId, field.TypeUuid))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Annotations(); ok {
		_spec.SetField(manifest.FieldAnnotations, field.TypeJson, value)
	}
	if _u.mutation.AnnotationsCleared() {
		_spec.ClearField(manifest.FieldAnnotations, field.TypeJson)
	}
	if value, ok := _u.mutation.DatePulled(); ok {
		_spec.SetField(manifest.FieldDatePulled, field.TypeTime, value)
	}
	if _u.mutation.DatePulledCleared() {
		_spec.ClearField(manifest.FieldDatePulled, field.TypeTime)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(manifest.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(manifest.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{manifest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ManifestUpdateOne is the builder for updating a single Manifest entity.
type ManifestUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ManifestMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetAnnotations sets the "annotations" field.
func (_u *ManifestUpdateOne) SetAnnotations(v map[string]string) *ManifestUpdateOne {
	_u.mutation.SetAnnotations(v)
	return _u
}

// ClearAnnotations clears the value of the "annotations" field.
func (_u *ManifestUpdateOne) ClearAnnotations() *ManifestUpdateOne {
	_u.mutation.ClearAnnotations()
	return _u
}

// SetDatePulled sets the "date_pulled" field.
func (_u *ManifestUpdateOne) SetDatePulled(v time.Time) *ManifestUpdateOne {
	_u.mutation.SetDatePulled(v)
	return _u
}

// SetNillableDatePulled sets the "date_pulled" field if the given value is not nil.
func (_u *ManifestUpdateOne) SetNillableDatePulled(v *time.Time) *ManifestUpdateOne {
	if v != nil {
		_u.SetDatePulled(*v)
	}
	return _u
}

// ClearDatePulled clears the value of the "date_pulled" field.
func (_u *ManifestUpdateOne) ClearDatePulled() *ManifestUpdateOne {
	_u.mutation.ClearDatePulled()
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *ManifestUpdateOne) SetDateUpdated(v time.Time) *ManifestUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *ManifestUpdateOne) SetNillableDateUpdated(v *time.Time) *ManifestUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// Mutation returns the ManifestMutation object of the builder.
func (_u *ManifestUpdateOne) Mutation() *ManifestMutation {
	return _u.mutation
}

// Where appends a list predicates to the ManifestUpdate builder.
func (_u *ManifestUpdateOne) Where(ps ...predicate.Manifest) *ManifestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ManifestUpdateOne) Select(field string, fields ...string) *ManifestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Manifest entity.
func (_u *ManifestUpdateOne) Save(ctx context.Context) (*Manifest, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManifestUpdateOne) SaveX(ctx context.Context) *Manifest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ManifestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManifestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ManifestUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ManifestUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ManifestUpdateOne) sqlSave(ctx context.Context) (_node *Manifest, err error) {
	_spec := sqlgraph.NewUpdateSpec(manifest.Table, manifest.Columns, sqlgraph.NewFieldSpec(manifest.FieldId, field.TypeUuid))
	id, ok := _u.mutation.Id()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Manifest.id" for update`)}
	}
	_spec.Node.Id.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, manifest.FieldId)
		for _, f := range fields {
			if !manifest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != manifest.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Annotations(); ok {
		_spec.SetField(manifest.FieldAnnotations, field.TypeJson, value)
	}
	if _u.mutation.AnnotationsCleared() {
		_spec.ClearField(manifest.FieldAnnotations, field.TypeJson)
	}
	if value, ok := _u.mutation.DatePulled(); ok {
		_spec.SetField(manifest.FieldDatePulled, field.TypeTime, value)
	}
	if _u.mutation.DatePulledCleared() {
		_spec.ClearField(manifest.FieldDatePulled, field.TypeTime)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(manifest.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(manifest.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Manifest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{manifest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
