// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"uuid"

	"github.com/lesomnus/cr/internal/ent/manifestblob"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// ManifestBlob is the model entity for the ManifestBlob schema.
type ManifestBlob struct {
	config `json:"-"`
	// Id of the ent.
	Id uuid.UUID `json:"id,omitempty"`
	// Repo holds the value of the "repo" field.
	Repo string `json:"repo,omitempty"`
	// Manifest holds the value of the "manifest" field.
	Manifest string `json:"manifest,omitempty"`
	// Blob holds the value of the "blob" field.
	Blob string `json:"blob,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated  time.Time `json:"date_created,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ManifestBlob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case manifestblob.FieldRepo, manifestblob.FieldManifest, manifestblob.FieldBlob:
			values[i] = new(sql.NullString)
		case manifestblob.FieldDateCreated:
			values[i] = new(sql.NullTime)
		case manifestblob.FieldId:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ManifestBlob fields.
func (_m *ManifestBlob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case manifestblob.FieldId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.Id = *value
			}
		case manifestblob.FieldRepo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo", values[i])
			} else if value.Valid {
				_m.Repo = value.String
			}
		case manifestblob.FieldManifest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manifest", values[i])
			} else if value.Valid {
				_m.Manifest = value.String
			}
		case manifestblob.FieldBlob:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field blob", values[i])
			} else if value.Valid {
				_m.Blob = value.String
			}
		case manifestblob.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ManifestBlob.
// This includes values selected through modifiers, order, etc.
func (_m *ManifestBlob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ManifestBlob.
// Note that you need to call ManifestBlob.Unwrap() before calling this method if this ManifestBlob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ManifestBlob) Update() *ManifestBlobUpdateOne {
	return NewManifestBlobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ManifestBlob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ManifestBlob) Unwrap() *ManifestBlob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ManifestBlob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ManifestBlob) String() string {
	var builder strings.Builder
	builder.WriteString("ManifestBlob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.Id))
	builder.WriteString("repo=")
	builder.WriteString(_m.Repo)
	builder.WriteString(", ")
	builder.WriteString("manifest=")
	builder.WriteString(_m.Manifest)
	builder.WriteString(", ")
	builder.WriteString("blob=")
	builder.WriteString(_m.Blob)
	builder.WriteString(", ")
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ManifestBlobList is a parsable slice of ManifestBlob.
type ManifestBlobList []*ManifestBlob
