// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/cr/internal/ent/referrerssnapshot"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// ReferrersSnapshotCreate is the builder for creating a ReferrersSnapshot entity.
type ReferrersSnapshotCreate struct {
	config
	mutation *ReferrersSnapshotMutation
	hooks    []Hook
}

// SetRepo sets the "repo" field.
func (_c *ReferrersSnapshotCreate) SetRepo(v string) *ReferrersSnapshotCreate {
	_c.mutation.SetRepo(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *ReferrersSnapshotCreate) SetSubject(v string) *ReferrersSnapshotCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetSupported sets the "supported" field.
func (_c *ReferrersSnapshotCreate) SetSupported(v bool) *ReferrersSnapshotCreate {
	_c.mutation.SetSupported(v)
	return _c
}

// SetDescriptors sets the "descriptors" field.
func (_c *ReferrersSnapshotCreate) SetDescriptors(v []byte) *ReferrersSnapshotCreate {
	_c.mutation.SetDescriptors(v)
	return _c
}

// SetDateChecked sets the "date_checked" field.
func (_c *ReferrersSnapshotCreate) SetDateChecked(v time.Time) *ReferrersSnapshotCreate {
	_c.mutation.SetDateChecked(v)
	return _c
}

// SetNillableDateChecked sets the "date_checked" field if the given value is not nil.
func (_c *ReferrersSnapshotCreate) SetNillableDateChecked(v *time.Time) *ReferrersSnapshotCreate {
	if v != nil {
		_c.SetDateChecked(*v)
	}
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *ReferrersSnapshotCreate) SetDateUpdated(v time.Time) *ReferrersSnapshotCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *ReferrersSnapshotCreate) SetDateCreated(v time.Time) *ReferrersSnapshotCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *ReferrersSnapshotCreate) SetNillableDateCreated(v *time.Time) *ReferrersSnapshotCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetId sets the "id" field.
func (_c *ReferrersSnapshotCreate) SetId(v uuid.UUID) *ReferrersSnapshotCreate {
	_c.mutation.SetId(v)
	return _c
}

// Mutation returns the ReferrersSnapshotMutation object of the builder.
func (_c *ReferrersSnapshotCreate) Mutation() *ReferrersSnapshotMutation {
	return _c.mutation
}

// Save creates the ReferrersSnapshot in the database.
func (_c *ReferrersSnapshotCreate) Save(ctx context.Context) (*ReferrersSnapshot, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReferrersSnapshotCreate) SaveX(ctx context.Context) *ReferrersSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferrersSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferrersSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReferrersSnapshotCreate) check() error {
	if _, ok := _c.mutation.Repo(); !ok {
		return &ValidationError{Name: "repo", err: errors.New(`ent: missing required field "ReferrersSnapshot.repo"`)}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "ReferrersSnapshot.subject"`)}
	}
	if _, ok := _c.mutation.Supported(); !ok {
		return &ValidationError{Name: "supported", err: errors.New(`ent: missing required field "ReferrersSnapshot.supported"`)}
	}
	if _, ok := _c.mutation.Descriptors(); !ok {
		return &ValidationError{Name: "descriptors", err: errors.New(`ent: missing required field "ReferrersSnapshot.descriptors"`)}
	}
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "ReferrersSnapshot.date_updated"`)}
	}
	return nil
}

func (_c *ReferrersSnapshotCreate) sqlSave(ctx context.Context) (*ReferrersSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		if id, ok := _spec.Id.Value.(*uuid.UUID); ok {
			_node.Id = *id
		} else {
			var v sql.Null[uuid.UUID]
			if err := v.Scan(_spec.Id.Value); err != nil {
				return nil, err
			}
			_node.Id = v.V
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReferrersSnapshotCreate) createSpec() (*ReferrersSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &ReferrersSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(referrerssnapshot.Table, sqlgraph.NewFieldSpec(referrerssnapshot.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		_spec.Id.Value = &id
	}
	if value, ok := _c.mutation.Repo(); ok {
		_spec.SetField(referrerssnapshot.FieldRepo, field.TypeString, value)
		_node.Repo = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(referrerssnapshot.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Supported(); ok {
		_spec.SetField(referrerssnapshot.FieldSupported, field.TypeBool, value)
		_node.Supported = value
	}
	if value, ok := _c.mutation.Descriptors(); ok {
		_spec.SetField(referrerssnapshot.FieldDescriptors, field.TypeBytes, value)
		_node.Descriptors = value
	}
	if value, ok := _c.mutation.DateChecked(); ok {
		_spec.SetField(referrerssnapshot.FieldDateChecked, field.TypeTime, value)
		_node.DateChecked = value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(referrerssnapshot.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(referrerssnapshot.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	return _node, _spec
}

// ReferrersSnapshotCreateBulk is the builder for creating many ReferrersSnapshot entities in bulk.
type ReferrersSnapshotCreateBulk struct {
	config
	err      error
	builders []*ReferrersSnapshotCreate
}

// Save creates the ReferrersSnapshot entities in the database.
func (_c *ReferrersSnapshotCreateBulk) Save(ctx context.Context) ([]*ReferrersSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReferrersSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReferrersSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReferrersSnapshotCreateBulk) SaveX(ctx context.Context) []*ReferrersSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferrersSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferrersSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
