// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/lesomnus/cr/internal/ent/predicate"
	"github.com/lesomnus/cr/internal/ent/referrerssnapshot"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// ReferrersSnapshotUpdate is the builder for updating ReferrersSnapshot entities.
type ReferrersSnapshotUpdate struct {
	config
	hooks     []Hook
	mutation  *ReferrersSnapshotMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ReferrersSnapshotUpdate builder.
func (_u *ReferrersSnapshotUpdate) Where(ps ...predicate.ReferrersSnapshot) *ReferrersSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSupported sets the "supported" field.
func (_u *ReferrersSnapshotUpdate) SetSupported(v bool) *ReferrersSnapshotUpdate {
	_u.mutation.SetSupported(v)
	return _u
}

// SetNillableSupported sets the "supported" field if the given value is not nil.
func (_u *ReferrersSnapshotUpdate) SetNillableSupported(v *bool) *ReferrersSnapshotUpdate {
	if v != nil {
		_u.SetSupported(*v)
	}
	return _u
}

// SetDescriptors sets the "descriptors" field.
func (_u *ReferrersSnapshotUpdate) SetDescriptors(v []byte) *ReferrersSnapshotUpdate {
	_u.mutation.SetDescriptors(v)
	return _u
}

// SetDateObserved sets the "date_observed" field.
func (_u *ReferrersSnapshotUpdate) SetDateObserved(v time.Time) *ReferrersSnapshotUpdate {
	_u.mutation.SetDateObserved(v)
	return _u
}

// SetNillableDateObserved sets the "date_observed" field if the given value is not nil.
func (_u *ReferrersSnapshotUpdate) SetNillableDateObserved(v *time.Time) *ReferrersSnapshotUpdate {
	if v != nil {
		_u.SetDateObserved(*v)
	}
	return _u
}

// ClearDateObserved clears the value of the "date_observed" field.
func (_u *ReferrersSnapshotUpdate) ClearDateObserved() *ReferrersSnapshotUpdate {
	_u.mutation.ClearDateObserved()
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *ReferrersSnapshotUpdate) SetDateUpdated(v time.Time) *ReferrersSnapshotUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *ReferrersSnapshotUpdate) SetNillableDateUpdated(v *time.Time) *ReferrersSnapshotUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// Mutation returns the ReferrersSnapshotMutation object of the builder.
func (_u *ReferrersSnapshotUpdate) Mutation() *ReferrersSnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReferrersSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferrersSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReferrersSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferrersSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ReferrersSnapshotUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ReferrersSnapshotUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ReferrersSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(referrerssnapshot.Table, referrerssnapshot.Columns, sqlgraph.NewFieldSpec(referrerssnapshot.FieldId, field.TypeUuid))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Supported(); ok {
		_spec.SetField(referrerssnapshot.FieldSupported, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Descriptors(); ok {
		_spec.SetField(referrerssnapshot.FieldDescriptors, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.DateObserved(); ok {
		_spec.SetField(referrerssnapshot.FieldDateObserved, field.TypeTime, value)
	}
	if _u.mutation.DateObservedCleared() {
		_spec.ClearField(referrerssnapshot.FieldDateObserved, field.TypeTime)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(referrerssnapshot.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(referrerssnapshot.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referrerssnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReferrersSnapshotUpdateOne is the builder for updating a single ReferrersSnapshot entity.
type ReferrersSnapshotUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ReferrersSnapshotMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetSupported sets the "supported" field.
func (_u *ReferrersSnapshotUpdateOne) SetSupported(v bool) *ReferrersSnapshotUpdateOne {
	_u.mutation.SetSupported(v)
	return _u
}

// SetNillableSupported sets the "supported" field if the given value is not nil.
func (_u *ReferrersSnapshotUpdateOne) SetNillableSupported(v *bool) *ReferrersSnapshotUpdateOne {
	if v != nil {
		_u.SetSupported(*v)
	}
	return _u
}

// SetDescriptors sets the "descriptors" field.
func (_u *ReferrersSnapshotUpdateOne) SetDescriptors(v []byte) *ReferrersSnapshotUpdateOne {
	_u.mutation.SetDescriptors(v)
	return _u
}

// SetDateObserved sets the "date_observed" field.
func (_u *ReferrersSnapshotUpdateOne) SetDateObserved(v time.Time) *ReferrersSnapshotUpdateOne {
	_u.mutation.SetDateObserved(v)
	return _u
}

// SetNillableDateObserved sets the "date_observed" field if the given value is not nil.
func (_u *ReferrersSnapshotUpdateOne) SetNillableDateObserved(v *time.Time) *ReferrersSnapshotUpdateOne {
	if v != nil {
		_u.SetDateObserved(*v)
	}
	return _u
}

// ClearDateObserved clears the value of the "date_observed" field.
func (_u *ReferrersSnapshotUpdateOne) ClearDateObserved() *ReferrersSnapshotUpdateOne {
	_u.mutation.ClearDateObserved()
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *ReferrersSnapshotUpdateOne) SetDateUpdated(v time.Time) *ReferrersSnapshotUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *ReferrersSnapshotUpdateOne) SetNillableDateUpdated(v *time.Time) *ReferrersSnapshotUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// Mutation returns the ReferrersSnapshotMutation object of the builder.
func (_u *ReferrersSnapshotUpdateOne) Mutation() *ReferrersSnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReferrersSnapshotUpdate builder.
func (_u *ReferrersSnapshotUpdateOne) Where(ps ...predicate.ReferrersSnapshot) *ReferrersSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReferrersSnapshotUpdateOne) Select(field string, fields ...string) *ReferrersSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReferrersSnapshot entity.
func (_u *ReferrersSnapshotUpdateOne) Save(ctx context.Context) (*ReferrersSnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferrersSnapshotUpdateOne) SaveX(ctx context.Context) *ReferrersSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReferrersSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferrersSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ReferrersSnapshotUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ReferrersSnapshotUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ReferrersSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *ReferrersSnapshot, err error) {
	_spec := sqlgraph.NewUpdateSpec(referrerssnapshot.Table, referrerssnapshot.Columns, sqlgraph.NewFieldSpec(referrerssnapshot.FieldId, field.TypeUuid))
	id, ok := _u.mutation.Id()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReferrersSnapshot.id" for update`)}
	}
	_spec.Node.Id.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referrerssnapshot.FieldId)
		for _, f := range fields {
			if !referrerssnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != referrerssnapshot.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Supported(); ok {
		_spec.SetField(referrerssnapshot.FieldSupported, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Descriptors(); ok {
		_spec.SetField(referrerssnapshot.FieldDescriptors, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.DateObserved(); ok {
		_spec.SetField(referrerssnapshot.FieldDateObserved, field.TypeTime, value)
	}
	if _u.mutation.DateObservedCleared() {
		_spec.ClearField(referrerssnapshot.FieldDateObserved, field.TypeTime)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(referrerssnapshot.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(referrerssnapshot.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ReferrersSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referrerssnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
