// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"uuid"

	"github.com/lesomnus/cr/internal/ent/referrerssnapshot"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// ReferrersSnapshot is the model entity for the ReferrersSnapshot schema.
type ReferrersSnapshot struct {
	config `json:"-"`
	// Id of the ent.
	Id uuid.UUID `json:"id,omitempty"`
	// Repo holds the value of the "repo" field.
	Repo string `json:"repo,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// Supported holds the value of the "supported" field.
	Supported bool `json:"supported,omitempty"`
	// Descriptors holds the value of the "descriptors" field.
	Descriptors []byte `json:"descriptors,omitempty"`
	// DateChecked holds the value of the "date_checked" field.
	DateChecked time.Time `json:"date_checked,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated time.Time `json:"date_updated,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated  time.Time `json:"date_created,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferrersSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referrerssnapshot.FieldDescriptors:
			values[i] = new([]byte)
		case referrerssnapshot.FieldSupported:
			values[i] = new(sql.NullBool)
		case referrerssnapshot.FieldRepo, referrerssnapshot.FieldSubject:
			values[i] = new(sql.NullString)
		case referrerssnapshot.FieldDateChecked, referrerssnapshot.FieldDateUpdated, referrerssnapshot.FieldDateCreated:
			values[i] = new(sql.NullTime)
		case referrerssnapshot.FieldId:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferrersSnapshot fields.
func (_m *ReferrersSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referrerssnapshot.FieldId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.Id = *value
			}
		case referrerssnapshot.FieldRepo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo", values[i])
			} else if value.Valid {
				_m.Repo = value.String
			}
		case referrerssnapshot.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case referrerssnapshot.FieldSupported:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field supported", values[i])
			} else if value.Valid {
				_m.Supported = value.Bool
			}
		case referrerssnapshot.FieldDescriptors:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field descriptors", values[i])
			} else if value != nil {
				_m.Descriptors = *value
				if _m.Descriptors == nil {
					_m.Descriptors = []byte{}
				}
			}
		case referrerssnapshot.FieldDateChecked:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_checked", values[i])
			} else if value.Valid {
				_m.DateChecked = value.Time
			}
		case referrerssnapshot.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = value.Time
			}
		case referrerssnapshot.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferrersSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *ReferrersSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ReferrersSnapshot.
// Note that you need to call ReferrersSnapshot.Unwrap() before calling this method if this ReferrersSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReferrersSnapshot) Update() *ReferrersSnapshotUpdateOne {
	return NewReferrersSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReferrersSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReferrersSnapshot) Unwrap() *ReferrersSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferrersSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReferrersSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("ReferrersSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.Id))
	builder.WriteString("repo=")
	builder.WriteString(_m.Repo)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("supported=")
	builder.WriteString(fmt.Sprintf("%v", _m.Supported))
	builder.WriteString(", ")
	builder.WriteString("descriptors=")
	builder.WriteString(fmt.Sprintf("%v", _m.Descriptors))
	builder.WriteString(", ")
	builder.WriteString("date_checked=")
	builder.WriteString(_m.DateChecked.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("date_updated=")
	builder.WriteString(_m.DateUpdated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReferrersSnapshotList is a parsable slice of ReferrersSnapshot.
type ReferrersSnapshotList []*ReferrersSnapshot
