// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/repository.proto

package ent

import (
	api "github.com/lesomnus/cr/api"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Repository) Proto() *api.Repository {
	x := &api.Repository{}
	x.SetId(e.Id[:])
	x.SetName(e.Name)
	x.SetDesc(e.Desc)
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
