// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/lesomnus/cr/internal/ent/predicate"
	"github.com/lesomnus/cr/internal/ent/repository"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// RepositoryUpdate is the builder for updating Repository entities.
type RepositoryUpdate struct {
	config
	hooks     []Hook
	mutation  *RepositoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (_u *RepositoryUpdate) Where(ps ...predicate.Repository) *RepositoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDesc sets the "desc" field.
func (_u *RepositoryUpdate) SetDesc(v string) *RepositoryUpdate {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableDesc(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *RepositoryUpdate) SetDateUpdated(v time.Time) *RepositoryUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableDateUpdated(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// Mutation returns the RepositoryMutation object of the builder.
func (_u *RepositoryUpdate) Mutation() *RepositoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RepositoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepositoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RepositoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepositoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RepositoryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RepositoryUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RepositoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldId, field.TypeUuid))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(repository.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(repository.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(repository.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RepositoryUpdateOne is the builder for updating a single Repository entity.
type RepositoryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RepositoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDesc sets the "desc" field.
func (_u *RepositoryUpdateOne) SetDesc(v string) *RepositoryUpdateOne {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableDesc(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *RepositoryUpdateOne) SetDateUpdated(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableDateUpdated(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// Mutation returns the RepositoryMutation object of the builder.
func (_u *RepositoryUpdateOne) Mutation() *RepositoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (_u *RepositoryUpdateOne) Where(ps ...predicate.Repository) *RepositoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RepositoryUpdateOne) Select(field string, fields ...string) *RepositoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Repository entity.
func (_u *RepositoryUpdateOne) Save(ctx context.Context) (*Repository, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepositoryUpdateOne) SaveX(ctx context.Context) *Repository {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RepositoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepositoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RepositoryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RepositoryUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RepositoryUpdateOne) sqlSave(ctx context.Context) (_node *Repository, err error) {
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldId, field.TypeUuid))
	id, ok := _u.mutation.Id()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Repository.id" for update`)}
	}
	_spec.Node.Id.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repository.FieldId)
		for _, f := range fields {
			if !repository.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != repository.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(repository.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(repository.FieldDateUpdated, field.TypeTime, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(repository.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Repository{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
