// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/cr/internal/ent/repository"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// RepositoryCreate is the builder for creating a Repository entity.
type RepositoryCreate struct {
	config
	mutation *RepositoryMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *RepositoryCreate) SetName(v string) *RepositoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDesc sets the "desc" field.
func (_c *RepositoryCreate) SetDesc(v string) *RepositoryCreate {
	_c.mutation.SetDesc(v)
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *RepositoryCreate) SetDateUpdated(v time.Time) *RepositoryCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *RepositoryCreate) SetDateCreated(v time.Time) *RepositoryCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableDateCreated(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetId sets the "id" field.
func (_c *RepositoryCreate) SetId(v uuid.UUID) *RepositoryCreate {
	_c.mutation.SetId(v)
	return _c
}

// Mutation returns the RepositoryMutation object of the builder.
func (_c *RepositoryCreate) Mutation() *RepositoryMutation {
	return _c.mutation
}

// Save creates the Repository in the database.
func (_c *RepositoryCreate) Save(ctx context.Context) (*Repository, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RepositoryCreate) SaveX(ctx context.Context) *Repository {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepositoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepositoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RepositoryCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Repository.name"`)}
	}
	if _, ok := _c.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "Repository.desc"`)}
	}
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "Repository.date_updated"`)}
	}
	return nil
}

func (_c *RepositoryCreate) sqlSave(ctx context.Context) (*Repository, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		if id, ok := _spec.Id.Value.(*uuid.UUID); ok {
			_node.Id = *id
		} else {
			var v sql.Null[uuid.UUID]
			if err := v.Scan(_spec.Id.Value); err != nil {
				return nil, err
			}
			_node.Id = v.V
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *RepositoryCreate) createSpec() (*Repository, *sqlgraph.CreateSpec) {
	var (
		_node = &Repository{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(repository.Table, sqlgraph.NewFieldSpec(repository.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		_spec.Id.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(repository.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Desc(); ok {
		_spec.SetField(repository.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(repository.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(repository.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	return _node, _spec
}

// RepositoryCreateBulk is the builder for creating many Repository entities in bulk.
type RepositoryCreateBulk struct {
	config
	err      error
	builders []*RepositoryCreate
}

// Save creates the Repository entities in the database.
func (_c *RepositoryCreateBulk) Save(ctx context.Context) ([]*Repository, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Repository, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RepositoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RepositoryCreateBulk) SaveX(ctx context.Context) []*Repository {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepositoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepositoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
