// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"uuid"

	"github.com/lesomnus/cr/internal/ent/tag"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Tag is the model entity for the Tag schema.
type Tag struct {
	config `json:"-"`
	// Id of the ent.
	Id uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Repo holds the value of the "repo" field.
	Repo string `json:"repo,omitempty"`
	// Digest holds the value of the "digest" field.
	Digest string `json:"digest,omitempty"`
	// DateMoved holds the value of the "date_moved" field.
	DateMoved time.Time `json:"date_moved,omitempty"`
	// DatePulled holds the value of the "date_pulled" field.
	DatePulled *time.Time `json:"date_pulled,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated time.Time `json:"date_updated,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated  time.Time `json:"date_created,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tag.FieldName, tag.FieldRepo, tag.FieldDigest:
			values[i] = new(sql.NullString)
		case tag.FieldDateMoved, tag.FieldDatePulled, tag.FieldDateUpdated, tag.FieldDateCreated:
			values[i] = new(sql.NullTime)
		case tag.FieldId:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tag fields.
func (_m *Tag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tag.FieldId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.Id = *value
			}
		case tag.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case tag.FieldRepo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo", values[i])
			} else if value.Valid {
				_m.Repo = value.String
			}
		case tag.FieldDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field digest", values[i])
			} else if value.Valid {
				_m.Digest = value.String
			}
		case tag.FieldDateMoved:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_moved", values[i])
			} else if value.Valid {
				_m.DateMoved = value.Time
			}
		case tag.FieldDatePulled:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_pulled", values[i])
			} else if value.Valid {
				_m.DatePulled = new(time.Time)
				*_m.DatePulled = value.Time
			}
		case tag.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = value.Time
			}
		case tag.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tag.
// This includes values selected through modifiers, order, etc.
func (_m *Tag) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Tag.
// Note that you need to call Tag.Unwrap() before calling this method if this Tag
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Tag) Update() *TagUpdateOne {
	return NewTagClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Tag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Tag) Unwrap() *Tag {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tag is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Tag) String() string {
	var builder strings.Builder
	builder.WriteString("Tag(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.Id))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("repo=")
	builder.WriteString(_m.Repo)
	builder.WriteString(", ")
	builder.WriteString("digest=")
	builder.WriteString(_m.Digest)
	builder.WriteString(", ")
	builder.WriteString("date_moved=")
	builder.WriteString(_m.DateMoved.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DatePulled; v != nil {
		builder.WriteString("date_pulled=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("date_updated=")
	builder.WriteString(_m.DateUpdated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TagList is a parsable slice of Tag.
type TagList []*Tag
