// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/cr/internal/ent/tagrule"
	"github.com/lesomnus/cr/internal/ent/tenant"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// TagRuleCreate is the builder for creating a TagRule entity.
type TagRuleCreate struct {
	config
	mutation *TagRuleMutation
	hooks    []Hook
}

// SetAlias sets the "alias" field.
func (_c *TagRuleCreate) SetAlias(v string) *TagRuleCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetDesc sets the "desc" field.
func (_c *TagRuleCreate) SetDesc(v string) *TagRuleCreate {
	_c.mutation.SetDesc(v)
	return _c
}

// SetRepo sets the "repo" field.
func (_c *TagRuleCreate) SetRepo(v string) *TagRuleCreate {
	_c.mutation.SetRepo(v)
	return _c
}

// SetTag sets the "tag" field.
func (_c *TagRuleCreate) SetTag(v string) *TagRuleCreate {
	_c.mutation.SetTag(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *TagRuleCreate) SetKind(v string) *TagRuleCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetPattern sets the "pattern" field.
func (_c *TagRuleCreate) SetPattern(v string) *TagRuleCreate {
	_c.mutation.SetPattern(v)
	return _c
}

// SetGroups sets the "groups" field.
func (_c *TagRuleCreate) SetGroups(v []string) *TagRuleCreate {
	_c.mutation.SetGroups(v)
	return _c
}

// SetKeep sets the "keep" field.
func (_c *TagRuleCreate) SetKeep(v int32) *TagRuleCreate {
	_c.mutation.SetKeep(v)
	return _c
}

// SetDateErased sets the "date_erased" field.
func (_c *TagRuleCreate) SetDateErased(v time.Time) *TagRuleCreate {
	_c.mutation.SetDateErased(v)
	return _c
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_c *TagRuleCreate) SetNillableDateErased(v *time.Time) *TagRuleCreate {
	if v != nil {
		_c.SetDateErased(*v)
	}
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *TagRuleCreate) SetDateUpdated(v time.Time) *TagRuleCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *TagRuleCreate) SetDateCreated(v time.Time) *TagRuleCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *TagRuleCreate) SetNillableDateCreated(v *time.Time) *TagRuleCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetTenantId sets the "tenant_id" field.
func (_c *TagRuleCreate) SetTenantId(v uuid.UUID) *TagRuleCreate {
	_c.mutation.SetTenantId(v)
	return _c
}

// SetId sets the "id" field.
func (_c *TagRuleCreate) SetId(v uuid.UUID) *TagRuleCreate {
	_c.mutation.SetId(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *TagRuleCreate) SetTenant(v *Tenant) *TagRuleCreate {
	return _c.SetTenantId(v.Id)
}

// Mutation returns the TagRuleMutation object of the builder.
func (_c *TagRuleCreate) Mutation() *TagRuleMutation {
	return _c.mutation
}

// Save creates the TagRule in the database.
func (_c *TagRuleCreate) Save(ctx context.Context) (*TagRule, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TagRuleCreate) SaveX(ctx context.Context) *TagRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TagRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TagRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TagRuleCreate) check() error {
	if _, ok := _c.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`ent: missing required field "TagRule.alias"`)}
	}
	if _, ok := _c.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "TagRule.desc"`)}
	}
	if _, ok := _c.mutation.Repo(); !ok {
		return &ValidationError{Name: "repo", err: errors.New(`ent: missing required field "TagRule.repo"`)}
	}
	if _, ok := _c.mutation.Tag(); !ok {
		return &ValidationError{Name: "tag", err: errors.New(`ent: missing required field "TagRule.tag"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "TagRule.kind"`)}
	}
	if _, ok := _c.mutation.Pattern(); !ok {
		return &ValidationError{Name: "pattern", err: errors.New(`ent: missing required field "TagRule.pattern"`)}
	}
	if _, ok := _c.mutation.Keep(); !ok {
		return &ValidationError{Name: "keep", err: errors.New(`ent: missing required field "TagRule.keep"`)}
	}
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "TagRule.date_updated"`)}
	}
	if _, ok := _c.mutation.TenantId(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TagRule.tenant_id"`)}
	}
	if len(_c.mutation.TenantIds()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "TagRule.tenant"`)}
	}
	return nil
}

func (_c *TagRuleCreate) sqlSave(ctx context.Context) (*TagRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		if id, ok := _spec.Id.Value.(*uuid.UUID); ok {
			_node.Id = *id
		} else {
			var v sql.Null[uuid.UUID]
			if err := v.Scan(_spec.Id.Value); err != nil {
				return nil, err
			}
			_node.Id = v.V
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *TagRuleCreate) createSpec() (*TagRule, *sqlgraph.CreateSpec) {
	var (
		_node = &TagRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tagrule.Table, sqlgraph.NewFieldSpec(tagrule.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		_spec.Id.Value = &id
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(tagrule.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := _c.mutation.Desc(); ok {
		_spec.SetField(tagrule.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if value, ok := _c.mutation.Repo(); ok {
		_spec.SetField(tagrule.FieldRepo, field.TypeString, value)
		_node.Repo = value
	}
	if value, ok := _c.mutation.Tag(); ok {
		_spec.SetField(tagrule.FieldTag, field.TypeString, value)
		_node.Tag = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(tagrule.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Pattern(); ok {
		_spec.SetField(tagrule.FieldPattern, field.TypeString, value)
		_node.Pattern = value
	}
	if value, ok := _c.mutation.Groups(); ok {
		_spec.SetField(tagrule.FieldGroups, field.TypeJson, value)
		_node.Groups = value
	}
	if value, ok := _c.mutation.Keep(); ok {
		_spec.SetField(tagrule.FieldKeep, field.TypeInt32, value)
		_node.Keep = value
	}
	if value, ok := _c.mutation.DateErased(); ok {
		_spec.SetField(tagrule.FieldDateErased, field.TypeTime, value)
		_node.DateErased = &value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(tagrule.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(tagrule.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if nodes := _c.mutation.TenantIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tagrule.TenantTable,
			Columns: []string{tagrule.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tenant.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TagRuleCreateBulk is the builder for creating many TagRule entities in bulk.
type TagRuleCreateBulk struct {
	config
	err      error
	builders []*TagRuleCreate
}

// Save creates the TagRule entities in the database.
func (_c *TagRuleCreateBulk) Save(ctx context.Context) ([]*TagRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TagRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TagRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TagRuleCreateBulk) SaveX(ctx context.Context) []*TagRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TagRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TagRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
