// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Audit is the predicate function for audit builders.
type Audit func(*sql.Selector)

// Binding is the predicate function for binding builders.
type Binding func(*sql.Selector)

// Holder is the predicate function for holder builders.
type Holder func(*sql.Selector)

// Manifest is the predicate function for manifest builders.
type Manifest func(*sql.Selector)

// ManifestBlob is the predicate function for manifestblob builders.
type ManifestBlob func(*sql.Selector)

// Outbox is the predicate function for outbox builders.
type Outbox func(*sql.Selector)

// Repository is the predicate function for repository builders.
type Repository func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// TagRule is the predicate function for tagrule builders.
type TagRule func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)
