// Code generated by ent, DO NOT EDIT.

package tagrule

import (
	"context"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/cr/internal/ent/predicate"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Mutation represents an operation that mutates the TagRule nodes in the graph.
type Mutation struct {
	op            ent.Op
	typ           string
	alias         *string
	desc          *string
	repo          *string
	tag           *string
	kind          *string
	pattern       *string
	groups        *[]string
	appendgroups  []string
	keep          *int32
	addkeep       *int32
	date_erased   *time.Time
	date_updated  *time.Time
	date_created  *time.Time
	clearedFields map[string]struct{}
	tenant        *uuid.UUID
	clearedtenant bool
	predicates    []predicate.TagRule
}

// NewMutation creates a new Mutation for the TagRule entity.
func NewMutation(op ent.Op) *Mutation {
	return &Mutation{
		op:            op,
		typ:           "TagRule",
		clearedFields: make(map[string]struct{}),
	}
}

// Predicates returns the list of predicates set on the mutation.
func (m *Mutation) Predicates() []predicate.TagRule {
	return m.predicates
}

// SetAlias sets the "alias" field.
func (m *Mutation) SetAlias(s string) {
	m.alias = &s
}

// Alias returns the value of the "alias" field in the mutation.
func (m *Mutation) Alias() (r string, exists bool) {
	v := m.alias
	if v == nil {
		return
	}
	return *v, true
}

// ResetAlias resets all changes to the "alias" field.
func (m *Mutation) ResetAlias() {
	m.alias = nil
}

// SetDesc sets the "desc" field.
func (m *Mutation) SetDesc(s string) {
	m.desc = &s
}

// Desc returns the value of the "desc" field in the mutation.
func (m *Mutation) Desc() (r string, exists bool) {
	v := m.desc
	if v == nil {
		return
	}
	return *v, true
}

// ResetDesc resets all changes to the "desc" field.
func (m *Mutation) ResetDesc() {
	m.desc = nil
}

// SetRepo sets the "repo" field.
func (m *Mutation) SetRepo(s string) {
	m.repo = &s
}

// Repo returns the value of the "repo" field in the mutation.
func (m *Mutation) Repo() (r string, exists bool) {
	v := m.repo
	if v == nil {
		return
	}
	return *v, true
}

// ResetRepo resets all changes to the "repo" field.
func (m *Mutation) ResetRepo() {
	m.repo = nil
}

// SetTag sets the "tag" field.
func (m *Mutation) SetTag(s string) {
	m.tag = &s
}

// Tag returns the value of the "tag" field in the mutation.
func (m *Mutation) Tag() (r string, exists bool) {
	v := m.tag
	if v == nil {
		return
	}
	return *v, true
}

// ResetTag resets all changes to the "tag" field.
func (m *Mutation) ResetTag() {
	m.tag = nil
}

// SetKind sets the "kind" field.
func (m *Mutation) SetKind(s string) {
	m.kind = &s
}

// Kind returns the value of the "kind" field in the mutation.
func (m *Mutation) Kind() (r string, exists bool) {
	v := m.kind
	if v == nil {
		return
	}
	return *v, true
}

// ResetKind resets all changes to the "kind" field.
func (m *Mutation) ResetKind() {
	m.kind = nil
}

// SetPattern sets the "pattern" field.
func (m *Mutation) SetPattern(s string) {
	m.pattern = &s
}

// Pattern returns the value of the "pattern" field in the mutation.
func (m *Mutation) Pattern() (r string, exists bool) {
	v := m.pattern
	if v == nil {
		return
	}
	return *v, true
}

// ResetPattern resets all changes to the "pattern" field.
func (m *Mutation) ResetPattern() {
	m.pattern = nil
}

// SetGroups sets the "groups" field.
func (m *Mutation) SetGroups(s []string) {
	m.groups = &s
	m.appendgroups = nil
}

// Groups returns the value of the "groups" field in the mutation.
func (m *Mutation) Groups() (r []string, exists bool) {
	v := m.groups
	if v == nil {
		return
	}
	return *v, true
}

// AppendGroups adds s to the "groups" field.
func (m *Mutation) AppendGroups(s []string) {
	m.appendgroups = append(m.appendgroups, s...)
}

// AppendedGroups returns the list of values that were appended to the "groups" field in this mutation.
func (m *Mutation) AppendedGroups() ([]string, bool) {
	if len(m.appendgroups) == 0 {
		return nil, false
	}
	return m.appendgroups, true
}

// ClearGroups clears the value of the "groups" field.
func (m *Mutation) ClearGroups() {
	m.groups = nil
	m.appendgroups = nil
	m.clearedFields[FieldGroups] = struct{}{}
}

// GroupsCleared returns if the "groups" field was cleared in this mutation.
func (m *Mutation) GroupsCleared() bool {
	_, ok := m.clearedFields[FieldGroups]
	return ok
}

// ResetGroups resets all changes to the "groups" field.
func (m *Mutation) ResetGroups() {
	m.groups = nil
	m.appendgroups = nil
	delete(m.clearedFields, FieldGroups)
}

// SetKeep sets the "keep" field.
func (m *Mutation) SetKeep(i int32) {
	m.keep = &i
	m.addkeep = nil
}

// Keep returns the value of the "keep" field in the mutation.
func (m *Mutation) Keep() (r int32, exists bool) {
	v := m.keep
	if v == nil {
		return
	}
	return *v, true
}

// AddKeep adds i to the "keep" field.
func (m *Mutation) AddKeep(i int32) {
	if m.addkeep != nil {
		*m.addkeep += i
	} else {
		m.addkeep = &i
	}
}

// AddedKeep returns the value that was added to the "keep" field in this mutation.
func (m *Mutation) AddedKeep() (r int32, exists bool) {
	v := m.addkeep
	if v == nil {
		return
	}
	return *v, true
}

// ResetKeep resets all changes to the "keep" field.
func (m *Mutation) ResetKeep() {
	m.keep = nil
	m.addkeep = nil
}

// SetDateErased sets the "date_erased" field.
func (m *Mutation) SetDateErased(t time.Time) {
	m.date_erased = &t
}

// DateErased returns the value of the "date_erased" field in the mutation.
func (m *Mutation) DateErased() (r time.Time, exists bool) {
	v := m.date_erased
	if v == nil {
		return
	}
	return *v, true
}

// ClearDateErased clears the value of the "date_erased" field.
func (m *Mutation) ClearDateErased() {
	m.date_erased = nil
	m.clearedFields[FieldDateErased] = struct{}{}
}

// DateErasedCleared returns if the "date_erased" field was cleared in this mutation.
func (m *Mutation) DateErasedCleared() bool {
	_, ok := m.clearedFields[FieldDateErased]
	return ok
}

// ResetDateErased resets all changes to the "date_erased" field.
func (m *Mutation) ResetDateErased() {
	m.date_erased = nil
	delete(m.clearedFields, FieldDateErased)
}

// SetDateUpdated sets the "date_updated" field.
func (m *Mutation) SetDateUpdated(t time.Time) {
	m.date_updated = &t
}

// DateUpdated returns the value of the "date_updated" field in the mutation.
func (m *Mutation) DateUpdated() (r time.Time, exists bool) {
	v := m.date_updated
	if v == nil {
		return
	}
	return *v, true
}

// ResetDateUpdated resets all changes to the "date_updated" field.
func (m *Mutation) ResetDateUpdated() {
	m.date_updated = nil
}

// SetDateCreated sets the "date_created" field.
func (m *Mutation) SetDateCreated(t time.Time) {
	m.date_created = &t
}

// DateCreated returns the value of the "date_created" field in the mutation.
func (m *Mutation) DateCreated() (r time.Time, exists bool) {
	v := m.date_created
	if v == nil {
		return
	}
	return *v, true
}

// ClearDateCreated clears the value of the "date_created" field.
func (m *Mutation) ClearDateCreated() {
	m.date_created = nil
	m.clearedFields[FieldDateCreated] = struct{}{}
}

// DateCreatedCleared returns if the "date_created" field was cleared in this mutation.
func (m *Mutation) DateCreatedCleared() bool {
	_, ok := m.clearedFields[FieldDateCreated]
	return ok
}

// ResetDateCreated resets all changes to the "date_created" field.
func (m *Mutation) ResetDateCreated() {
	m.date_created = nil
	delete(m.clearedFields, FieldDateCreated)
}

// SetTenantId sets the "tenant_id" field.
func (m *Mutation) SetTenantId(u uuid.UUID) {
	m.tenant = &u
}

// TenantId returns the value of the "tenant_id" field in the mutation.
func (m *Mutation) TenantId() (r uuid.UUID, exists bool) {
	v := m.tenant
	if v == nil {
		return
	}
	return *v, true
}

// ResetTenantId resets all changes to the "tenant_id" field.
func (m *Mutation) ResetTenantId() {
	m.tenant = nil
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (m *Mutation) ClearTenant() {
	m.clearedtenant = true
	m.clearedFields[FieldTenantId] = struct{}{}
}

// TenantCleared reports if the "tenant" edge to the Tenant entity was cleared.
func (m *Mutation) TenantCleared() bool {
	return m.clearedtenant
}

// TenantIds returns the "tenant" edge Ids in the mutation.
// Note that Ids always returns len(Ids) <= 1 for unique edges, and you should use
// TenantId instead. It exists only for internal usage by the builders.
func (m *Mutation) TenantIds() (ids []uuid.UUID) {
	if id := m.tenant; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetTenant resets all changes to the "tenant" edge.
func (m *Mutation) ResetTenant() {
	m.tenant = nil
	m.clearedtenant = false
}

// Where appends a list predicates to the Mutation builder.
func (m *Mutation) Where(ps ...predicate.TagRule) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the Mutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *Mutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TagRule, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *Mutation) Op() ent.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *Mutation) SetOp(op ent.Op) {
	m.op = op
}

// Type returns the node type of this mutation (TagRule).
func (m *Mutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *Mutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.alias != nil {
		fields = append(fields, FieldAlias)
	}
	if m.desc != nil {
		fields = append(fields, FieldDesc)
	}
	if m.repo != nil {
		fields = append(fields, FieldRepo)
	}
	if m.tag != nil {
		fields = append(fields, FieldTag)
	}
	if m.kind != nil {
		fields = append(fields, FieldKind)
	}
	if m.pattern != nil {
		fields = append(fields, FieldPattern)
	}
	if m.groups != nil {
		fields = append(fields, FieldGroups)
	}
	if m.keep != nil {
		fields = append(fields, FieldKeep)
	}
	if m.date_erased != nil {
		fields = append(fields, FieldDateErased)
	}
	if m.date_updated != nil {
		fields = append(fields, FieldDateUpdated)
	}
	if m.date_created != nil {
		fields = append(fields, FieldDateCreated)
	}
	if m.tenant != nil {
		fields = append(fields, FieldTenantId)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *Mutation) Field(name string) (ent.Value, bool) {
	switch name {
	case FieldAlias:
		return m.Alias()
	case FieldDesc:
		return m.Desc()
	case FieldRepo:
		return m.Repo()
	case FieldTag:
		return m.Tag()
	case FieldKind:
		return m.Kind()
	case FieldPattern:
		return m.Pattern()
	case FieldGroups:
		return m.Groups()
	case FieldKeep:
		return m.Keep()
	case FieldDateErased:
		return m.DateErased()
	case FieldDateUpdated:
		return m.DateUpdated()
	case FieldDateCreated:
		return m.DateCreated()
	case FieldTenantId:
		return m.TenantId()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *Mutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown TagRule field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) SetField(name string, value ent.Value) error {
	switch name {
	case FieldAlias:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAlias(v)
		return nil
	case FieldDesc:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDesc(v)
		return nil
	case FieldRepo:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRepo(v)
		return nil
	case FieldTag:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTag(v)
		return nil
	case FieldKind:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKind(v)
		return nil
	case FieldPattern:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPattern(v)
		return nil
	case FieldGroups:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGroups(v)
		return nil
	case FieldKeep:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKeep(v)
		return nil
	case FieldDateErased:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateErased(v)
		return nil
	case FieldDateUpdated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateUpdated(v)
		return nil
	case FieldDateCreated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateCreated(v)
		return nil
	case FieldTenantId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantId(v)
		return nil
	}
	return fmt.Errorf("unknown TagRule field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *Mutation) AddedFields() []string {
	var fields []string
	if m.addkeep != nil {
		fields = append(fields, FieldKeep)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *Mutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case FieldKeep:
		return m.AddedKeep()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) AddField(name string, value ent.Value) error {
	switch name {
	case FieldKeep:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddKeep(v)
		return nil
	}
	return fmt.Errorf("unknown TagRule numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *Mutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(FieldGroups) {
		fields = append(fields, FieldGroups)
	}
	if m.FieldCleared(FieldDateErased) {
		fields = append(fields, FieldDateErased)
	}
	if m.FieldCleared(FieldDateCreated) {
		fields = append(fields, FieldDateCreated)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *Mutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *Mutation) ClearField(name string) error {
	switch name {
	case FieldGroups:
		m.ClearGroups()
		return nil
	case FieldDateErased:
		m.ClearDateErased()
		return nil
	case FieldDateCreated:
		m.ClearDateCreated()
		return nil
	}
	return fmt.Errorf("unknown TagRule nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *Mutation) ResetField(name string) error {
	switch name {
	case FieldAlias:
		m.ResetAlias()
		return nil
	case FieldDesc:
		m.ResetDesc()
		return nil
	case FieldRepo:
		m.ResetRepo()
		return nil
	case FieldTag:
		m.ResetTag()
		return nil
	case FieldKind:
		m.ResetKind()
		return nil
	case FieldPattern:
		m.ResetPattern()
		return nil
	case FieldGroups:
		m.ResetGroups()
		return nil
	case FieldKeep:
		m.ResetKeep()
		return nil
	case FieldDateErased:
		m.ResetDateErased()
		return nil
	case FieldDateUpdated:
		m.ResetDateUpdated()
		return nil
	case FieldDateCreated:
		m.ResetDateCreated()
		return nil
	case FieldTenantId:
		m.ResetTenantId()
		return nil
	}
	return fmt.Errorf("unknown TagRule field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *Mutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.tenant != nil {
		edges = append(edges, EdgeTenant)
	}
	return edges
}

// AddedIds returns all Ids (to other nodes) that were added for the given edge
// name in this mutation.
func (m *Mutation) AddedIds(name string) []ent.Value {
	switch name {
	case EdgeTenant:
		if id := m.tenant; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *Mutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIds returns all Ids (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *Mutation) RemovedIds(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *Mutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedtenant {
		edges = append(edges, EdgeTenant)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *Mutation) EdgeCleared(name string) bool {
	switch name {
	case EdgeTenant:
		return m.clearedtenant
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *Mutation) ClearEdge(name string) error {
	switch name {
	case EdgeTenant:
		m.ClearTenant()
		return nil
	}
	return fmt.Errorf("unknown TagRule unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *Mutation) ResetEdge(name string) error {
	switch name {
	case EdgeTenant:
		m.ResetTenant()
		return nil
	}
	return fmt.Errorf("unknown TagRule edge %s", name)
}
