// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/binding.proto

package bare

import (
	context "context"
	errors "errors"
	api "github.com/lesomnus/cr/api"
	ent "github.com/lesomnus/cr/internal/ent"
	binding "github.com/lesomnus/cr/internal/ent/binding"
	predicate "github.com/lesomnus/cr/internal/ent/predicate"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	ent1 "github.com/protobuf-orm/ent"
	sqlgraph "github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	entuuid "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entuuid"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	uuid "uuid"
)

type BindingServiceServer struct {
	Store

	api.UnimplementedBindingServiceServer
}

// NewBindingServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewBindingServiceServer(db *ent.Client, opts ...Option) api.BindingServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return BindingServiceServer{Store: s.Store}
}

// BindingNarrow answers with `p` and everything else that narrows a
// read of a Binding: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func BindingNarrow(ctx context.Context, scope Scope, p predicate.Binding) (predicate.Binding, error) {
	ps := make([]predicate.Binding, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, binding.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.BindingScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return binding.And(ps...), nil
	}
}

// narrow is [BindingNarrow] with this server's own scope.
func (s BindingServiceServer) narrow(ctx context.Context, p predicate.Binding) (predicate.Binding, error) {
	return BindingNarrow(ctx, s.Scope, p)
}

func (s BindingServiceServer) Add(ctx context.Context, req *api.BindingAddRequest) (*api.Binding, error) {
	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *api.Binding), 0, 1)
	q := st.Db.Binding.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "app.Binding", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetId(v)
	}
	if k, err := TenantGetKey(ctx, st.Db, req.GetTenant()); err != nil {
		return nil, err
	} else {
		q.SetTenantId(k)
		ds = append(ds, func(v *api.Binding) {
			v.SetTenant(api.Tenant_builder{Id: k[:]}.Build())
		})
	}
	q.SetAlias(req.GetAlias())
	q.SetDesc(req.GetDesc())
	q.SetSubject(req.GetSubject())
	q.SetGroup(req.GetGroup())
	q.SetRepo(req.GetRepo())
	if u := req.GetActions(); len(u) > 0 {
		q.SetActions(u)
	}
	if u := req.GetWhen(); len(u) > 0 {
		q.SetWhen(u)
	}
	q.SetDateUpdated(st.now())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Binding already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Binding: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  api.BindingService_Add_FullMethodName,
		Key: u.Id,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s BindingServiceServer) Get(ctx context.Context, req *api.BindingGetRequest) (*api.Binding, error) {
	p, err := BindingPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Binding.Query().Where(p)
	BindingSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Binding not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectBindingKey(q *ent.BindingQuery) {
	q.Select(binding.FieldId)
}

func BindingSelectedFields(m *api.BindingSelect) []string {
	if m.GetAll() {
		return binding.Columns
	}

	vs := make([]string, 0, len(binding.Columns))
	{
		vs = append(vs, binding.FieldId)
	}
	if m.GetAlias() {
		vs = append(vs, binding.FieldAlias)
	}
	if m.GetDesc() {
		vs = append(vs, binding.FieldDesc)
	}
	if m.GetSubject() {
		vs = append(vs, binding.FieldSubject)
	}
	if m.GetGroup() {
		vs = append(vs, binding.FieldGroup)
	}
	if m.GetRepo() {
		vs = append(vs, binding.FieldRepo)
	}
	if m.GetActions() {
		vs = append(vs, binding.FieldActions)
	}
	if m.GetWhen() {
		vs = append(vs, binding.FieldWhen)
	}
	if m.GetDateErased() {
		vs = append(vs, binding.FieldDateErased)
	}
	if m.GetDateUpdated() {
		vs = append(vs, binding.FieldDateUpdated)
	}
	if m.GetDateCreated() {
		vs = append(vs, binding.FieldDateCreated)
	}

	return vs
}

func BindingSelect(q *ent.BindingQuery, m *api.BindingSelect) {
	if !m.GetAll() {
		fields := BindingSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasTenant() {
		q.WithTenant(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetTenant())
		})
	}
}

func BindingSelectInit(q *ent.BindingQuery, m *api.BindingSelect) {
	if m != nil {
		BindingSelect(q, m)
	} else {
		q.WithTenant(selectTenantKey)
	}
}

func (s BindingServiceServer) Patch(ctx context.Context, req *api.BindingPatchRequest) (*api.Binding, error) {
	doc, err := ormpatch.FromPatchRequest(bindingOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, api.BindingService_Patch_FullMethodName)
}

func BindingGetKey(ctx context.Context, db *ent.Client, ref *api.BindingRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := entuuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := BindingPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Binding.Query().Where(p).OnlyId(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Binding not found")
		}
		return z, err
	}

	return v, nil
}

var bindingOrmEntity = ormpatch.MustEntityOf(api.File_app_binding_proto, "Binding")

var bindingPatchColumns = entpatch.Columns{
	1: binding.FieldId, 2: binding.TenantColumn, 4: binding.FieldAlias, 6: binding.FieldDesc, 8: binding.FieldSubject, 9: binding.FieldGroup, 10: binding.FieldRepo, 11: binding.FieldActions, 12: binding.FieldWhen, 14: binding.FieldDateErased, 13: binding.FieldDateUpdated, 15: binding.FieldDateCreated}

func (s BindingServiceServer) Apply(ctx context.Context, req *api.BindingApplyRequest) (*api.Binding, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), api.BindingService_Apply_FullMethodName)
}

func (s BindingServiceServer) apply(ctx context.Context, ref *api.BindingRef, doc *patchpb.Patch, by string) (*api.Binding, error) {
	plan := &ormpatch.Plan{Entity: bindingOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(bindingOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, bindingPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := BindingGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &api.BindingRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, binding.IdEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Binding.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Binding(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Binding.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Binding not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Binding.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Binding(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(13) {
			q.SetDateUpdated(st.now())
		}
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Binding already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Binding: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Binding.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Binding not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s BindingServiceServer) Erase(ctx context.Context, req *api.BindingRef) (*api.BindingEraseResponse, error) {
	p, err := BindingPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Binding.Query().Where(p).OnlyId(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &api.BindingEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = binding.And(p, binding.IdEQ(v))
	}

	u := st.Db.Binding.Update().Where(p)
	u.SetDateErased(st.now())
	u.SetDateUpdated(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  api.BindingService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &api.BindingEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

// BindingPick answers with the predicate this reference selects on,
// among the rows that are still here.
//
// Erasure is part of the reference and not only part of a read's scope,
// because a reference to a Binding is composed into the reference of
// whatever names one: an index over an edge asks this for a predicate and
// puts it inside `HasBindingWith`, where no narrowing of a Binding
// is ever applied. A child of an erased row would otherwise be readable by
// naming its parent.
func BindingPick(req *api.BindingRef) (predicate.Binding, error) {
	p, err := pickBinding(req)
	if err != nil {
		return nil, err
	}

	return binding.And(binding.DateErasedIsNil(), p), nil
}

func pickBinding(req *api.BindingRef) (predicate.Binding, error) {
	switch req.WhichKey() {
	case api.BindingRef_Id_case:
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return binding.IdEQ(v), nil
		}
	case api.BindingRef_Slug_case:
		k := req.GetSlug()
		ps := make([]predicate.Binding, 0, 2)
		ps = append(ps, binding.AliasEQ(k.GetAlias()))
		if p, err := TenantPick(k.GetTenant()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "slug.tenant: %s", err)
		} else {
			ps = append(ps, binding.HasTenantWith(p))
		}
		return binding.And(ps...), nil
	case api.BindingRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Binding")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
