// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/manifest.proto

package bare

import (
	context "context"
	api "github.com/lesomnus/cr/api"
	ent "github.com/lesomnus/cr/internal/ent"
	manifest "github.com/lesomnus/cr/internal/ent/manifest"
	predicate "github.com/lesomnus/cr/internal/ent/predicate"
	entuuid "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entuuid"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

type ManifestServiceServer struct {
	Store

	api.UnimplementedManifestServiceServer
}

// NewManifestServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewManifestServiceServer(db *ent.Client, opts ...Option) api.ManifestServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return ManifestServiceServer{Store: s.Store}
}

// ManifestNarrow answers with `p` and everything else that narrows a
// read of a Manifest, which is whatever `scope` says.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func ManifestNarrow(ctx context.Context, scope Scope, p predicate.Manifest) (predicate.Manifest, error) {
	ps := make([]predicate.Manifest, 0, 2)
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.ManifestScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return manifest.And(ps...), nil
	}
}

// narrow is [ManifestNarrow] with this server's own scope.
func (s ManifestServiceServer) narrow(ctx context.Context, p predicate.Manifest) (predicate.Manifest, error) {
	return ManifestNarrow(ctx, s.Scope, p)
}

func (s ManifestServiceServer) Get(ctx context.Context, req *api.ManifestGetRequest) (*api.Manifest, error) {
	p, err := ManifestPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Manifest.Query().Where(p)
	ManifestSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Manifest not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectManifestKey(q *ent.ManifestQuery) {
	q.Select(manifest.FieldId)
}

func ManifestSelectedFields(m *api.ManifestSelect) []string {
	if m.GetAll() {
		return manifest.Columns
	}

	vs := make([]string, 0, len(manifest.Columns))
	{
		vs = append(vs, manifest.FieldId)
	}
	if m.GetRepo() {
		vs = append(vs, manifest.FieldRepo)
	}
	if m.GetDigest() {
		vs = append(vs, manifest.FieldDigest)
	}
	if m.GetMediaType() {
		vs = append(vs, manifest.FieldMediaType)
	}
	if m.GetArtifactType() {
		vs = append(vs, manifest.FieldArtifactType)
	}
	if m.GetSubject() {
		vs = append(vs, manifest.FieldSubject)
	}
	if m.GetSize() {
		vs = append(vs, manifest.FieldSize)
	}
	if m.GetAnnotations() {
		vs = append(vs, manifest.FieldAnnotations)
	}
	if m.GetDatePulled() {
		vs = append(vs, manifest.FieldDatePulled)
	}
	if m.GetDateUpdated() {
		vs = append(vs, manifest.FieldDateUpdated)
	}
	if m.GetDateCreated() {
		vs = append(vs, manifest.FieldDateCreated)
	}

	return vs
}

func ManifestSelect(q *ent.ManifestQuery, m *api.ManifestSelect) {
	if !m.GetAll() {
		fields := ManifestSelectedFields(m)
		q.Select(fields...)
	}
}

func ManifestSelectInit(q *ent.ManifestQuery, m *api.ManifestSelect) {
	if m != nil {
		ManifestSelect(q, m)
	} else {
	}
}

func ManifestPick(req *api.ManifestRef) (predicate.Manifest, error) {
	switch req.WhichKey() {
	case api.ManifestRef_Id_case:
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return manifest.IdEQ(v), nil
		}
	case api.ManifestRef_ByDigest_case:
		k := req.GetByDigest()
		ps := make([]predicate.Manifest, 0, 2)
		ps = append(ps, manifest.RepoEQ(k.GetRepo()))
		ps = append(ps, manifest.DigestEQ(k.GetDigest()))
		return manifest.And(ps...), nil
	case api.ManifestRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Manifest")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
