// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/tag_rule.proto

package bare

import (
	context "context"
	errors "errors"
	api "github.com/lesomnus/cr/api"
	ent "github.com/lesomnus/cr/internal/ent"
	predicate "github.com/lesomnus/cr/internal/ent/predicate"
	tagrule "github.com/lesomnus/cr/internal/ent/tagrule"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	ent1 "github.com/protobuf-orm/ent"
	sqlgraph "github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	entuuid "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entuuid"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	uuid "uuid"
)

type TagRuleServiceServer struct {
	Store

	api.UnimplementedTagRuleServiceServer
}

// NewTagRuleServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewTagRuleServiceServer(db *ent.Client, opts ...Option) api.TagRuleServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return TagRuleServiceServer{Store: s.Store}
}

// TagRuleNarrow answers with `p` and everything else that narrows a
// read of a TagRule: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func TagRuleNarrow(ctx context.Context, scope Scope, p predicate.TagRule) (predicate.TagRule, error) {
	ps := make([]predicate.TagRule, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, tagrule.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.TagRuleScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return tagrule.And(ps...), nil
	}
}

// narrow is [TagRuleNarrow] with this server's own scope.
func (s TagRuleServiceServer) narrow(ctx context.Context, p predicate.TagRule) (predicate.TagRule, error) {
	return TagRuleNarrow(ctx, s.Scope, p)
}

func (s TagRuleServiceServer) Add(ctx context.Context, req *api.TagRuleAddRequest) (*api.TagRule, error) {
	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *api.TagRule), 0, 1)
	q := st.Db.TagRule.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "app.TagRule", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetId(v)
	}
	if k, err := TenantGetKey(ctx, st.Db, req.GetTenant()); err != nil {
		return nil, err
	} else {
		q.SetTenantId(k)
		ds = append(ds, func(v *api.TagRule) {
			v.SetTenant(api.Tenant_builder{Id: k[:]}.Build())
		})
	}
	q.SetAlias(req.GetAlias())
	q.SetDesc(req.GetDesc())
	q.SetRepo(req.GetRepo())
	q.SetTag(req.GetTag())
	q.SetKind(req.GetKind())
	q.SetPattern(req.GetPattern())
	if u := req.GetGroups(); len(u) > 0 {
		q.SetGroups(u)
	}
	q.SetKeep(req.GetKeep())
	q.SetDateUpdated(st.now())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "TagRule already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "TagRule: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  api.TagRuleService_Add_FullMethodName,
		Key: u.Id,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s TagRuleServiceServer) Get(ctx context.Context, req *api.TagRuleGetRequest) (*api.TagRule, error) {
	p, err := TagRulePick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.TagRule.Query().Where(p)
	TagRuleSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "TagRule not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectTagRuleKey(q *ent.TagRuleQuery) {
	q.Select(tagrule.FieldId)
}

func TagRuleSelectedFields(m *api.TagRuleSelect) []string {
	if m.GetAll() {
		return tagrule.Columns
	}

	vs := make([]string, 0, len(tagrule.Columns))
	{
		vs = append(vs, tagrule.FieldId)
	}
	if m.GetAlias() {
		vs = append(vs, tagrule.FieldAlias)
	}
	if m.GetDesc() {
		vs = append(vs, tagrule.FieldDesc)
	}
	if m.GetRepo() {
		vs = append(vs, tagrule.FieldRepo)
	}
	if m.GetTag() {
		vs = append(vs, tagrule.FieldTag)
	}
	if m.GetKind() {
		vs = append(vs, tagrule.FieldKind)
	}
	if m.GetPattern() {
		vs = append(vs, tagrule.FieldPattern)
	}
	if m.GetGroups() {
		vs = append(vs, tagrule.FieldGroups)
	}
	if m.GetKeep() {
		vs = append(vs, tagrule.FieldKeep)
	}
	if m.GetDateErased() {
		vs = append(vs, tagrule.FieldDateErased)
	}
	if m.GetDateUpdated() {
		vs = append(vs, tagrule.FieldDateUpdated)
	}
	if m.GetDateCreated() {
		vs = append(vs, tagrule.FieldDateCreated)
	}

	return vs
}

func TagRuleSelect(q *ent.TagRuleQuery, m *api.TagRuleSelect) {
	if !m.GetAll() {
		fields := TagRuleSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasTenant() {
		q.WithTenant(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetTenant())
		})
	}
}

func TagRuleSelectInit(q *ent.TagRuleQuery, m *api.TagRuleSelect) {
	if m != nil {
		TagRuleSelect(q, m)
	} else {
		q.WithTenant(selectTenantKey)
	}
}

func (s TagRuleServiceServer) Patch(ctx context.Context, req *api.TagRulePatchRequest) (*api.TagRule, error) {
	doc, err := ormpatch.FromPatchRequest(tagRuleOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, api.TagRuleService_Patch_FullMethodName)
}

func TagRuleGetKey(ctx context.Context, db *ent.Client, ref *api.TagRuleRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := entuuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := TagRulePick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.TagRule.Query().Where(p).OnlyId(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "TagRule not found")
		}
		return z, err
	}

	return v, nil
}

var tagRuleOrmEntity = ormpatch.MustEntityOf(api.File_app_tag_rule_proto, "TagRule")

var tagRulePatchColumns = entpatch.Columns{
	1: tagrule.FieldId, 2: tagrule.TenantColumn, 4: tagrule.FieldAlias, 6: tagrule.FieldDesc, 8: tagrule.FieldRepo, 9: tagrule.FieldTag, 10: tagrule.FieldKind, 11: tagrule.FieldPattern, 12: tagrule.FieldGroups, 16: tagrule.FieldKeep, 14: tagrule.FieldDateErased, 13: tagrule.FieldDateUpdated, 15: tagrule.FieldDateCreated}

func (s TagRuleServiceServer) Apply(ctx context.Context, req *api.TagRuleApplyRequest) (*api.TagRule, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), api.TagRuleService_Apply_FullMethodName)
}

func (s TagRuleServiceServer) apply(ctx context.Context, ref *api.TagRuleRef, doc *patchpb.Patch, by string) (*api.TagRule, error) {
	plan := &ormpatch.Plan{Entity: tagRuleOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(tagRuleOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, tagRulePatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := TagRuleGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &api.TagRuleRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, tagrule.IdEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.TagRule.Query().Where(p)
		if pred != nil {
			q.Where(predicate.TagRule(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.TagRule.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "TagRule not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.TagRule.Update().Where(p)
		if pred != nil {
			q.Where(predicate.TagRule(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(13) {
			q.SetDateUpdated(st.now())
		}
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "TagRule already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "TagRule: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.TagRule.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "TagRule not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s TagRuleServiceServer) Erase(ctx context.Context, req *api.TagRuleRef) (*api.TagRuleEraseResponse, error) {
	p, err := TagRulePick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.TagRule.Query().Where(p).OnlyId(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &api.TagRuleEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = tagrule.And(p, tagrule.IdEQ(v))
	}

	u := st.Db.TagRule.Update().Where(p)
	u.SetDateErased(st.now())
	u.SetDateUpdated(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  api.TagRuleService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &api.TagRuleEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

// TagRulePick answers with the predicate this reference selects on,
// among the rows that are still here.
//
// Erasure is part of the reference and not only part of a read's scope,
// because a reference to a TagRule is composed into the reference of
// whatever names one: an index over an edge asks this for a predicate and
// puts it inside `HasTagRuleWith`, where no narrowing of a TagRule
// is ever applied. A child of an erased row would otherwise be readable by
// naming its parent.
func TagRulePick(req *api.TagRuleRef) (predicate.TagRule, error) {
	p, err := pickTagRule(req)
	if err != nil {
		return nil, err
	}

	return tagrule.And(tagrule.DateErasedIsNil(), p), nil
}

func pickTagRule(req *api.TagRuleRef) (predicate.TagRule, error) {
	switch req.WhichKey() {
	case api.TagRuleRef_Id_case:
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return tagrule.IdEQ(v), nil
		}
	case api.TagRuleRef_Slug_case:
		k := req.GetSlug()
		ps := make([]predicate.TagRule, 0, 2)
		ps = append(ps, tagrule.AliasEQ(k.GetAlias()))
		if p, err := TenantPick(k.GetTenant()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "slug.tenant: %s", err)
		} else {
			ps = append(ps, tagrule.HasTenantWith(p))
		}
		return tagrule.And(ps...), nil
	case api.TagRuleRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: TagRule")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
