// Code generated by ent, DO NOT EDIT.

package gcrun

import (
	"context"
	"fmt"
	"time"

	"github.com/lesomnus/cr/internal/ent/predicate"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Mutation represents an operation that mutates the GcRun nodes in the graph.
type Mutation struct {
	op              ent.Op
	typ             string
	kind            *string
	trigger         *string
	state           *string
	error           *string
	stages          *int64
	addstages       *int64
	tags            *int64
	addtags         *int64
	manifests       *int64
	addmanifests    *int64
	repositories    *int64
	addrepositories *int64
	blobs           *int64
	addblobs        *int64
	bytes           *int64
	addbytes        *int64
	missing         *[]string
	appendmissing   []string
	date_finished   *time.Time
	date_updated    *time.Time
	date_created    *time.Time
	clearedFields   map[string]struct{}
	predicates      []predicate.GcRun
}

// NewMutation creates a new Mutation for the GcRun entity.
func NewMutation(op ent.Op) *Mutation {
	return &Mutation{
		op:            op,
		typ:           "GcRun",
		clearedFields: make(map[string]struct{}),
	}
}

// Predicates returns the list of predicates set on the mutation.
func (m *Mutation) Predicates() []predicate.GcRun {
	return m.predicates
}

// SetKind sets the "kind" field.
func (m *Mutation) SetKind(s string) {
	m.kind = &s
}

// Kind returns the value of the "kind" field in the mutation.
func (m *Mutation) Kind() (r string, exists bool) {
	v := m.kind
	if v == nil {
		return
	}
	return *v, true
}

// ResetKind resets all changes to the "kind" field.
func (m *Mutation) ResetKind() {
	m.kind = nil
}

// SetTrigger sets the "trigger" field.
func (m *Mutation) SetTrigger(s string) {
	m.trigger = &s
}

// Trigger returns the value of the "trigger" field in the mutation.
func (m *Mutation) Trigger() (r string, exists bool) {
	v := m.trigger
	if v == nil {
		return
	}
	return *v, true
}

// ResetTrigger resets all changes to the "trigger" field.
func (m *Mutation) ResetTrigger() {
	m.trigger = nil
}

// SetState sets the "state" field.
func (m *Mutation) SetState(s string) {
	m.state = &s
}

// State returns the value of the "state" field in the mutation.
func (m *Mutation) State() (r string, exists bool) {
	v := m.state
	if v == nil {
		return
	}
	return *v, true
}

// ResetState resets all changes to the "state" field.
func (m *Mutation) ResetState() {
	m.state = nil
}

// SetError sets the "error" field.
func (m *Mutation) SetError(s string) {
	m.error = &s
}

// Error returns the value of the "error" field in the mutation.
func (m *Mutation) Error() (r string, exists bool) {
	v := m.error
	if v == nil {
		return
	}
	return *v, true
}

// ResetError resets all changes to the "error" field.
func (m *Mutation) ResetError() {
	m.error = nil
}

// SetStages sets the "stages" field.
func (m *Mutation) SetStages(i int64) {
	m.stages = &i
	m.addstages = nil
}

// Stages returns the value of the "stages" field in the mutation.
func (m *Mutation) Stages() (r int64, exists bool) {
	v := m.stages
	if v == nil {
		return
	}
	return *v, true
}

// AddStages adds i to the "stages" field.
func (m *Mutation) AddStages(i int64) {
	if m.addstages != nil {
		*m.addstages += i
	} else {
		m.addstages = &i
	}
}

// AddedStages returns the value that was added to the "stages" field in this mutation.
func (m *Mutation) AddedStages() (r int64, exists bool) {
	v := m.addstages
	if v == nil {
		return
	}
	return *v, true
}

// ResetStages resets all changes to the "stages" field.
func (m *Mutation) ResetStages() {
	m.stages = nil
	m.addstages = nil
}

// SetTags sets the "tags" field.
func (m *Mutation) SetTags(i int64) {
	m.tags = &i
	m.addtags = nil
}

// Tags returns the value of the "tags" field in the mutation.
func (m *Mutation) Tags() (r int64, exists bool) {
	v := m.tags
	if v == nil {
		return
	}
	return *v, true
}

// AddTags adds i to the "tags" field.
func (m *Mutation) AddTags(i int64) {
	if m.addtags != nil {
		*m.addtags += i
	} else {
		m.addtags = &i
	}
}

// AddedTags returns the value that was added to the "tags" field in this mutation.
func (m *Mutation) AddedTags() (r int64, exists bool) {
	v := m.addtags
	if v == nil {
		return
	}
	return *v, true
}

// ResetTags resets all changes to the "tags" field.
func (m *Mutation) ResetTags() {
	m.tags = nil
	m.addtags = nil
}

// SetManifests sets the "manifests" field.
func (m *Mutation) SetManifests(i int64) {
	m.manifests = &i
	m.addmanifests = nil
}

// Manifests returns the value of the "manifests" field in the mutation.
func (m *Mutation) Manifests() (r int64, exists bool) {
	v := m.manifests
	if v == nil {
		return
	}
	return *v, true
}

// AddManifests adds i to the "manifests" field.
func (m *Mutation) AddManifests(i int64) {
	if m.addmanifests != nil {
		*m.addmanifests += i
	} else {
		m.addmanifests = &i
	}
}

// AddedManifests returns the value that was added to the "manifests" field in this mutation.
func (m *Mutation) AddedManifests() (r int64, exists bool) {
	v := m.addmanifests
	if v == nil {
		return
	}
	return *v, true
}

// ResetManifests resets all changes to the "manifests" field.
func (m *Mutation) ResetManifests() {
	m.manifests = nil
	m.addmanifests = nil
}

// SetRepositories sets the "repositories" field.
func (m *Mutation) SetRepositories(i int64) {
	m.repositories = &i
	m.addrepositories = nil
}

// Repositories returns the value of the "repositories" field in the mutation.
func (m *Mutation) Repositories() (r int64, exists bool) {
	v := m.repositories
	if v == nil {
		return
	}
	return *v, true
}

// AddRepositories adds i to the "repositories" field.
func (m *Mutation) AddRepositories(i int64) {
	if m.addrepositories != nil {
		*m.addrepositories += i
	} else {
		m.addrepositories = &i
	}
}

// AddedRepositories returns the value that was added to the "repositories" field in this mutation.
func (m *Mutation) AddedRepositories() (r int64, exists bool) {
	v := m.addrepositories
	if v == nil {
		return
	}
	return *v, true
}

// ResetRepositories resets all changes to the "repositories" field.
func (m *Mutation) ResetRepositories() {
	m.repositories = nil
	m.addrepositories = nil
}

// SetBlobs sets the "blobs" field.
func (m *Mutation) SetBlobs(i int64) {
	m.blobs = &i
	m.addblobs = nil
}

// Blobs returns the value of the "blobs" field in the mutation.
func (m *Mutation) Blobs() (r int64, exists bool) {
	v := m.blobs
	if v == nil {
		return
	}
	return *v, true
}

// AddBlobs adds i to the "blobs" field.
func (m *Mutation) AddBlobs(i int64) {
	if m.addblobs != nil {
		*m.addblobs += i
	} else {
		m.addblobs = &i
	}
}

// AddedBlobs returns the value that was added to the "blobs" field in this mutation.
func (m *Mutation) AddedBlobs() (r int64, exists bool) {
	v := m.addblobs
	if v == nil {
		return
	}
	return *v, true
}

// ResetBlobs resets all changes to the "blobs" field.
func (m *Mutation) ResetBlobs() {
	m.blobs = nil
	m.addblobs = nil
}

// SetBytes sets the "bytes" field.
func (m *Mutation) SetBytes(i int64) {
	m.bytes = &i
	m.addbytes = nil
}

// Bytes returns the value of the "bytes" field in the mutation.
func (m *Mutation) Bytes() (r int64, exists bool) {
	v := m.bytes
	if v == nil {
		return
	}
	return *v, true
}

// AddBytes adds i to the "bytes" field.
func (m *Mutation) AddBytes(i int64) {
	if m.addbytes != nil {
		*m.addbytes += i
	} else {
		m.addbytes = &i
	}
}

// AddedBytes returns the value that was added to the "bytes" field in this mutation.
func (m *Mutation) AddedBytes() (r int64, exists bool) {
	v := m.addbytes
	if v == nil {
		return
	}
	return *v, true
}

// ResetBytes resets all changes to the "bytes" field.
func (m *Mutation) ResetBytes() {
	m.bytes = nil
	m.addbytes = nil
}

// SetMissing sets the "missing" field.
func (m *Mutation) SetMissing(s []string) {
	m.missing = &s
	m.appendmissing = nil
}

// Missing returns the value of the "missing" field in the mutation.
func (m *Mutation) Missing() (r []string, exists bool) {
	v := m.missing
	if v == nil {
		return
	}
	return *v, true
}

// AppendMissing adds s to the "missing" field.
func (m *Mutation) AppendMissing(s []string) {
	m.appendmissing = append(m.appendmissing, s...)
}

// AppendedMissing returns the list of values that were appended to the "missing" field in this mutation.
func (m *Mutation) AppendedMissing() ([]string, bool) {
	if len(m.appendmissing) == 0 {
		return nil, false
	}
	return m.appendmissing, true
}

// ClearMissing clears the value of the "missing" field.
func (m *Mutation) ClearMissing() {
	m.missing = nil
	m.appendmissing = nil
	m.clearedFields[FieldMissing] = struct{}{}
}

// MissingCleared returns if the "missing" field was cleared in this mutation.
func (m *Mutation) MissingCleared() bool {
	_, ok := m.clearedFields[FieldMissing]
	return ok
}

// ResetMissing resets all changes to the "missing" field.
func (m *Mutation) ResetMissing() {
	m.missing = nil
	m.appendmissing = nil
	delete(m.clearedFields, FieldMissing)
}

// SetDateFinished sets the "date_finished" field.
func (m *Mutation) SetDateFinished(t time.Time) {
	m.date_finished = &t
}

// DateFinished returns the value of the "date_finished" field in the mutation.
func (m *Mutation) DateFinished() (r time.Time, exists bool) {
	v := m.date_finished
	if v == nil {
		return
	}
	return *v, true
}

// ClearDateFinished clears the value of the "date_finished" field.
func (m *Mutation) ClearDateFinished() {
	m.date_finished = nil
	m.clearedFields[FieldDateFinished] = struct{}{}
}

// DateFinishedCleared returns if the "date_finished" field was cleared in this mutation.
func (m *Mutation) DateFinishedCleared() bool {
	_, ok := m.clearedFields[FieldDateFinished]
	return ok
}

// ResetDateFinished resets all changes to the "date_finished" field.
func (m *Mutation) ResetDateFinished() {
	m.date_finished = nil
	delete(m.clearedFields, FieldDateFinished)
}

// SetDateUpdated sets the "date_updated" field.
func (m *Mutation) SetDateUpdated(t time.Time) {
	m.date_updated = &t
}

// DateUpdated returns the value of the "date_updated" field in the mutation.
func (m *Mutation) DateUpdated() (r time.Time, exists bool) {
	v := m.date_updated
	if v == nil {
		return
	}
	return *v, true
}

// ResetDateUpdated resets all changes to the "date_updated" field.
func (m *Mutation) ResetDateUpdated() {
	m.date_updated = nil
}

// SetDateCreated sets the "date_created" field.
func (m *Mutation) SetDateCreated(t time.Time) {
	m.date_created = &t
}

// DateCreated returns the value of the "date_created" field in the mutation.
func (m *Mutation) DateCreated() (r time.Time, exists bool) {
	v := m.date_created
	if v == nil {
		return
	}
	return *v, true
}

// ClearDateCreated clears the value of the "date_created" field.
func (m *Mutation) ClearDateCreated() {
	m.date_created = nil
	m.clearedFields[FieldDateCreated] = struct{}{}
}

// DateCreatedCleared returns if the "date_created" field was cleared in this mutation.
func (m *Mutation) DateCreatedCleared() bool {
	_, ok := m.clearedFields[FieldDateCreated]
	return ok
}

// ResetDateCreated resets all changes to the "date_created" field.
func (m *Mutation) ResetDateCreated() {
	m.date_created = nil
	delete(m.clearedFields, FieldDateCreated)
}

// Where appends a list predicates to the Mutation builder.
func (m *Mutation) Where(ps ...predicate.GcRun) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the Mutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *Mutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.GcRun, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *Mutation) Op() ent.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *Mutation) SetOp(op ent.Op) {
	m.op = op
}

// Type returns the node type of this mutation (GcRun).
func (m *Mutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *Mutation) Fields() []string {
	fields := make([]string, 0, 14)
	if m.kind != nil {
		fields = append(fields, FieldKind)
	}
	if m.trigger != nil {
		fields = append(fields, FieldTrigger)
	}
	if m.state != nil {
		fields = append(fields, FieldState)
	}
	if m.error != nil {
		fields = append(fields, FieldError)
	}
	if m.stages != nil {
		fields = append(fields, FieldStages)
	}
	if m.tags != nil {
		fields = append(fields, FieldTags)
	}
	if m.manifests != nil {
		fields = append(fields, FieldManifests)
	}
	if m.repositories != nil {
		fields = append(fields, FieldRepositories)
	}
	if m.blobs != nil {
		fields = append(fields, FieldBlobs)
	}
	if m.bytes != nil {
		fields = append(fields, FieldBytes)
	}
	if m.missing != nil {
		fields = append(fields, FieldMissing)
	}
	if m.date_finished != nil {
		fields = append(fields, FieldDateFinished)
	}
	if m.date_updated != nil {
		fields = append(fields, FieldDateUpdated)
	}
	if m.date_created != nil {
		fields = append(fields, FieldDateCreated)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *Mutation) Field(name string) (ent.Value, bool) {
	switch name {
	case FieldKind:
		return m.Kind()
	case FieldTrigger:
		return m.Trigger()
	case FieldState:
		return m.State()
	case FieldError:
		return m.Error()
	case FieldStages:
		return m.Stages()
	case FieldTags:
		return m.Tags()
	case FieldManifests:
		return m.Manifests()
	case FieldRepositories:
		return m.Repositories()
	case FieldBlobs:
		return m.Blobs()
	case FieldBytes:
		return m.Bytes()
	case FieldMissing:
		return m.Missing()
	case FieldDateFinished:
		return m.DateFinished()
	case FieldDateUpdated:
		return m.DateUpdated()
	case FieldDateCreated:
		return m.DateCreated()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *Mutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown GcRun field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) SetField(name string, value ent.Value) error {
	switch name {
	case FieldKind:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKind(v)
		return nil
	case FieldTrigger:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTrigger(v)
		return nil
	case FieldState:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetState(v)
		return nil
	case FieldError:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetError(v)
		return nil
	case FieldStages:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStages(v)
		return nil
	case FieldTags:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTags(v)
		return nil
	case FieldManifests:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetManifests(v)
		return nil
	case FieldRepositories:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRepositories(v)
		return nil
	case FieldBlobs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBlobs(v)
		return nil
	case FieldBytes:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBytes(v)
		return nil
	case FieldMissing:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMissing(v)
		return nil
	case FieldDateFinished:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateFinished(v)
		return nil
	case FieldDateUpdated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateUpdated(v)
		return nil
	case FieldDateCreated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateCreated(v)
		return nil
	}
	return fmt.Errorf("unknown GcRun field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *Mutation) AddedFields() []string {
	var fields []string
	if m.addstages != nil {
		fields = append(fields, FieldStages)
	}
	if m.addtags != nil {
		fields = append(fields, FieldTags)
	}
	if m.addmanifests != nil {
		fields = append(fields, FieldManifests)
	}
	if m.addrepositories != nil {
		fields = append(fields, FieldRepositories)
	}
	if m.addblobs != nil {
		fields = append(fields, FieldBlobs)
	}
	if m.addbytes != nil {
		fields = append(fields, FieldBytes)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *Mutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case FieldStages:
		return m.AddedStages()
	case FieldTags:
		return m.AddedTags()
	case FieldManifests:
		return m.AddedManifests()
	case FieldRepositories:
		return m.AddedRepositories()
	case FieldBlobs:
		return m.AddedBlobs()
	case FieldBytes:
		return m.AddedBytes()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) AddField(name string, value ent.Value) error {
	switch name {
	case FieldStages:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStages(v)
		return nil
	case FieldTags:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTags(v)
		return nil
	case FieldManifests:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddManifests(v)
		return nil
	case FieldRepositories:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRepositories(v)
		return nil
	case FieldBlobs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddBlobs(v)
		return nil
	case FieldBytes:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddBytes(v)
		return nil
	}
	return fmt.Errorf("unknown GcRun numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *Mutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(FieldMissing) {
		fields = append(fields, FieldMissing)
	}
	if m.FieldCleared(FieldDateFinished) {
		fields = append(fields, FieldDateFinished)
	}
	if m.FieldCleared(FieldDateCreated) {
		fields = append(fields, FieldDateCreated)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *Mutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *Mutation) ClearField(name string) error {
	switch name {
	case FieldMissing:
		m.ClearMissing()
		return nil
	case FieldDateFinished:
		m.ClearDateFinished()
		return nil
	case FieldDateCreated:
		m.ClearDateCreated()
		return nil
	}
	return fmt.Errorf("unknown GcRun nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *Mutation) ResetField(name string) error {
	switch name {
	case FieldKind:
		m.ResetKind()
		return nil
	case FieldTrigger:
		m.ResetTrigger()
		return nil
	case FieldState:
		m.ResetState()
		return nil
	case FieldError:
		m.ResetError()
		return nil
	case FieldStages:
		m.ResetStages()
		return nil
	case FieldTags:
		m.ResetTags()
		return nil
	case FieldManifests:
		m.ResetManifests()
		return nil
	case FieldRepositories:
		m.ResetRepositories()
		return nil
	case FieldBlobs:
		m.ResetBlobs()
		return nil
	case FieldBytes:
		m.ResetBytes()
		return nil
	case FieldMissing:
		m.ResetMissing()
		return nil
	case FieldDateFinished:
		m.ResetDateFinished()
		return nil
	case FieldDateUpdated:
		m.ResetDateUpdated()
		return nil
	case FieldDateCreated:
		m.ResetDateCreated()
		return nil
	}
	return fmt.Errorf("unknown GcRun field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *Mutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIds returns all Ids (to other nodes) that were added for the given edge
// name in this mutation.
func (m *Mutation) AddedIds(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *Mutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIds returns all Ids (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *Mutation) RemovedIds(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *Mutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *Mutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *Mutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown GcRun unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *Mutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown GcRun edge %s", name)
}
