// Code generated by ent, DO NOT EDIT.

package gcrun

import (
	"time"
	"uuid"

	"github.com/lesomnus/cr/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Id filters vertices based on their Id field.
func Id(id uuid.UUID) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldId, id))
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id uuid.UUID) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldId, id))
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id uuid.UUID) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldId, id))
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...uuid.UUID) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldId, ids...))
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...uuid.UUID) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldId, ids...))
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id uuid.UUID) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldId, id))
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id uuid.UUID) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldId, id))
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id uuid.UUID) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldId, id))
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id uuid.UUID) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldId, id))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldKind, v))
}

// Trigger applies equality check predicate on the "trigger" field. It's identical to TriggerEQ.
func Trigger(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldTrigger, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldState, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldError, v))
}

// Stages applies equality check predicate on the "stages" field. It's identical to StagesEQ.
func Stages(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldStages, v))
}

// Tags applies equality check predicate on the "tags" field. It's identical to TagsEQ.
func Tags(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldTags, v))
}

// Manifests applies equality check predicate on the "manifests" field. It's identical to ManifestsEQ.
func Manifests(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldManifests, v))
}

// Repositories applies equality check predicate on the "repositories" field. It's identical to RepositoriesEQ.
func Repositories(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldRepositories, v))
}

// Blobs applies equality check predicate on the "blobs" field. It's identical to BlobsEQ.
func Blobs(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldBlobs, v))
}

// Bytes applies equality check predicate on the "bytes" field. It's identical to BytesEQ.
func Bytes(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldBytes, v))
}

// DateFinished applies equality check predicate on the "date_finished" field. It's identical to DateFinishedEQ.
func DateFinished(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldDateFinished, v))
}

// DateUpdated applies equality check predicate on the "date_updated" field. It's identical to DateUpdatedEQ.
func DateUpdated(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldDateUpdated, v))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldDateCreated, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldContainsFold(FieldKind, v))
}

// TriggerEQ applies the EQ predicate on the "trigger" field.
func TriggerEQ(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldTrigger, v))
}

// TriggerNEQ applies the NEQ predicate on the "trigger" field.
func TriggerNEQ(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldTrigger, v))
}

// TriggerIn applies the In predicate on the "trigger" field.
func TriggerIn(vs ...string) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldTrigger, vs...))
}

// TriggerNotIn applies the NotIn predicate on the "trigger" field.
func TriggerNotIn(vs ...string) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldTrigger, vs...))
}

// TriggerGT applies the GT predicate on the "trigger" field.
func TriggerGT(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldTrigger, v))
}

// TriggerGTE applies the GTE predicate on the "trigger" field.
func TriggerGTE(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldTrigger, v))
}

// TriggerLT applies the LT predicate on the "trigger" field.
func TriggerLT(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldTrigger, v))
}

// TriggerLTE applies the LTE predicate on the "trigger" field.
func TriggerLTE(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldTrigger, v))
}

// TriggerContains applies the Contains predicate on the "trigger" field.
func TriggerContains(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldContains(FieldTrigger, v))
}

// TriggerHasPrefix applies the HasPrefix predicate on the "trigger" field.
func TriggerHasPrefix(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldHasPrefix(FieldTrigger, v))
}

// TriggerHasSuffix applies the HasSuffix predicate on the "trigger" field.
func TriggerHasSuffix(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldHasSuffix(FieldTrigger, v))
}

// TriggerEqualFold applies the EqualFold predicate on the "trigger" field.
func TriggerEqualFold(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldEqualFold(FieldTrigger, v))
}

// TriggerContainsFold applies the ContainsFold predicate on the "trigger" field.
func TriggerContainsFold(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldContainsFold(FieldTrigger, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldContainsFold(FieldState, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldHasSuffix(FieldError, v))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.GcRun {
	return predicate.GcRun(sql.FieldContainsFold(FieldError, v))
}

// StagesEQ applies the EQ predicate on the "stages" field.
func StagesEQ(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldStages, v))
}

// StagesNEQ applies the NEQ predicate on the "stages" field.
func StagesNEQ(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldStages, v))
}

// StagesIn applies the In predicate on the "stages" field.
func StagesIn(vs ...int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldStages, vs...))
}

// StagesNotIn applies the NotIn predicate on the "stages" field.
func StagesNotIn(vs ...int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldStages, vs...))
}

// StagesGT applies the GT predicate on the "stages" field.
func StagesGT(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldStages, v))
}

// StagesGTE applies the GTE predicate on the "stages" field.
func StagesGTE(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldStages, v))
}

// StagesLT applies the LT predicate on the "stages" field.
func StagesLT(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldStages, v))
}

// StagesLTE applies the LTE predicate on the "stages" field.
func StagesLTE(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldStages, v))
}

// TagsEQ applies the EQ predicate on the "tags" field.
func TagsEQ(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldTags, v))
}

// TagsNEQ applies the NEQ predicate on the "tags" field.
func TagsNEQ(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldTags, v))
}

// TagsIn applies the In predicate on the "tags" field.
func TagsIn(vs ...int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldTags, vs...))
}

// TagsNotIn applies the NotIn predicate on the "tags" field.
func TagsNotIn(vs ...int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldTags, vs...))
}

// TagsGT applies the GT predicate on the "tags" field.
func TagsGT(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldTags, v))
}

// TagsGTE applies the GTE predicate on the "tags" field.
func TagsGTE(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldTags, v))
}

// TagsLT applies the LT predicate on the "tags" field.
func TagsLT(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldTags, v))
}

// TagsLTE applies the LTE predicate on the "tags" field.
func TagsLTE(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldTags, v))
}

// ManifestsEQ applies the EQ predicate on the "manifests" field.
func ManifestsEQ(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldManifests, v))
}

// ManifestsNEQ applies the NEQ predicate on the "manifests" field.
func ManifestsNEQ(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldManifests, v))
}

// ManifestsIn applies the In predicate on the "manifests" field.
func ManifestsIn(vs ...int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldManifests, vs...))
}

// ManifestsNotIn applies the NotIn predicate on the "manifests" field.
func ManifestsNotIn(vs ...int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldManifests, vs...))
}

// ManifestsGT applies the GT predicate on the "manifests" field.
func ManifestsGT(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldManifests, v))
}

// ManifestsGTE applies the GTE predicate on the "manifests" field.
func ManifestsGTE(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldManifests, v))
}

// ManifestsLT applies the LT predicate on the "manifests" field.
func ManifestsLT(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldManifests, v))
}

// ManifestsLTE applies the LTE predicate on the "manifests" field.
func ManifestsLTE(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldManifests, v))
}

// RepositoriesEQ applies the EQ predicate on the "repositories" field.
func RepositoriesEQ(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldRepositories, v))
}

// RepositoriesNEQ applies the NEQ predicate on the "repositories" field.
func RepositoriesNEQ(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldRepositories, v))
}

// RepositoriesIn applies the In predicate on the "repositories" field.
func RepositoriesIn(vs ...int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldRepositories, vs...))
}

// RepositoriesNotIn applies the NotIn predicate on the "repositories" field.
func RepositoriesNotIn(vs ...int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldRepositories, vs...))
}

// RepositoriesGT applies the GT predicate on the "repositories" field.
func RepositoriesGT(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldRepositories, v))
}

// RepositoriesGTE applies the GTE predicate on the "repositories" field.
func RepositoriesGTE(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldRepositories, v))
}

// RepositoriesLT applies the LT predicate on the "repositories" field.
func RepositoriesLT(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldRepositories, v))
}

// RepositoriesLTE applies the LTE predicate on the "repositories" field.
func RepositoriesLTE(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldRepositories, v))
}

// BlobsEQ applies the EQ predicate on the "blobs" field.
func BlobsEQ(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldBlobs, v))
}

// BlobsNEQ applies the NEQ predicate on the "blobs" field.
func BlobsNEQ(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldBlobs, v))
}

// BlobsIn applies the In predicate on the "blobs" field.
func BlobsIn(vs ...int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldBlobs, vs...))
}

// BlobsNotIn applies the NotIn predicate on the "blobs" field.
func BlobsNotIn(vs ...int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldBlobs, vs...))
}

// BlobsGT applies the GT predicate on the "blobs" field.
func BlobsGT(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldBlobs, v))
}

// BlobsGTE applies the GTE predicate on the "blobs" field.
func BlobsGTE(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldBlobs, v))
}

// BlobsLT applies the LT predicate on the "blobs" field.
func BlobsLT(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldBlobs, v))
}

// BlobsLTE applies the LTE predicate on the "blobs" field.
func BlobsLTE(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldBlobs, v))
}

// BytesEQ applies the EQ predicate on the "bytes" field.
func BytesEQ(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldBytes, v))
}

// BytesNEQ applies the NEQ predicate on the "bytes" field.
func BytesNEQ(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldBytes, v))
}

// BytesIn applies the In predicate on the "bytes" field.
func BytesIn(vs ...int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldBytes, vs...))
}

// BytesNotIn applies the NotIn predicate on the "bytes" field.
func BytesNotIn(vs ...int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldBytes, vs...))
}

// BytesGT applies the GT predicate on the "bytes" field.
func BytesGT(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldBytes, v))
}

// BytesGTE applies the GTE predicate on the "bytes" field.
func BytesGTE(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldBytes, v))
}

// BytesLT applies the LT predicate on the "bytes" field.
func BytesLT(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldBytes, v))
}

// BytesLTE applies the LTE predicate on the "bytes" field.
func BytesLTE(v int64) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldBytes, v))
}

// MissingIsNil applies the IsNil predicate on the "missing" field.
func MissingIsNil() predicate.GcRun {
	return predicate.GcRun(sql.FieldIsNull(FieldMissing))
}

// MissingNotNil applies the NotNil predicate on the "missing" field.
func MissingNotNil() predicate.GcRun {
	return predicate.GcRun(sql.FieldNotNull(FieldMissing))
}

// DateFinishedEQ applies the EQ predicate on the "date_finished" field.
func DateFinishedEQ(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldDateFinished, v))
}

// DateFinishedNEQ applies the NEQ predicate on the "date_finished" field.
func DateFinishedNEQ(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldDateFinished, v))
}

// DateFinishedIn applies the In predicate on the "date_finished" field.
func DateFinishedIn(vs ...time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldDateFinished, vs...))
}

// DateFinishedNotIn applies the NotIn predicate on the "date_finished" field.
func DateFinishedNotIn(vs ...time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldDateFinished, vs...))
}

// DateFinishedGT applies the GT predicate on the "date_finished" field.
func DateFinishedGT(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldDateFinished, v))
}

// DateFinishedGTE applies the GTE predicate on the "date_finished" field.
func DateFinishedGTE(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldDateFinished, v))
}

// DateFinishedLT applies the LT predicate on the "date_finished" field.
func DateFinishedLT(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldDateFinished, v))
}

// DateFinishedLTE applies the LTE predicate on the "date_finished" field.
func DateFinishedLTE(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldDateFinished, v))
}

// DateFinishedIsNil applies the IsNil predicate on the "date_finished" field.
func DateFinishedIsNil() predicate.GcRun {
	return predicate.GcRun(sql.FieldIsNull(FieldDateFinished))
}

// DateFinishedNotNil applies the NotNil predicate on the "date_finished" field.
func DateFinishedNotNil() predicate.GcRun {
	return predicate.GcRun(sql.FieldNotNull(FieldDateFinished))
}

// DateUpdatedEQ applies the EQ predicate on the "date_updated" field.
func DateUpdatedEQ(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldDateUpdated, v))
}

// DateUpdatedNEQ applies the NEQ predicate on the "date_updated" field.
func DateUpdatedNEQ(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldDateUpdated, v))
}

// DateUpdatedIn applies the In predicate on the "date_updated" field.
func DateUpdatedIn(vs ...time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldDateUpdated, vs...))
}

// DateUpdatedNotIn applies the NotIn predicate on the "date_updated" field.
func DateUpdatedNotIn(vs ...time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldDateUpdated, vs...))
}

// DateUpdatedGT applies the GT predicate on the "date_updated" field.
func DateUpdatedGT(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldDateUpdated, v))
}

// DateUpdatedGTE applies the GTE predicate on the "date_updated" field.
func DateUpdatedGTE(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldDateUpdated, v))
}

// DateUpdatedLT applies the LT predicate on the "date_updated" field.
func DateUpdatedLT(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldDateUpdated, v))
}

// DateUpdatedLTE applies the LTE predicate on the "date_updated" field.
func DateUpdatedLTE(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldDateUpdated, v))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.GcRun {
	return predicate.GcRun(sql.FieldLTE(FieldDateCreated, v))
}

// DateCreatedIsNil applies the IsNil predicate on the "date_created" field.
func DateCreatedIsNil() predicate.GcRun {
	return predicate.GcRun(sql.FieldIsNull(FieldDateCreated))
}

// DateCreatedNotNil applies the NotNil predicate on the "date_created" field.
func DateCreatedNotNil() predicate.GcRun {
	return predicate.GcRun(sql.FieldNotNull(FieldDateCreated))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GcRun) predicate.GcRun {
	return predicate.GcRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GcRun) predicate.GcRun {
	return predicate.GcRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GcRun) predicate.GcRun {
	return predicate.GcRun(sql.NotPredicates(p))
}
