// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: app/binding_svc.g.proto

package api

import (
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BindingAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Subject     string                 `protobuf:"bytes,8,opt,name=subject"`
	xxx_hidden_Group       string                 `protobuf:"bytes,9,opt,name=group"`
	xxx_hidden_Repo        string                 `protobuf:"bytes,10,opt,name=repo"`
	xxx_hidden_Actions     []string               `protobuf:"bytes,11,rep,name=actions"`
	xxx_hidden_When        map[string]string      `protobuf:"bytes,12,rep,name=when" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BindingAddRequest) Reset() {
	*x = BindingAddRequest{}
	mi := &file_app_binding_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingAddRequest) ProtoMessage() {}

func (x *BindingAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *BindingAddRequest) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *BindingAddRequest) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *BindingAddRequest) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *BindingAddRequest) GetSubject() string {
	if x != nil {
		return x.xxx_hidden_Subject
	}
	return ""
}

func (x *BindingAddRequest) GetGroup() string {
	if x != nil {
		return x.xxx_hidden_Group
	}
	return ""
}

func (x *BindingAddRequest) GetRepo() string {
	if x != nil {
		return x.xxx_hidden_Repo
	}
	return ""
}

func (x *BindingAddRequest) GetActions() []string {
	if x != nil {
		return x.xxx_hidden_Actions
	}
	return nil
}

func (x *BindingAddRequest) GetWhen() map[string]string {
	if x != nil {
		return x.xxx_hidden_When
	}
	return nil
}

func (x *BindingAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *BindingAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *BindingAddRequest) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *BindingAddRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *BindingAddRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *BindingAddRequest) SetSubject(v string) {
	x.xxx_hidden_Subject = v
}

func (x *BindingAddRequest) SetGroup(v string) {
	x.xxx_hidden_Group = v
}

func (x *BindingAddRequest) SetRepo(v string) {
	x.xxx_hidden_Repo = v
}

func (x *BindingAddRequest) SetActions(v []string) {
	x.xxx_hidden_Actions = v
}

func (x *BindingAddRequest) SetWhen(v map[string]string) {
	x.xxx_hidden_When = v
}

func (x *BindingAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *BindingAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BindingAddRequest) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *BindingAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *BindingAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *BindingAddRequest) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *BindingAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type BindingAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	Tenant      *TenantRef
	Alias       string
	Desc        string
	Subject     string
	Group       string
	Repo        string
	Actions     []string
	When        map[string]string
	DateCreated *timestamppb.Timestamp
}

func (b0 BindingAddRequest_builder) Build() *BindingAddRequest {
	m0 := &BindingAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Subject = b.Subject
	x.xxx_hidden_Group = b.Group
	x.xxx_hidden_Repo = b.Repo
	x.xxx_hidden_Actions = b.Actions
	x.xxx_hidden_When = b.When
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

type BindingGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *BindingRef            `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *BindingSelect         `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BindingGetRequest) Reset() {
	*x = BindingGetRequest{}
	mi := &file_app_binding_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingGetRequest) ProtoMessage() {}

func (x *BindingGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingGetRequest) GetRef() *BindingRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *BindingGetRequest) GetSelect() *BindingSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *BindingGetRequest) SetRef(v *BindingRef) {
	x.xxx_hidden_Ref = v
}

func (x *BindingGetRequest) SetSelect(v *BindingSelect) {
	x.xxx_hidden_Select = v
}

func (x *BindingGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *BindingGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *BindingGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *BindingGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type BindingGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *BindingRef
	Select *BindingSelect
}

func (b0 BindingGetRequest_builder) Build() *BindingGetRequest {
	m0 := &BindingGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type BindingRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isBindingRef_Key       `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BindingRef) Reset() {
	*x = BindingRef{}
	mi := &file_app_binding_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingRef) ProtoMessage() {}

func (x *BindingRef) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*bindingRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *BindingRef) GetSlug() *BindingRefBySlug {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*bindingRef_Slug); ok {
			return x.Slug
		}
	}
	return nil
}

func (x *BindingRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &bindingRef_Id{v}
}

func (x *BindingRef) SetSlug(v *BindingRefBySlug) {
	if v == nil {
		x.xxx_hidden_Key = nil
		return
	}
	x.xxx_hidden_Key = &bindingRef_Slug{v}
}

func (x *BindingRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *BindingRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*bindingRef_Id)
	return ok
}

func (x *BindingRef) HasSlug() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*bindingRef_Slug)
	return ok
}

func (x *BindingRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *BindingRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*bindingRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *BindingRef) ClearSlug() {
	if _, ok := x.xxx_hidden_Key.(*bindingRef_Slug); ok {
		x.xxx_hidden_Key = nil
	}
}

const BindingRef_Key_not_set_case case_BindingRef_Key = 0
const BindingRef_Id_case case_BindingRef_Key = 1
const BindingRef_Slug_case case_BindingRef_Key = 4

func (x *BindingRef) WhichKey() case_BindingRef_Key {
	if x == nil {
		return BindingRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *bindingRef_Id:
		return BindingRef_Id_case
	case *bindingRef_Slug:
		return BindingRef_Slug_case
	default:
		return BindingRef_Key_not_set_case
	}
}

type BindingRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id   []byte
	Slug *BindingRefBySlug
	// -- end of xxx_hidden_Key
}

func (b0 BindingRef_builder) Build() *BindingRef {
	m0 := &BindingRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &bindingRef_Id{b.Id}
	}
	if b.Slug != nil {
		x.xxx_hidden_Key = &bindingRef_Slug{b.Slug}
	}
	return m0
}

type case_BindingRef_Key protoreflect.FieldNumber

func (x case_BindingRef_Key) String() string {
	md := file_app_binding_svc_g_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isBindingRef_Key interface {
	isBindingRef_Key()
}

type bindingRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type bindingRef_Slug struct {
	Slug *BindingRefBySlug `protobuf:"bytes,4,opt,name=slug,oneof"`
}

func (*bindingRef_Id) isBindingRef_Key() {}

func (*bindingRef_Slug) isBindingRef_Key() {}

type BindingRefBySlug struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BindingRefBySlug) Reset() {
	*x = BindingRefBySlug{}
	mi := &file_app_binding_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingRefBySlug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingRefBySlug) ProtoMessage() {}

func (x *BindingRefBySlug) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingRefBySlug) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *BindingRefBySlug) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *BindingRefBySlug) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *BindingRefBySlug) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *BindingRefBySlug) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BindingRefBySlug) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *BindingRefBySlug) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

func (x *BindingRefBySlug) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

type BindingRefBySlug_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias  *string
	Tenant *TenantRef
}

func (b0 BindingRefBySlug_builder) Build() *BindingRefBySlug {
	m0 := &BindingRefBySlug{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Alias = b.Alias
	}
	x.xxx_hidden_Tenant = b.Tenant
	return m0
}

type BindingSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Tenant      *TenantSelect          `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       bool                   `protobuf:"varint,4,opt,name=alias"`
	xxx_hidden_Desc        bool                   `protobuf:"varint,6,opt,name=desc"`
	xxx_hidden_Subject     bool                   `protobuf:"varint,8,opt,name=subject"`
	xxx_hidden_Group       bool                   `protobuf:"varint,9,opt,name=group"`
	xxx_hidden_Repo        bool                   `protobuf:"varint,10,opt,name=repo"`
	xxx_hidden_Actions     bool                   `protobuf:"varint,11,opt,name=actions"`
	xxx_hidden_When        bool                   `protobuf:"varint,12,opt,name=when"`
	xxx_hidden_DateErased  bool                   `protobuf:"varint,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateUpdated bool                   `protobuf:"varint,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateCreated bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BindingSelect) Reset() {
	*x = BindingSelect{}
	mi := &file_app_binding_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingSelect) ProtoMessage() {}

func (x *BindingSelect) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *BindingSelect) GetTenant() *TenantSelect {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *BindingSelect) GetAlias() bool {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return false
}

func (x *BindingSelect) GetDesc() bool {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return false
}

func (x *BindingSelect) GetSubject() bool {
	if x != nil {
		return x.xxx_hidden_Subject
	}
	return false
}

func (x *BindingSelect) GetGroup() bool {
	if x != nil {
		return x.xxx_hidden_Group
	}
	return false
}

func (x *BindingSelect) GetRepo() bool {
	if x != nil {
		return x.xxx_hidden_Repo
	}
	return false
}

func (x *BindingSelect) GetActions() bool {
	if x != nil {
		return x.xxx_hidden_Actions
	}
	return false
}

func (x *BindingSelect) GetWhen() bool {
	if x != nil {
		return x.xxx_hidden_When
	}
	return false
}

func (x *BindingSelect) GetDateErased() bool {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return false
}

func (x *BindingSelect) GetDateUpdated() bool {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return false
}

func (x *BindingSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *BindingSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 12)
}

func (x *BindingSelect) SetTenant(v *TenantSelect) {
	x.xxx_hidden_Tenant = v
}

func (x *BindingSelect) SetAlias(v bool) {
	x.xxx_hidden_Alias = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 12)
}

func (x *BindingSelect) SetDesc(v bool) {
	x.xxx_hidden_Desc = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 12)
}

func (x *BindingSelect) SetSubject(v bool) {
	x.xxx_hidden_Subject = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *BindingSelect) SetGroup(v bool) {
	x.xxx_hidden_Group = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *BindingSelect) SetRepo(v bool) {
	x.xxx_hidden_Repo = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 12)
}

func (x *BindingSelect) SetActions(v bool) {
	x.xxx_hidden_Actions = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 12)
}

func (x *BindingSelect) SetWhen(v bool) {
	x.xxx_hidden_When = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 12)
}

func (x *BindingSelect) SetDateErased(v bool) {
	x.xxx_hidden_DateErased = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 12)
}

func (x *BindingSelect) SetDateUpdated(v bool) {
	x.xxx_hidden_DateUpdated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 12)
}

func (x *BindingSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 12)
}

func (x *BindingSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BindingSelect) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *BindingSelect) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *BindingSelect) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *BindingSelect) HasSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *BindingSelect) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *BindingSelect) HasRepo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *BindingSelect) HasActions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *BindingSelect) HasWhen() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *BindingSelect) HasDateErased() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *BindingSelect) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *BindingSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *BindingSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *BindingSelect) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *BindingSelect) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Alias = false
}

func (x *BindingSelect) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Desc = false
}

func (x *BindingSelect) ClearSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Subject = false
}

func (x *BindingSelect) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Group = false
}

func (x *BindingSelect) ClearRepo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Repo = false
}

func (x *BindingSelect) ClearActions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Actions = false
}

func (x *BindingSelect) ClearWhen() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_When = false
}

func (x *BindingSelect) ClearDateErased() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_DateErased = false
}

func (x *BindingSelect) ClearDateUpdated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_DateUpdated = false
}

func (x *BindingSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_DateCreated = false
}

type BindingSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All         *bool
	Tenant      *TenantSelect
	Alias       *bool
	Desc        *bool
	Subject     *bool
	Group       *bool
	Repo        *bool
	Actions     *bool
	When        *bool
	DateErased  *bool
	DateUpdated *bool
	DateCreated *bool
}

func (b0 BindingSelect_builder) Build() *BindingSelect {
	m0 := &BindingSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 12)
		x.xxx_hidden_All = *b.All
	}
	x.xxx_hidden_Tenant = b.Tenant
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 12)
		x.xxx_hidden_Alias = *b.Alias
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 12)
		x.xxx_hidden_Desc = *b.Desc
	}
	if b.Subject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_Subject = *b.Subject
	}
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_Group = *b.Group
	}
	if b.Repo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 12)
		x.xxx_hidden_Repo = *b.Repo
	}
	if b.Actions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 12)
		x.xxx_hidden_Actions = *b.Actions
	}
	if b.When != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 12)
		x.xxx_hidden_When = *b.When
	}
	if b.DateErased != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 12)
		x.xxx_hidden_DateErased = *b.DateErased
	}
	if b.DateUpdated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 12)
		x.xxx_hidden_DateUpdated = *b.DateUpdated
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 12)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	return m0
}

type BindingPatchRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref              *BindingRef            `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Alias            *string                `protobuf:"bytes,8,opt,name=alias"`
	xxx_hidden_Desc             *string                `protobuf:"bytes,12,opt,name=desc"`
	xxx_hidden_Subject          *string                `protobuf:"bytes,16,opt,name=subject"`
	xxx_hidden_Group            *string                `protobuf:"bytes,18,opt,name=group"`
	xxx_hidden_Repo             *string                `protobuf:"bytes,20,opt,name=repo"`
	xxx_hidden_Actions          []string               `protobuf:"bytes,22,rep,name=actions"`
	xxx_hidden_When             map[string]string      `protobuf:"bytes,24,rep,name=when" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateUpdated      *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateUpdatedForce bool                   `protobuf:"varint,27,opt,name=date_updated_force,json=dateUpdatedForce"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *BindingPatchRequest) Reset() {
	*x = BindingPatchRequest{}
	mi := &file_app_binding_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingPatchRequest) ProtoMessage() {}

func (x *BindingPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingPatchRequest) GetRef() *BindingRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *BindingPatchRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *BindingPatchRequest) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *BindingPatchRequest) GetSubject() string {
	if x != nil {
		if x.xxx_hidden_Subject != nil {
			return *x.xxx_hidden_Subject
		}
		return ""
	}
	return ""
}

func (x *BindingPatchRequest) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *BindingPatchRequest) GetRepo() string {
	if x != nil {
		if x.xxx_hidden_Repo != nil {
			return *x.xxx_hidden_Repo
		}
		return ""
	}
	return ""
}

func (x *BindingPatchRequest) GetActions() []string {
	if x != nil {
		return x.xxx_hidden_Actions
	}
	return nil
}

func (x *BindingPatchRequest) GetWhen() map[string]string {
	if x != nil {
		return x.xxx_hidden_When
	}
	return nil
}

func (x *BindingPatchRequest) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *BindingPatchRequest) GetDateUpdatedForce() bool {
	if x != nil {
		return x.xxx_hidden_DateUpdatedForce
	}
	return false
}

func (x *BindingPatchRequest) SetRef(v *BindingRef) {
	x.xxx_hidden_Ref = v
}

func (x *BindingPatchRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *BindingPatchRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 10)
}

func (x *BindingPatchRequest) SetSubject(v string) {
	x.xxx_hidden_Subject = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 10)
}

func (x *BindingPatchRequest) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 10)
}

func (x *BindingPatchRequest) SetRepo(v string) {
	x.xxx_hidden_Repo = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 10)
}

func (x *BindingPatchRequest) SetActions(v []string) {
	x.xxx_hidden_Actions = v
}

func (x *BindingPatchRequest) SetWhen(v map[string]string) {
	x.xxx_hidden_When = v
}

func (x *BindingPatchRequest) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *BindingPatchRequest) SetDateUpdatedForce(v bool) {
	x.xxx_hidden_DateUpdatedForce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 10)
}

func (x *BindingPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *BindingPatchRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *BindingPatchRequest) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *BindingPatchRequest) HasSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *BindingPatchRequest) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *BindingPatchRequest) HasRepo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *BindingPatchRequest) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *BindingPatchRequest) HasDateUpdatedForce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *BindingPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *BindingPatchRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = nil
}

func (x *BindingPatchRequest) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Desc = nil
}

func (x *BindingPatchRequest) ClearSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Subject = nil
}

func (x *BindingPatchRequest) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Group = nil
}

func (x *BindingPatchRequest) ClearRepo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Repo = nil
}

func (x *BindingPatchRequest) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *BindingPatchRequest) ClearDateUpdatedForce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_DateUpdatedForce = false
}

type BindingPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref     *BindingRef
	Alias   *string
	Desc    *string
	Subject *string
	Group   *string
	Repo    *string
	Actions []string
	When    map[string]string
	// The version this update requires the stored date_updated to be.
	// It is a precondition, not a write: the update applies only if the row
	// still holds this value, and the server stamps the new version itself.
	// Setting it together with date_updated_force is an error --
	// the version is the token every client's compare-and-swap is measured
	// against, so it is not the caller's to choose.
	DateUpdated *timestamppb.Timestamp
	// Update whatever the stored date_updated is, with no precondition.
	// The server still stamps a new version, so other clients' tokens are
	// invalidated as usual; this declines the check for THIS update only.
	// One of date_updated or this must be set. An omitted version is
	// refused rather than assumed, because an unset field cannot be told
	// apart from a caller who never considered locking at all.
	DateUpdatedForce *bool
}

func (b0 BindingPatchRequest_builder) Build() *BindingPatchRequest {
	m0 := &BindingPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 10)
		x.xxx_hidden_Desc = b.Desc
	}
	if b.Subject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 10)
		x.xxx_hidden_Subject = b.Subject
	}
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 10)
		x.xxx_hidden_Group = b.Group
	}
	if b.Repo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 10)
		x.xxx_hidden_Repo = b.Repo
	}
	x.xxx_hidden_Actions = b.Actions
	x.xxx_hidden_When = b.When
	x.xxx_hidden_DateUpdated = b.DateUpdated
	if b.DateUpdatedForce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 10)
		x.xxx_hidden_DateUpdatedForce = *b.DateUpdatedForce
	}
	return m0
}

type BindingApplyRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref   *BindingRef            `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Patch *patchpb.Patch         `protobuf:"bytes,2,opt,name=patch"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BindingApplyRequest) Reset() {
	*x = BindingApplyRequest{}
	mi := &file_app_binding_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingApplyRequest) ProtoMessage() {}

func (x *BindingApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingApplyRequest) GetRef() *BindingRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *BindingApplyRequest) GetPatch() *patchpb.Patch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *BindingApplyRequest) SetRef(v *BindingRef) {
	x.xxx_hidden_Ref = v
}

func (x *BindingApplyRequest) SetPatch(v *patchpb.Patch) {
	x.xxx_hidden_Patch = v
}

func (x *BindingApplyRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *BindingApplyRequest) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *BindingApplyRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *BindingApplyRequest) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

type BindingApplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref   *BindingRef
	Patch *patchpb.Patch
}

func (b0 BindingApplyRequest_builder) Build() *BindingApplyRequest {
	m0 := &BindingApplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Patch = b.Patch
	return m0
}

type BindingEraseResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Erased      bool                   `protobuf:"varint,1,opt,name=erased"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BindingEraseResponse) Reset() {
	*x = BindingEraseResponse{}
	mi := &file_app_binding_svc_g_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingEraseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingEraseResponse) ProtoMessage() {}

func (x *BindingEraseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingEraseResponse) GetErased() bool {
	if x != nil {
		return x.xxx_hidden_Erased
	}
	return false
}

func (x *BindingEraseResponse) SetErased(v bool) {
	x.xxx_hidden_Erased = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *BindingEraseResponse) HasErased() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BindingEraseResponse) ClearErased() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Erased = false
}

type BindingEraseResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Erased is whether this call is the one that erased the row.
	//
	// False for a row that was already gone, was never there, or is out
	// of this caller's reach -- which are one answer on purpose, and the
	// reason the RPC does not fail instead.
	Erased *bool
}

func (b0 BindingEraseResponse_builder) Build() *BindingEraseResponse {
	m0 := &BindingEraseResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Erased != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Erased = *b.Erased
	}
	return m0
}

type BindingListRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters *[]*BindingFilter      `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_Size    int32                  `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_After   string                 `protobuf:"bytes,3,opt,name=after"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BindingListRequest) Reset() {
	*x = BindingListRequest{}
	mi := &file_app_binding_svc_g_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingListRequest) ProtoMessage() {}

func (x *BindingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingListRequest) GetFilters() []*BindingFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *BindingListRequest) GetSize() int32 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *BindingListRequest) GetAfter() string {
	if x != nil {
		return x.xxx_hidden_After
	}
	return ""
}

func (x *BindingListRequest) SetFilters(v []*BindingFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *BindingListRequest) SetSize(v int32) {
	x.xxx_hidden_Size = v
}

func (x *BindingListRequest) SetAfter(v string) {
	x.xxx_hidden_After = v
}

type BindingListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Bounded because the work is: each filter is a predicate in the same query,
	// so this is what says how much of the database one request may read.
	Filters []*BindingFilter
	// How many to answer with. Nothing said is what the schema declared, and more
	// than the cap is the cap -- a caller asking for more than there is meant no
	// harm, so it is not an error and it is not the whole table either.
	Size int32
	// Where to carry on from: the "next" of the answer before. It names the last
	// row of that page rather than counting rows from the start, so a row added
	// ahead of the page does not shift it and a caller reading through never sees
	// one twice or misses one.
	After string
}

func (b0 BindingListRequest_builder) Build() *BindingListRequest {
	m0 := &BindingListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	x.xxx_hidden_Size = b.Size
	x.xxx_hidden_After = b.After
	return m0
}

type BindingListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*Binding            `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_Next  string                 `protobuf:"bytes,2,opt,name=next"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BindingListResponse) Reset() {
	*x = BindingListResponse{}
	mi := &file_app_binding_svc_g_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingListResponse) ProtoMessage() {}

func (x *BindingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingListResponse) GetItems() []*Binding {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *BindingListResponse) GetNext() string {
	if x != nil {
		return x.xxx_hidden_Next
	}
	return ""
}

func (x *BindingListResponse) SetItems(v []*Binding) {
	x.xxx_hidden_Items = &v
}

func (x *BindingListResponse) SetNext(v string) {
	x.xxx_hidden_Next = v
}

type BindingListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*Binding
	// What to ask for next, and empty when this was the last of them.
	//
	// Empty means there is no more *for now*: a list is read as it is, and one
	// that has grown since answers a fresh call. It is not empty merely because
	// the page came back short -- a page is short when the last row of it was the
	// last row there was, which is a thing the server can only know by having
	// looked.
	Next string
}

func (b0 BindingListResponse_builder) Build() *BindingListResponse {
	m0 := &BindingListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_Next = b.Next
	return m0
}

type BindingFilter struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *BindingRef            `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Subject     *string                `protobuf:"bytes,3,opt,name=subject"`
	xxx_hidden_Group       *string                `protobuf:"bytes,4,opt,name=group"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BindingFilter) Reset() {
	*x = BindingFilter{}
	mi := &file_app_binding_svc_g_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingFilter) ProtoMessage() {}

func (x *BindingFilter) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingFilter) GetRef() *BindingRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *BindingFilter) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *BindingFilter) GetSubject() string {
	if x != nil {
		if x.xxx_hidden_Subject != nil {
			return *x.xxx_hidden_Subject
		}
		return ""
	}
	return ""
}

func (x *BindingFilter) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *BindingFilter) SetRef(v *BindingRef) {
	x.xxx_hidden_Ref = v
}

func (x *BindingFilter) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *BindingFilter) SetSubject(v string) {
	x.xxx_hidden_Subject = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *BindingFilter) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *BindingFilter) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *BindingFilter) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *BindingFilter) HasSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *BindingFilter) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *BindingFilter) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *BindingFilter) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *BindingFilter) ClearSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Subject = nil
}

func (x *BindingFilter) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Group = nil
}

type BindingFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref     *BindingRef
	Tenant  *TenantRef
	Subject *string
	Group   *string
}

func (b0 BindingFilter_builder) Build() *BindingFilter {
	m0 := &BindingFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Tenant = b.Tenant
	if b.Subject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Subject = b.Subject
	}
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Group = b.Group
	}
	return m0
}

type BindingWatchRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters      *[]*BindingFilter      `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_SkipSnapshot bool                   `protobuf:"varint,2,opt,name=skip_snapshot,json=skipSnapshot"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *BindingWatchRequest) Reset() {
	*x = BindingWatchRequest{}
	mi := &file_app_binding_svc_g_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingWatchRequest) ProtoMessage() {}

func (x *BindingWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingWatchRequest) GetFilters() []*BindingFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *BindingWatchRequest) GetSkipSnapshot() bool {
	if x != nil {
		return x.xxx_hidden_SkipSnapshot
	}
	return false
}

func (x *BindingWatchRequest) SetFilters(v []*BindingFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *BindingWatchRequest) SetSkipSnapshot(v bool) {
	x.xxx_hidden_SkipSnapshot = v
}

type BindingWatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Which rows to watch, in the same words List takes them: what is watched is
	// what that list would answer with, now and afterwards.
	//
	// Required, and bounded the way a List is -- for a heavier reason. A list
	// runs its filters once; a watch runs them again for every write that touches
	// the entity, for as long as the stream is open. A watch with no filters is
	// the whole table, forever, which is the one shape that has no cap at all.
	Filters []*BindingFilter
	// Skip what is there now and send only what changes from here.
	//
	// Off by default, and the default is the safe one: a client that does not
	// know the current state and did not ask for it holds something wrong until
	// the next write happens to correct it.
	SkipSnapshot bool
}

func (b0 BindingWatchRequest_builder) Build() *BindingWatchRequest {
	m0 := &BindingWatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	x.xxx_hidden_SkipSnapshot = b.SkipSnapshot
	return m0
}

type BindingWatchResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*BindingWatchItem   `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BindingWatchResponse) Reset() {
	*x = BindingWatchResponse{}
	mi := &file_app_binding_svc_g_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingWatchResponse) ProtoMessage() {}

func (x *BindingWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingWatchResponse) GetItems() []*BindingWatchItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *BindingWatchResponse) SetItems(v []*BindingWatchItem) {
	x.xxx_hidden_Items = &v
}

type BindingWatchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// What changed, or -- in the first message -- everything that matches.
	Items []*BindingWatchItem
}

func (b0 BindingWatchResponse_builder) Build() *BindingWatchResponse {
	m0 := &BindingWatchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

type BindingWatchItem struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Value       *Binding               `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Action      string                 `protobuf:"bytes,3,opt,name=action"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BindingWatchItem) Reset() {
	*x = BindingWatchItem{}
	mi := &file_app_binding_svc_g_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingWatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingWatchItem) ProtoMessage() {}

func (x *BindingWatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_binding_svc_g_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingWatchItem) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *BindingWatchItem) GetValue() *Binding {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *BindingWatchItem) GetAction() string {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return ""
}

func (x *BindingWatchItem) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *BindingWatchItem) SetValue(v *Binding) {
	x.xxx_hidden_Value = v
}

func (x *BindingWatchItem) SetAction(v string) {
	x.xxx_hidden_Action = v
}

func (x *BindingWatchItem) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BindingWatchItem) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *BindingWatchItem) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *BindingWatchItem) ClearValue() {
	x.xxx_hidden_Value = nil
}

type BindingWatchItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Which row. Always said, since one that is gone still has to be named.
	Id []byte
	// The row as it is now, and **absent when it is no longer one this caller may
	// see**: erased, or moved out of the filters this stream named.
	//
	// Absence is the whole of how a removal is said. There is no flag for it, and
	// there is deliberately no way to tell those two apart -- a stream that
	// distinguished "erased" from "no longer yours" would be telling a caller
	// about rows that stopped being theirs, which is the thing the wall is for.
	//
	// It is only ever said about a row this stream has already carried. One that
	// never matched is not news.
	Value *Binding
	// The RPC that changed it, by the name gRPC knows it by. It is what the
	// caller of *that* RPC asked for and not the write it became, so an RPC
	// written by hand is here under its own name.
	//
	// Empty in the first message, which is not something anybody asked for -- it
	// is what is already there.
	Action string
}

func (b0 BindingWatchItem_builder) Build() *BindingWatchItem {
	m0 := &BindingWatchItem{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Action = b.Action
	return m0
}

var File_app_binding_svc_g_proto protoreflect.FileDescriptor

const file_app_binding_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x17app/binding_svc.g.proto\x12\x03app\x1a\x11app/binding.proto\x1a\x1dapp/payday/tenant_svc.g.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11patch/patch.proto\"\xa4\x03\n" +
	"\x11BindingAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12&\n" +
	"\x06tenant\x18\x02 \x01(\v2\x0e.app.TenantRefR\x06tenant\x12\x1b\n" +
	"\x05alias\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05alias\x12\x19\n" +
	"\x04desc\x18\x06 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04desc\x12\x1f\n" +
	"\asubject\x18\b \x01(\tB\x05\xaa\x01\x02\b\x02R\asubject\x12\x1b\n" +
	"\x05group\x18\t \x01(\tB\x05\xaa\x01\x02\b\x02R\x05group\x12\x19\n" +
	"\x04repo\x18\n" +
	" \x01(\tB\x05\xaa\x01\x02\b\x02R\x04repo\x12\x18\n" +
	"\aactions\x18\v \x03(\tR\aactions\x124\n" +
	"\x04when\x18\f \x03(\v2 .app.BindingAddRequest.WhenEntryR\x04when\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x1a7\n" +
	"\tWhenEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x11BindingGetRequest\x12!\n" +
	"\x03ref\x18\x01 \x01(\v2\x0f.app.BindingRefR\x03ref\x12*\n" +
	"\x06select\x18\x02 \x01(\v2\x12.app.BindingSelectR\x06select\"R\n" +
	"\n" +
	"BindingRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x12+\n" +
	"\x04slug\x18\x04 \x01(\v2\x15.app.BindingRefBySlugH\x00R\x04slugB\x05\n" +
	"\x03key\"P\n" +
	"\x10BindingRefBySlug\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12&\n" +
	"\x06tenant\x18\x02 \x01(\v2\x0e.app.TenantRefR\x06tenant\"\xcf\x02\n" +
	"\rBindingSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12)\n" +
	"\x06tenant\x18\x02 \x01(\v2\x11.app.TenantSelectR\x06tenant\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\bR\x05alias\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\bR\x04desc\x12\x18\n" +
	"\asubject\x18\b \x01(\bR\asubject\x12\x14\n" +
	"\x05group\x18\t \x01(\bR\x05group\x12\x12\n" +
	"\x04repo\x18\n" +
	" \x01(\bR\x04repo\x12\x18\n" +
	"\aactions\x18\v \x01(\bR\aactions\x12\x12\n" +
	"\x04when\x18\f \x01(\bR\x04when\x12\x1f\n" +
	"\vdate_erased\x18\x0e \x01(\bR\n" +
	"dateErased\x12!\n" +
	"\fdate_updated\x18\r \x01(\bR\vdateUpdated\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\"\x9e\x03\n" +
	"\x13BindingPatchRequest\x12!\n" +
	"\x03ref\x18\x01 \x01(\v2\x0f.app.BindingRefR\x03ref\x12\x14\n" +
	"\x05alias\x18\b \x01(\tR\x05alias\x12\x12\n" +
	"\x04desc\x18\f \x01(\tR\x04desc\x12\x18\n" +
	"\asubject\x18\x10 \x01(\tR\asubject\x12\x14\n" +
	"\x05group\x18\x12 \x01(\tR\x05group\x12\x12\n" +
	"\x04repo\x18\x14 \x01(\tR\x04repo\x12\x18\n" +
	"\aactions\x18\x16 \x03(\tR\aactions\x126\n" +
	"\x04when\x18\x18 \x03(\v2\".app.BindingPatchRequest.WhenEntryR\x04when\x12=\n" +
	"\fdate_updated\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\vdateUpdated\x12,\n" +
	"\x12date_updated_force\x18\x1b \x01(\bR\x10dateUpdatedForce\x1a7\n" +
	"\tWhenEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x13BindingApplyRequest\x12!\n" +
	"\x03ref\x18\x01 \x01(\v2\x0f.app.BindingRefR\x03ref\x12\"\n" +
	"\x05patch\x18\x02 \x01(\v2\f.patch.PatchR\x05patch\".\n" +
	"\x14BindingEraseResponse\x12\x16\n" +
	"\x06erased\x18\x01 \x01(\bR\x06erased\"z\n" +
	"\x12BindingListRequest\x12,\n" +
	"\afilters\x18\x01 \x03(\v2\x12.app.BindingFilterR\afilters\x12\x19\n" +
	"\x04size\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x02R\x04size\x12\x1b\n" +
	"\x05after\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05after\"T\n" +
	"\x13BindingListResponse\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.app.BindingR\x05items\x12\x19\n" +
	"\x04next\x18\x02 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04next\"\x8a\x01\n" +
	"\rBindingFilter\x12!\n" +
	"\x03ref\x18\x01 \x01(\v2\x0f.app.BindingRefR\x03ref\x12&\n" +
	"\x06tenant\x18\x02 \x01(\v2\x0e.app.TenantRefR\x06tenant\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\"o\n" +
	"\x13BindingWatchRequest\x12,\n" +
	"\afilters\x18\x01 \x03(\v2\x12.app.BindingFilterR\afilters\x12*\n" +
	"\rskip_snapshot\x18\x02 \x01(\bB\x05\xaa\x01\x02\b\x02R\fskipSnapshot\"C\n" +
	"\x14BindingWatchResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.app.BindingWatchItemR\x05items\"e\n" +
	"\x10BindingWatchItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.app.BindingR\x05value\x12\x1d\n" +
	"\x06action\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x06action2\xfc\x02\n" +
	"\x0eBindingService\x12+\n" +
	"\x03Add\x12\x16.app.BindingAddRequest\x1a\f.app.Binding\x12+\n" +
	"\x03Get\x12\x16.app.BindingGetRequest\x1a\f.app.Binding\x12/\n" +
	"\x05Patch\x12\x18.app.BindingPatchRequest\x1a\f.app.Binding\x12/\n" +
	"\x05Apply\x12\x18.app.BindingApplyRequest\x1a\f.app.Binding\x123\n" +
	"\x05Erase\x12\x0f.app.BindingRef\x1a\x19.app.BindingEraseResponse\x129\n" +
	"\x04List\x12\x17.app.BindingListRequest\x1a\x18.app.BindingListResponse\x12>\n" +
	"\x05Watch\x12\x18.app.BindingWatchRequest\x1a\x19.app.BindingWatchResponse0\x01B\x1cZ\x1agithub.com/lesomnus/cr/apib\beditionsp\xe8\a"

var file_app_binding_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_app_binding_svc_g_proto_goTypes = []any{
	(*BindingAddRequest)(nil),     // 0: app.BindingAddRequest
	(*BindingGetRequest)(nil),     // 1: app.BindingGetRequest
	(*BindingRef)(nil),            // 2: app.BindingRef
	(*BindingRefBySlug)(nil),      // 3: app.BindingRefBySlug
	(*BindingSelect)(nil),         // 4: app.BindingSelect
	(*BindingPatchRequest)(nil),   // 5: app.BindingPatchRequest
	(*BindingApplyRequest)(nil),   // 6: app.BindingApplyRequest
	(*BindingEraseResponse)(nil),  // 7: app.BindingEraseResponse
	(*BindingListRequest)(nil),    // 8: app.BindingListRequest
	(*BindingListResponse)(nil),   // 9: app.BindingListResponse
	(*BindingFilter)(nil),         // 10: app.BindingFilter
	(*BindingWatchRequest)(nil),   // 11: app.BindingWatchRequest
	(*BindingWatchResponse)(nil),  // 12: app.BindingWatchResponse
	(*BindingWatchItem)(nil),      // 13: app.BindingWatchItem
	nil,                           // 14: app.BindingAddRequest.WhenEntry
	nil,                           // 15: app.BindingPatchRequest.WhenEntry
	(*TenantRef)(nil),             // 16: app.TenantRef
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*TenantSelect)(nil),          // 18: app.TenantSelect
	(*patchpb.Patch)(nil),         // 19: patch.Patch
	(*Binding)(nil),               // 20: app.Binding
}
var file_app_binding_svc_g_proto_depIdxs = []int32{
	16, // 0: app.BindingAddRequest.tenant:type_name -> app.TenantRef
	14, // 1: app.BindingAddRequest.when:type_name -> app.BindingAddRequest.WhenEntry
	17, // 2: app.BindingAddRequest.date_created:type_name -> google.protobuf.Timestamp
	2,  // 3: app.BindingGetRequest.ref:type_name -> app.BindingRef
	4,  // 4: app.BindingGetRequest.select:type_name -> app.BindingSelect
	3,  // 5: app.BindingRef.slug:type_name -> app.BindingRefBySlug
	16, // 6: app.BindingRefBySlug.tenant:type_name -> app.TenantRef
	18, // 7: app.BindingSelect.tenant:type_name -> app.TenantSelect
	2,  // 8: app.BindingPatchRequest.ref:type_name -> app.BindingRef
	15, // 9: app.BindingPatchRequest.when:type_name -> app.BindingPatchRequest.WhenEntry
	17, // 10: app.BindingPatchRequest.date_updated:type_name -> google.protobuf.Timestamp
	2,  // 11: app.BindingApplyRequest.ref:type_name -> app.BindingRef
	19, // 12: app.BindingApplyRequest.patch:type_name -> patch.Patch
	10, // 13: app.BindingListRequest.filters:type_name -> app.BindingFilter
	20, // 14: app.BindingListResponse.items:type_name -> app.Binding
	2,  // 15: app.BindingFilter.ref:type_name -> app.BindingRef
	16, // 16: app.BindingFilter.tenant:type_name -> app.TenantRef
	10, // 17: app.BindingWatchRequest.filters:type_name -> app.BindingFilter
	13, // 18: app.BindingWatchResponse.items:type_name -> app.BindingWatchItem
	20, // 19: app.BindingWatchItem.value:type_name -> app.Binding
	0,  // 20: app.BindingService.Add:input_type -> app.BindingAddRequest
	1,  // 21: app.BindingService.Get:input_type -> app.BindingGetRequest
	5,  // 22: app.BindingService.Patch:input_type -> app.BindingPatchRequest
	6,  // 23: app.BindingService.Apply:input_type -> app.BindingApplyRequest
	2,  // 24: app.BindingService.Erase:input_type -> app.BindingRef
	8,  // 25: app.BindingService.List:input_type -> app.BindingListRequest
	11, // 26: app.BindingService.Watch:input_type -> app.BindingWatchRequest
	20, // 27: app.BindingService.Add:output_type -> app.Binding
	20, // 28: app.BindingService.Get:output_type -> app.Binding
	20, // 29: app.BindingService.Patch:output_type -> app.Binding
	20, // 30: app.BindingService.Apply:output_type -> app.Binding
	7,  // 31: app.BindingService.Erase:output_type -> app.BindingEraseResponse
	9,  // 32: app.BindingService.List:output_type -> app.BindingListResponse
	12, // 33: app.BindingService.Watch:output_type -> app.BindingWatchResponse
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_app_binding_svc_g_proto_init() }
func file_app_binding_svc_g_proto_init() {
	if File_app_binding_svc_g_proto != nil {
		return
	}
	file_app_binding_proto_init()
	file_app_payday_tenant_svc_g_proto_init()
	file_app_binding_svc_g_proto_msgTypes[2].OneofWrappers = []any{
		(*bindingRef_Id)(nil),
		(*bindingRef_Slug)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_binding_svc_g_proto_rawDesc), len(file_app_binding_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_binding_svc_g_proto_goTypes,
		DependencyIndexes: file_app_binding_svc_g_proto_depIdxs,
		MessageInfos:      file_app_binding_svc_g_proto_msgTypes,
	}.Build()
	File_app_binding_svc_g_proto = out.File
	file_app_binding_svc_g_proto_goTypes = nil
	file_app_binding_svc_g_proto_depIdxs = nil
}
