// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: app/gc_run.proto

package api

import (
	_ "github.com/lesomnus/payday/pdpb"
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GcRun is one run of garbage collection and what it did: the record behind
// `GET /admin/gc/<id>`, and the history of a deployment's collections.
type GcRun struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id           []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Kind         string                 `protobuf:"bytes,8,opt,name=kind"`
	xxx_hidden_Trigger      string                 `protobuf:"bytes,9,opt,name=trigger"`
	xxx_hidden_State        string                 `protobuf:"bytes,10,opt,name=state"`
	xxx_hidden_Error        string                 `protobuf:"bytes,11,opt,name=error"`
	xxx_hidden_Stages       int64                  `protobuf:"varint,12,opt,name=stages"`
	xxx_hidden_Tags         int64                  `protobuf:"varint,16,opt,name=tags"`
	xxx_hidden_Manifests    int64                  `protobuf:"varint,17,opt,name=manifests"`
	xxx_hidden_Repositories int64                  `protobuf:"varint,18,opt,name=repositories"`
	xxx_hidden_Blobs        int64                  `protobuf:"varint,19,opt,name=blobs"`
	xxx_hidden_Bytes        int64                  `protobuf:"varint,20,opt,name=bytes"`
	xxx_hidden_Missing      []string               `protobuf:"bytes,21,rep,name=missing"`
	xxx_hidden_DateFinished *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=date_finished,json=dateFinished"`
	xxx_hidden_DateUpdated  *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateCreated  *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GcRun) Reset() {
	*x = GcRun{}
	mi := &file_app_gc_run_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcRun) ProtoMessage() {}

func (x *GcRun) ProtoReflect() protoreflect.Message {
	mi := &file_app_gc_run_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GcRun) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *GcRun) GetKind() string {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return ""
}

func (x *GcRun) GetTrigger() string {
	if x != nil {
		return x.xxx_hidden_Trigger
	}
	return ""
}

func (x *GcRun) GetState() string {
	if x != nil {
		return x.xxx_hidden_State
	}
	return ""
}

func (x *GcRun) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *GcRun) GetStages() int64 {
	if x != nil {
		return x.xxx_hidden_Stages
	}
	return 0
}

func (x *GcRun) GetTags() int64 {
	if x != nil {
		return x.xxx_hidden_Tags
	}
	return 0
}

func (x *GcRun) GetManifests() int64 {
	if x != nil {
		return x.xxx_hidden_Manifests
	}
	return 0
}

func (x *GcRun) GetRepositories() int64 {
	if x != nil {
		return x.xxx_hidden_Repositories
	}
	return 0
}

func (x *GcRun) GetBlobs() int64 {
	if x != nil {
		return x.xxx_hidden_Blobs
	}
	return 0
}

func (x *GcRun) GetBytes() int64 {
	if x != nil {
		return x.xxx_hidden_Bytes
	}
	return 0
}

func (x *GcRun) GetMissing() []string {
	if x != nil {
		return x.xxx_hidden_Missing
	}
	return nil
}

func (x *GcRun) GetDateFinished() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateFinished
	}
	return nil
}

func (x *GcRun) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *GcRun) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *GcRun) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *GcRun) SetKind(v string) {
	x.xxx_hidden_Kind = v
}

func (x *GcRun) SetTrigger(v string) {
	x.xxx_hidden_Trigger = v
}

func (x *GcRun) SetState(v string) {
	x.xxx_hidden_State = v
}

func (x *GcRun) SetError(v string) {
	x.xxx_hidden_Error = v
}

func (x *GcRun) SetStages(v int64) {
	x.xxx_hidden_Stages = v
}

func (x *GcRun) SetTags(v int64) {
	x.xxx_hidden_Tags = v
}

func (x *GcRun) SetManifests(v int64) {
	x.xxx_hidden_Manifests = v
}

func (x *GcRun) SetRepositories(v int64) {
	x.xxx_hidden_Repositories = v
}

func (x *GcRun) SetBlobs(v int64) {
	x.xxx_hidden_Blobs = v
}

func (x *GcRun) SetBytes(v int64) {
	x.xxx_hidden_Bytes = v
}

func (x *GcRun) SetMissing(v []string) {
	x.xxx_hidden_Missing = v
}

func (x *GcRun) SetDateFinished(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateFinished = v
}

func (x *GcRun) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *GcRun) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *GcRun) HasDateFinished() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateFinished != nil
}

func (x *GcRun) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *GcRun) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *GcRun) ClearDateFinished() {
	x.xxx_hidden_DateFinished = nil
}

func (x *GcRun) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *GcRun) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type GcRun_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id []byte
	// online, which runs on its own ticker, or full, which also sweeps every
	// repository's store.
	Kind string
	// schedule, admin or cli: what started it.
	Trigger string
	// running, done or failed. A run whose process died stays running; the
	// time it started says how stale that is.
	State string
	// The first failure, when there was one.
	Error        string
	Stages       int64
	Tags         int64
	Manifests    int64
	Repositories int64
	Blobs        int64
	Bytes        int64
	// `repo@digest` of the manifests the index has and the store does not.
	Missing      []string
	DateFinished *timestamppb.Timestamp
	DateUpdated  *timestamppb.Timestamp
	DateCreated  *timestamppb.Timestamp
}

func (b0 GcRun_builder) Build() *GcRun {
	m0 := &GcRun{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Kind = b.Kind
	x.xxx_hidden_Trigger = b.Trigger
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Error = b.Error
	x.xxx_hidden_Stages = b.Stages
	x.xxx_hidden_Tags = b.Tags
	x.xxx_hidden_Manifests = b.Manifests
	x.xxx_hidden_Repositories = b.Repositories
	x.xxx_hidden_Blobs = b.Blobs
	x.xxx_hidden_Bytes = b.Bytes
	x.xxx_hidden_Missing = b.Missing
	x.xxx_hidden_DateFinished = b.DateFinished
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_app_gc_run_proto protoreflect.FileDescriptor

const file_app_gc_run_proto_rawDesc = "" +
	"\n" +
	"\x10app/gc_run.proto\x12\x03app\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\fpayday.proto\"\x8a\x05\n" +
	"\x05GcRun\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12\x12\n" +
	"\x04kind\x18\b \x01(\tR\x04kind\x12\x18\n" +
	"\atrigger\x18\t \x01(\tR\atrigger\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\tR\x05state\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\x12\x16\n" +
	"\x06stages\x18\f \x01(\x03R\x06stages\x12\x12\n" +
	"\x04tags\x18\x10 \x01(\x03R\x04tags\x12\x1c\n" +
	"\tmanifests\x18\x11 \x01(\x03R\tmanifests\x12\"\n" +
	"\frepositories\x18\x12 \x01(\x03R\frepositories\x12\x14\n" +
	"\x05blobs\x18\x13 \x01(\x03R\x05blobs\x12\x14\n" +
	"\x05bytes\x18\x14 \x01(\x03R\x05bytes\x12\x18\n" +
	"\amissing\x18\x15 \x03(\tR\amissing\x12G\n" +
	"\rdate_finished\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xea\x82\x16\x028\x01R\fdateFinished\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated:{\xca\xfc\x155\x12\x11\x10\x01\x82\x01\x02\b\x01\x92\x01\x02\b\x01\x9a\x01\x02\b\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x8a\xbb\x16>\b\x0e22\n" +
	"\x12\n" +
	"\x0e\n" +
	"\fdate_created\x10\x01\n" +
	"\b\n" +
	"\x04\n" +
	"\x02id\x10\x01\x1a\x05\n" +
	"\x03ref\x1a\a\n" +
	"\x05state \x14(d:\x00B\x02\n" +
	"\x00*\x00B!Z\x1agithub.com/lesomnus/cr/api\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_app_gc_run_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_gc_run_proto_goTypes = []any{
	(*GcRun)(nil),                 // 0: app.GcRun
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_app_gc_run_proto_depIdxs = []int32{
	1, // 0: app.GcRun.date_finished:type_name -> google.protobuf.Timestamp
	1, // 1: app.GcRun.date_updated:type_name -> google.protobuf.Timestamp
	1, // 2: app.GcRun.date_created:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_gc_run_proto_init() }
func file_app_gc_run_proto_init() {
	if File_app_gc_run_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_gc_run_proto_rawDesc), len(file_app_gc_run_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_gc_run_proto_goTypes,
		DependencyIndexes: file_app_gc_run_proto_depIdxs,
		MessageInfos:      file_app_gc_run_proto_msgTypes,
	}.Build()
	File_app_gc_run_proto = out.File
	file_app_gc_run_proto_goTypes = nil
	file_app_gc_run_proto_depIdxs = nil
}
