// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package api

import (
	bytes "bytes"
)

func (x *GcRunRef) Pick() *GcRunGetRequest {
	return GcRunGetRequest_builder{Ref: x}.Build()
}

func (x *GcRun) Ref() *GcRunRef {
	if v := x.GetId(); len(v) > 0 {
		return GcRunById(v)
	}

	return nil
}

func (x *GcRun) Pick() *GcRunGetRequest {
	return x.Ref().Pick()
}

func (x *GcRunRef) Picks(v *GcRun) bool {
	switch x.WhichKey() {
	case GcRunRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *GcRunGetRequest) WithSelect(f func(s *GcRunSelect)) *GcRunGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&GcRunSelect{})
	}
	f(x.GetSelect())
	return x
}

func GcRunById(v []byte) *GcRunRef {
	x := &GcRunRef{}
	x.SetId(v)
	return x
}

func GcRunGetById(v []byte) *GcRunGetRequest {
	return GcRunGetRequest_builder{Ref: GcRunById(v)}.Build()
}
