// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: app/manifest.proto

package api

import (
	_ "github.com/lesomnus/payday/pdpb"
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Manifest is one manifest a repository holds, named by its digest.
//
// The bytes are in flob; this row is what the registry needs to answer without
// opening them: the media type for `Content-Type`, and the subject, artifact
// type, size and annotations a referrers response is built from.
type Manifest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id           []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Repo         string                 `protobuf:"bytes,8,opt,name=repo"`
	xxx_hidden_Digest       string                 `protobuf:"bytes,9,opt,name=digest"`
	xxx_hidden_MediaType    string                 `protobuf:"bytes,10,opt,name=media_type,json=mediaType"`
	xxx_hidden_ArtifactType string                 `protobuf:"bytes,11,opt,name=artifact_type,json=artifactType"`
	xxx_hidden_Subject      string                 `protobuf:"bytes,12,opt,name=subject"`
	xxx_hidden_Size         int64                  `protobuf:"varint,16,opt,name=size"`
	xxx_hidden_Annotations  map[string]string      `protobuf:"bytes,17,rep,name=annotations" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DatePulled   *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=date_pulled,json=datePulled"`
	xxx_hidden_DateUpdated  *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateCreated  *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_app_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_app_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Manifest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Manifest) GetRepo() string {
	if x != nil {
		return x.xxx_hidden_Repo
	}
	return ""
}

func (x *Manifest) GetDigest() string {
	if x != nil {
		return x.xxx_hidden_Digest
	}
	return ""
}

func (x *Manifest) GetMediaType() string {
	if x != nil {
		return x.xxx_hidden_MediaType
	}
	return ""
}

func (x *Manifest) GetArtifactType() string {
	if x != nil {
		return x.xxx_hidden_ArtifactType
	}
	return ""
}

func (x *Manifest) GetSubject() string {
	if x != nil {
		return x.xxx_hidden_Subject
	}
	return ""
}

func (x *Manifest) GetSize() int64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *Manifest) GetAnnotations() map[string]string {
	if x != nil {
		return x.xxx_hidden_Annotations
	}
	return nil
}

func (x *Manifest) GetDatePulled() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DatePulled
	}
	return nil
}

func (x *Manifest) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *Manifest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Manifest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Manifest) SetRepo(v string) {
	x.xxx_hidden_Repo = v
}

func (x *Manifest) SetDigest(v string) {
	x.xxx_hidden_Digest = v
}

func (x *Manifest) SetMediaType(v string) {
	x.xxx_hidden_MediaType = v
}

func (x *Manifest) SetArtifactType(v string) {
	x.xxx_hidden_ArtifactType = v
}

func (x *Manifest) SetSubject(v string) {
	x.xxx_hidden_Subject = v
}

func (x *Manifest) SetSize(v int64) {
	x.xxx_hidden_Size = v
}

func (x *Manifest) SetAnnotations(v map[string]string) {
	x.xxx_hidden_Annotations = v
}

func (x *Manifest) SetDatePulled(v *timestamppb.Timestamp) {
	x.xxx_hidden_DatePulled = v
}

func (x *Manifest) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *Manifest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Manifest) HasDatePulled() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DatePulled != nil
}

func (x *Manifest) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *Manifest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Manifest) ClearDatePulled() {
	x.xxx_hidden_DatePulled = nil
}

func (x *Manifest) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *Manifest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Manifest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        []byte
	Repo      string
	Digest    string
	MediaType string
	// The manifest's `artifactType`, or its config's media type when it has
	// none, which is what the referrers API reports.
	ArtifactType string
	// The digest in the manifest's `subject`, or empty.
	Subject     string
	Size        int64
	Annotations map[string]string
	// Written in batches, after the fact; see `index.Pulled`.
	DatePulled  *timestamppb.Timestamp
	DateUpdated *timestamppb.Timestamp
	DateCreated *timestamppb.Timestamp
}

func (b0 Manifest_builder) Build() *Manifest {
	m0 := &Manifest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Repo = b.Repo
	x.xxx_hidden_Digest = b.Digest
	x.xxx_hidden_MediaType = b.MediaType
	x.xxx_hidden_ArtifactType = b.ArtifactType
	x.xxx_hidden_Subject = b.Subject
	x.xxx_hidden_Size = b.Size
	x.xxx_hidden_Annotations = b.Annotations
	x.xxx_hidden_DatePulled = b.DatePulled
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_app_manifest_proto protoreflect.FileDescriptor

const file_app_manifest_proto_rawDesc = "" +
	"\n" +
	"\x12app/manifest.proto\x12\x03app\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\fpayday.proto\"\xa6\x06\n" +
	"\bManifest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12\x1a\n" +
	"\x04repo\x18\b \x01(\tB\x06\xea\x82\x16\x02@\x01R\x04repo\x12\x1e\n" +
	"\x06digest\x18\t \x01(\tB\x06\xea\x82\x16\x02@\x01R\x06digest\x12%\n" +
	"\n" +
	"media_type\x18\n" +
	" \x01(\tB\x06\xea\x82\x16\x02@\x01R\tmediaType\x12+\n" +
	"\rartifact_type\x18\v \x01(\tB\x06\xea\x82\x16\x02@\x01R\fartifactType\x12 \n" +
	"\asubject\x18\f \x01(\tB\x06\xea\x82\x16\x02@\x01R\asubject\x12\x1a\n" +
	"\x04size\x18\x10 \x01(\x03B\x06\xea\x82\x16\x02@\x01R\x04size\x12@\n" +
	"\vannotations\x18\x11 \x03(\v2\x1e.app.Manifest.AnnotationsEntryR\vannotations\x12C\n" +
	"\vdate_pulled\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xea\x82\x16\x028\x01R\n" +
	"datePulled\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\xd5\x01\xca\xfc\x15\x7f\x12\x11\x10\x01\x82\x01\x02\b\x01\x92\x01\x02\b\x01\x9a\x01\x02\b\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x1a#\x12\tby_digest\x1a\b\n" +
	"\x04repo\x10\b\x1a\n" +
	"\n" +
	"\x06digest\x10\t0\x01\x1a#\x12\n" +
	"by_subject\x1a\b\n" +
	"\x04repo\x10\b\x1a\v\n" +
	"\asubject\x10\f\x8a\xbb\x16N\b\t2B\n" +
	"\x10\n" +
	"\x0e\n" +
	"\fdate_created\n" +
	"\x06\n" +
	"\x04\n" +
	"\x02id\x1a\x05\n" +
	"\x03ref\x1a\x06\n" +
	"\x04repo\x1a\b\n" +
	"\x06digest\x1a\t\n" +
	"\asubject \x14(d:\x00B\x02\n" +
	"\x00*\x00B!Z\x1agithub.com/lesomnus/cr/api\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_app_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_manifest_proto_goTypes = []any{
	(*Manifest)(nil),              // 0: app.Manifest
	nil,                           // 1: app.Manifest.AnnotationsEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_app_manifest_proto_depIdxs = []int32{
	1, // 0: app.Manifest.annotations:type_name -> app.Manifest.AnnotationsEntry
	2, // 1: app.Manifest.date_pulled:type_name -> google.protobuf.Timestamp
	2, // 2: app.Manifest.date_updated:type_name -> google.protobuf.Timestamp
	2, // 3: app.Manifest.date_created:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_app_manifest_proto_init() }
func file_app_manifest_proto_init() {
	if File_app_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_manifest_proto_rawDesc), len(file_app_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_manifest_proto_goTypes,
		DependencyIndexes: file_app_manifest_proto_depIdxs,
		MessageInfos:      file_app_manifest_proto_msgTypes,
	}.Build()
	File_app_manifest_proto = out.File
	file_app_manifest_proto_goTypes = nil
	file_app_manifest_proto_depIdxs = nil
}
