// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package api

import (
	bytes "bytes"
)

func (x *ManifestRef) Pick() *ManifestGetRequest {
	return ManifestGetRequest_builder{Ref: x}.Build()
}

func (x *Manifest) Ref() *ManifestRef {
	if v := x.GetId(); len(v) > 0 {
		return ManifestById(v)
	}
	{
		v1 := x.GetRepo()
		v2 := x.GetDigest()
		if len(v1) > 0 && len(v2) > 0 {
			return ManifestByByDigest(v1, v2)
		}
	}

	return nil
}

func (x *Manifest) Pick() *ManifestGetRequest {
	return x.Ref().Pick()
}

func (x *ManifestRef) Picks(v *Manifest) bool {
	switch x.WhichKey() {
	case ManifestRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case ManifestRef_ByDigest_case:
		x := x.GetByDigest()
		return (x.GetRepo() == v.GetRepo()) &&
			(x.GetDigest() == v.GetDigest())
	default:
		return false
	}
}

func (x *ManifestGetRequest) WithSelect(f func(s *ManifestSelect)) *ManifestGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&ManifestSelect{})
	}
	f(x.GetSelect())
	return x
}

func ManifestById(v []byte) *ManifestRef {
	x := &ManifestRef{}
	x.SetId(v)
	return x
}

func ManifestGetById(v []byte) *ManifestGetRequest {
	return ManifestGetRequest_builder{Ref: ManifestById(v)}.Build()
}

func ManifestByByDigest(repo string, digest string) *ManifestRef {
	x := &ManifestRefByByDigest{}
	x.SetRepo(repo)
	x.SetDigest(digest)
	return ManifestRef_builder{ByDigest: x}.Build()
}

func ManifestGetByByDigest(repo string, digest string) *ManifestGetRequest {
	return ManifestGetRequest_builder{Ref: ManifestByByDigest(repo, digest)}.Build()
}
