// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package api

import (
	bytes "bytes"
)

func (x *ReferrersSnapshotRef) Pick() *ReferrersSnapshotGetRequest {
	return ReferrersSnapshotGetRequest_builder{Ref: x}.Build()
}

func (x *ReferrersSnapshot) Ref() *ReferrersSnapshotRef {
	if v := x.GetId(); len(v) > 0 {
		return ReferrersSnapshotById(v)
	}
	{
		v1 := x.GetRepo()
		v2 := x.GetSubject()
		if len(v1) > 0 && len(v2) > 0 {
			return ReferrersSnapshotByBySubject(v1, v2)
		}
	}

	return nil
}

func (x *ReferrersSnapshot) Pick() *ReferrersSnapshotGetRequest {
	return x.Ref().Pick()
}

func (x *ReferrersSnapshotRef) Picks(v *ReferrersSnapshot) bool {
	switch x.WhichKey() {
	case ReferrersSnapshotRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case ReferrersSnapshotRef_BySubject_case:
		x := x.GetBySubject()
		return (x.GetRepo() == v.GetRepo()) &&
			(x.GetSubject() == v.GetSubject())
	default:
		return false
	}
}

func (x *ReferrersSnapshotGetRequest) WithSelect(f func(s *ReferrersSnapshotSelect)) *ReferrersSnapshotGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&ReferrersSnapshotSelect{})
	}
	f(x.GetSelect())
	return x
}

func ReferrersSnapshotById(v []byte) *ReferrersSnapshotRef {
	x := &ReferrersSnapshotRef{}
	x.SetId(v)
	return x
}

func ReferrersSnapshotGetById(v []byte) *ReferrersSnapshotGetRequest {
	return ReferrersSnapshotGetRequest_builder{Ref: ReferrersSnapshotById(v)}.Build()
}

func ReferrersSnapshotByBySubject(repo string, subject string) *ReferrersSnapshotRef {
	x := &ReferrersSnapshotRefByBySubject{}
	x.SetRepo(repo)
	x.SetSubject(subject)
	return ReferrersSnapshotRef_builder{BySubject: x}.Build()
}

func ReferrersSnapshotGetByBySubject(repo string, subject string) *ReferrersSnapshotGetRequest {
	return ReferrersSnapshotGetRequest_builder{Ref: ReferrersSnapshotByBySubject(repo, subject)}.Build()
}
