// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: app/referrers_snapshot_svc.g.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReferrersSnapshotGetRequest struct {
	state             protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Ref    *ReferrersSnapshotRef    `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *ReferrersSnapshotSelect `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReferrersSnapshotGetRequest) Reset() {
	*x = ReferrersSnapshotGetRequest{}
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferrersSnapshotGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferrersSnapshotGetRequest) ProtoMessage() {}

func (x *ReferrersSnapshotGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReferrersSnapshotGetRequest) GetRef() *ReferrersSnapshotRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *ReferrersSnapshotGetRequest) GetSelect() *ReferrersSnapshotSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *ReferrersSnapshotGetRequest) SetRef(v *ReferrersSnapshotRef) {
	x.xxx_hidden_Ref = v
}

func (x *ReferrersSnapshotGetRequest) SetSelect(v *ReferrersSnapshotSelect) {
	x.xxx_hidden_Select = v
}

func (x *ReferrersSnapshotGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *ReferrersSnapshotGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *ReferrersSnapshotGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *ReferrersSnapshotGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type ReferrersSnapshotGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *ReferrersSnapshotRef
	Select *ReferrersSnapshotSelect
}

func (b0 ReferrersSnapshotGetRequest_builder) Build() *ReferrersSnapshotGetRequest {
	m0 := &ReferrersSnapshotGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type ReferrersSnapshotRef struct {
	state          protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Key isReferrersSnapshotRef_Key `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReferrersSnapshotRef) Reset() {
	*x = ReferrersSnapshotRef{}
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferrersSnapshotRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferrersSnapshotRef) ProtoMessage() {}

func (x *ReferrersSnapshotRef) ProtoReflect() protoreflect.Message {
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReferrersSnapshotRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*referrersSnapshotRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *ReferrersSnapshotRef) GetBySubject() *ReferrersSnapshotRefByBySubject {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*referrersSnapshotRef_BySubject); ok {
			return x.BySubject
		}
	}
	return nil
}

func (x *ReferrersSnapshotRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &referrersSnapshotRef_Id{v}
}

func (x *ReferrersSnapshotRef) SetBySubject(v *ReferrersSnapshotRefByBySubject) {
	if v == nil {
		x.xxx_hidden_Key = nil
		return
	}
	x.xxx_hidden_Key = &referrersSnapshotRef_BySubject{v}
}

func (x *ReferrersSnapshotRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *ReferrersSnapshotRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*referrersSnapshotRef_Id)
	return ok
}

func (x *ReferrersSnapshotRef) HasBySubject() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*referrersSnapshotRef_BySubject)
	return ok
}

func (x *ReferrersSnapshotRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *ReferrersSnapshotRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*referrersSnapshotRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *ReferrersSnapshotRef) ClearBySubject() {
	if _, ok := x.xxx_hidden_Key.(*referrersSnapshotRef_BySubject); ok {
		x.xxx_hidden_Key = nil
	}
}

const ReferrersSnapshotRef_Key_not_set_case case_ReferrersSnapshotRef_Key = 0
const ReferrersSnapshotRef_Id_case case_ReferrersSnapshotRef_Key = 1
const ReferrersSnapshotRef_BySubject_case case_ReferrersSnapshotRef_Key = 8

func (x *ReferrersSnapshotRef) WhichKey() case_ReferrersSnapshotRef_Key {
	if x == nil {
		return ReferrersSnapshotRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *referrersSnapshotRef_Id:
		return ReferrersSnapshotRef_Id_case
	case *referrersSnapshotRef_BySubject:
		return ReferrersSnapshotRef_BySubject_case
	default:
		return ReferrersSnapshotRef_Key_not_set_case
	}
}

type ReferrersSnapshotRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id        []byte
	BySubject *ReferrersSnapshotRefByBySubject
	// -- end of xxx_hidden_Key
}

func (b0 ReferrersSnapshotRef_builder) Build() *ReferrersSnapshotRef {
	m0 := &ReferrersSnapshotRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &referrersSnapshotRef_Id{b.Id}
	}
	if b.BySubject != nil {
		x.xxx_hidden_Key = &referrersSnapshotRef_BySubject{b.BySubject}
	}
	return m0
}

type case_ReferrersSnapshotRef_Key protoreflect.FieldNumber

func (x case_ReferrersSnapshotRef_Key) String() string {
	md := file_app_referrers_snapshot_svc_g_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isReferrersSnapshotRef_Key interface {
	isReferrersSnapshotRef_Key()
}

type referrersSnapshotRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type referrersSnapshotRef_BySubject struct {
	BySubject *ReferrersSnapshotRefByBySubject `protobuf:"bytes,8,opt,name=by_subject,json=bySubject,oneof"`
}

func (*referrersSnapshotRef_Id) isReferrersSnapshotRef_Key() {}

func (*referrersSnapshotRef_BySubject) isReferrersSnapshotRef_Key() {}

type ReferrersSnapshotRefByBySubject struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Repo        *string                `protobuf:"bytes,8,opt,name=repo"`
	xxx_hidden_Subject     *string                `protobuf:"bytes,9,opt,name=subject"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReferrersSnapshotRefByBySubject) Reset() {
	*x = ReferrersSnapshotRefByBySubject{}
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferrersSnapshotRefByBySubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferrersSnapshotRefByBySubject) ProtoMessage() {}

func (x *ReferrersSnapshotRefByBySubject) ProtoReflect() protoreflect.Message {
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReferrersSnapshotRefByBySubject) GetRepo() string {
	if x != nil {
		if x.xxx_hidden_Repo != nil {
			return *x.xxx_hidden_Repo
		}
		return ""
	}
	return ""
}

func (x *ReferrersSnapshotRefByBySubject) GetSubject() string {
	if x != nil {
		if x.xxx_hidden_Subject != nil {
			return *x.xxx_hidden_Subject
		}
		return ""
	}
	return ""
}

func (x *ReferrersSnapshotRefByBySubject) SetRepo(v string) {
	x.xxx_hidden_Repo = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ReferrersSnapshotRefByBySubject) SetSubject(v string) {
	x.xxx_hidden_Subject = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ReferrersSnapshotRefByBySubject) HasRepo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReferrersSnapshotRefByBySubject) HasSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReferrersSnapshotRefByBySubject) ClearRepo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Repo = nil
}

func (x *ReferrersSnapshotRefByBySubject) ClearSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Subject = nil
}

type ReferrersSnapshotRefByBySubject_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Repo    *string
	Subject *string
}

func (b0 ReferrersSnapshotRefByBySubject_builder) Build() *ReferrersSnapshotRefByBySubject {
	m0 := &ReferrersSnapshotRefByBySubject{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Repo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Repo = b.Repo
	}
	if b.Subject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Subject = b.Subject
	}
	return m0
}

type ReferrersSnapshotSelect struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All          bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Repo         bool                   `protobuf:"varint,8,opt,name=repo"`
	xxx_hidden_Subject      bool                   `protobuf:"varint,9,opt,name=subject"`
	xxx_hidden_Supported    bool                   `protobuf:"varint,10,opt,name=supported"`
	xxx_hidden_Descriptors  bool                   `protobuf:"varint,11,opt,name=descriptors"`
	xxx_hidden_DateObserved bool                   `protobuf:"varint,12,opt,name=date_observed,json=dateObserved"`
	xxx_hidden_DateUpdated  bool                   `protobuf:"varint,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateCreated  bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ReferrersSnapshotSelect) Reset() {
	*x = ReferrersSnapshotSelect{}
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferrersSnapshotSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferrersSnapshotSelect) ProtoMessage() {}

func (x *ReferrersSnapshotSelect) ProtoReflect() protoreflect.Message {
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReferrersSnapshotSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *ReferrersSnapshotSelect) GetRepo() bool {
	if x != nil {
		return x.xxx_hidden_Repo
	}
	return false
}

func (x *ReferrersSnapshotSelect) GetSubject() bool {
	if x != nil {
		return x.xxx_hidden_Subject
	}
	return false
}

func (x *ReferrersSnapshotSelect) GetSupported() bool {
	if x != nil {
		return x.xxx_hidden_Supported
	}
	return false
}

func (x *ReferrersSnapshotSelect) GetDescriptors() bool {
	if x != nil {
		return x.xxx_hidden_Descriptors
	}
	return false
}

func (x *ReferrersSnapshotSelect) GetDateObserved() bool {
	if x != nil {
		return x.xxx_hidden_DateObserved
	}
	return false
}

func (x *ReferrersSnapshotSelect) GetDateUpdated() bool {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return false
}

func (x *ReferrersSnapshotSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *ReferrersSnapshotSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *ReferrersSnapshotSelect) SetRepo(v bool) {
	x.xxx_hidden_Repo = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *ReferrersSnapshotSelect) SetSubject(v bool) {
	x.xxx_hidden_Subject = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *ReferrersSnapshotSelect) SetSupported(v bool) {
	x.xxx_hidden_Supported = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *ReferrersSnapshotSelect) SetDescriptors(v bool) {
	x.xxx_hidden_Descriptors = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *ReferrersSnapshotSelect) SetDateObserved(v bool) {
	x.xxx_hidden_DateObserved = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *ReferrersSnapshotSelect) SetDateUpdated(v bool) {
	x.xxx_hidden_DateUpdated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *ReferrersSnapshotSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *ReferrersSnapshotSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReferrersSnapshotSelect) HasRepo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReferrersSnapshotSelect) HasSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ReferrersSnapshotSelect) HasSupported() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ReferrersSnapshotSelect) HasDescriptors() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ReferrersSnapshotSelect) HasDateObserved() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ReferrersSnapshotSelect) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ReferrersSnapshotSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ReferrersSnapshotSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *ReferrersSnapshotSelect) ClearRepo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Repo = false
}

func (x *ReferrersSnapshotSelect) ClearSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Subject = false
}

func (x *ReferrersSnapshotSelect) ClearSupported() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Supported = false
}

func (x *ReferrersSnapshotSelect) ClearDescriptors() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Descriptors = false
}

func (x *ReferrersSnapshotSelect) ClearDateObserved() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_DateObserved = false
}

func (x *ReferrersSnapshotSelect) ClearDateUpdated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DateUpdated = false
}

func (x *ReferrersSnapshotSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_DateCreated = false
}

type ReferrersSnapshotSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All          *bool
	Repo         *bool
	Subject      *bool
	Supported    *bool
	Descriptors  *bool
	DateObserved *bool
	DateUpdated  *bool
	DateCreated  *bool
}

func (b0 ReferrersSnapshotSelect_builder) Build() *ReferrersSnapshotSelect {
	m0 := &ReferrersSnapshotSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_All = *b.All
	}
	if b.Repo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Repo = *b.Repo
	}
	if b.Subject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Subject = *b.Subject
	}
	if b.Supported != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Supported = *b.Supported
	}
	if b.Descriptors != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Descriptors = *b.Descriptors
	}
	if b.DateObserved != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_DateObserved = *b.DateObserved
	}
	if b.DateUpdated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_DateUpdated = *b.DateUpdated
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	return m0
}

type ReferrersSnapshotListRequest struct {
	state              protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Filters *[]*ReferrersSnapshotFilter `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_Size    int32                       `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_After   string                      `protobuf:"bytes,3,opt,name=after"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReferrersSnapshotListRequest) Reset() {
	*x = ReferrersSnapshotListRequest{}
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferrersSnapshotListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferrersSnapshotListRequest) ProtoMessage() {}

func (x *ReferrersSnapshotListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReferrersSnapshotListRequest) GetFilters() []*ReferrersSnapshotFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *ReferrersSnapshotListRequest) GetSize() int32 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *ReferrersSnapshotListRequest) GetAfter() string {
	if x != nil {
		return x.xxx_hidden_After
	}
	return ""
}

func (x *ReferrersSnapshotListRequest) SetFilters(v []*ReferrersSnapshotFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *ReferrersSnapshotListRequest) SetSize(v int32) {
	x.xxx_hidden_Size = v
}

func (x *ReferrersSnapshotListRequest) SetAfter(v string) {
	x.xxx_hidden_After = v
}

type ReferrersSnapshotListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Bounded because the work is: each filter is a predicate in the same query,
	// so this is what says how much of the database one request may read.
	Filters []*ReferrersSnapshotFilter
	// How many to answer with. Nothing said is what the schema declared, and more
	// than the cap is the cap -- a caller asking for more than there is meant no
	// harm, so it is not an error and it is not the whole table either.
	Size int32
	// Where to carry on from: the "next" of the answer before. It names the last
	// row of that page rather than counting rows from the start, so a row added
	// ahead of the page does not shift it and a caller reading through never sees
	// one twice or misses one.
	After string
}

func (b0 ReferrersSnapshotListRequest_builder) Build() *ReferrersSnapshotListRequest {
	m0 := &ReferrersSnapshotListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	x.xxx_hidden_Size = b.Size
	x.xxx_hidden_After = b.After
	return m0
}

type ReferrersSnapshotListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*ReferrersSnapshot  `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_Next  string                 `protobuf:"bytes,2,opt,name=next"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReferrersSnapshotListResponse) Reset() {
	*x = ReferrersSnapshotListResponse{}
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferrersSnapshotListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferrersSnapshotListResponse) ProtoMessage() {}

func (x *ReferrersSnapshotListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReferrersSnapshotListResponse) GetItems() []*ReferrersSnapshot {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *ReferrersSnapshotListResponse) GetNext() string {
	if x != nil {
		return x.xxx_hidden_Next
	}
	return ""
}

func (x *ReferrersSnapshotListResponse) SetItems(v []*ReferrersSnapshot) {
	x.xxx_hidden_Items = &v
}

func (x *ReferrersSnapshotListResponse) SetNext(v string) {
	x.xxx_hidden_Next = v
}

type ReferrersSnapshotListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*ReferrersSnapshot
	// What to ask for next, and empty when this was the last of them.
	//
	// Empty means there is no more *for now*: a list is read as it is, and one
	// that has grown since answers a fresh call. It is not empty merely because
	// the page came back short -- a page is short when the last row of it was the
	// last row there was, which is a thing the server can only know by having
	// looked.
	Next string
}

func (b0 ReferrersSnapshotListResponse_builder) Build() *ReferrersSnapshotListResponse {
	m0 := &ReferrersSnapshotListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_Next = b.Next
	return m0
}

type ReferrersSnapshotFilter struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *ReferrersSnapshotRef  `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Repo        *string                `protobuf:"bytes,2,opt,name=repo"`
	xxx_hidden_Subject     *string                `protobuf:"bytes,3,opt,name=subject"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReferrersSnapshotFilter) Reset() {
	*x = ReferrersSnapshotFilter{}
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferrersSnapshotFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferrersSnapshotFilter) ProtoMessage() {}

func (x *ReferrersSnapshotFilter) ProtoReflect() protoreflect.Message {
	mi := &file_app_referrers_snapshot_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReferrersSnapshotFilter) GetRef() *ReferrersSnapshotRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *ReferrersSnapshotFilter) GetRepo() string {
	if x != nil {
		if x.xxx_hidden_Repo != nil {
			return *x.xxx_hidden_Repo
		}
		return ""
	}
	return ""
}

func (x *ReferrersSnapshotFilter) GetSubject() string {
	if x != nil {
		if x.xxx_hidden_Subject != nil {
			return *x.xxx_hidden_Subject
		}
		return ""
	}
	return ""
}

func (x *ReferrersSnapshotFilter) SetRef(v *ReferrersSnapshotRef) {
	x.xxx_hidden_Ref = v
}

func (x *ReferrersSnapshotFilter) SetRepo(v string) {
	x.xxx_hidden_Repo = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ReferrersSnapshotFilter) SetSubject(v string) {
	x.xxx_hidden_Subject = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ReferrersSnapshotFilter) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *ReferrersSnapshotFilter) HasRepo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReferrersSnapshotFilter) HasSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ReferrersSnapshotFilter) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *ReferrersSnapshotFilter) ClearRepo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Repo = nil
}

func (x *ReferrersSnapshotFilter) ClearSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Subject = nil
}

type ReferrersSnapshotFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref     *ReferrersSnapshotRef
	Repo    *string
	Subject *string
}

func (b0 ReferrersSnapshotFilter_builder) Build() *ReferrersSnapshotFilter {
	m0 := &ReferrersSnapshotFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Repo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Repo = b.Repo
	}
	if b.Subject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Subject = b.Subject
	}
	return m0
}

var File_app_referrers_snapshot_svc_g_proto protoreflect.FileDescriptor

const file_app_referrers_snapshot_svc_g_proto_rawDesc = "" +
	"\n" +
	"\"app/referrers_snapshot_svc.g.proto\x12\x03app\x1a\x1capp/referrers_snapshot.proto\"\x80\x01\n" +
	"\x1bReferrersSnapshotGetRequest\x12+\n" +
	"\x03ref\x18\x01 \x01(\v2\x19.app.ReferrersSnapshotRefR\x03ref\x124\n" +
	"\x06select\x18\x02 \x01(\v2\x1c.app.ReferrersSnapshotSelectR\x06select\"v\n" +
	"\x14ReferrersSnapshotRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x12E\n" +
	"\n" +
	"by_subject\x18\b \x01(\v2$.app.ReferrersSnapshotRefByBySubjectH\x00R\tbySubjectB\x05\n" +
	"\x03key\"O\n" +
	"\x1fReferrersSnapshotRefByBySubject\x12\x12\n" +
	"\x04repo\x18\b \x01(\tR\x04repo\x12\x18\n" +
	"\asubject\x18\t \x01(\tR\asubject\"\x84\x02\n" +
	"\x17ReferrersSnapshotSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x12\n" +
	"\x04repo\x18\b \x01(\bR\x04repo\x12\x18\n" +
	"\asubject\x18\t \x01(\bR\asubject\x12\x1c\n" +
	"\tsupported\x18\n" +
	" \x01(\bR\tsupported\x12 \n" +
	"\vdescriptors\x18\v \x01(\bR\vdescriptors\x12#\n" +
	"\rdate_observed\x18\f \x01(\bR\fdateObserved\x12!\n" +
	"\fdate_updated\x18\r \x01(\bR\vdateUpdated\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\"\x8e\x01\n" +
	"\x1cReferrersSnapshotListRequest\x126\n" +
	"\afilters\x18\x01 \x03(\v2\x1c.app.ReferrersSnapshotFilterR\afilters\x12\x19\n" +
	"\x04size\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x02R\x04size\x12\x1b\n" +
	"\x05after\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05after\"h\n" +
	"\x1dReferrersSnapshotListResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.app.ReferrersSnapshotR\x05items\x12\x19\n" +
	"\x04next\x18\x02 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04next\"t\n" +
	"\x17ReferrersSnapshotFilter\x12+\n" +
	"\x03ref\x18\x01 \x01(\v2\x19.app.ReferrersSnapshotRefR\x03ref\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject2\xaa\x01\n" +
	"\x18ReferrersSnapshotService\x12?\n" +
	"\x03Get\x12 .app.ReferrersSnapshotGetRequest\x1a\x16.app.ReferrersSnapshot\x12M\n" +
	"\x04List\x12!.app.ReferrersSnapshotListRequest\x1a\".app.ReferrersSnapshotListResponseB\x1cZ\x1agithub.com/lesomnus/cr/apib\beditionsp\xe8\a"

var file_app_referrers_snapshot_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_referrers_snapshot_svc_g_proto_goTypes = []any{
	(*ReferrersSnapshotGetRequest)(nil),     // 0: app.ReferrersSnapshotGetRequest
	(*ReferrersSnapshotRef)(nil),            // 1: app.ReferrersSnapshotRef
	(*ReferrersSnapshotRefByBySubject)(nil), // 2: app.ReferrersSnapshotRefByBySubject
	(*ReferrersSnapshotSelect)(nil),         // 3: app.ReferrersSnapshotSelect
	(*ReferrersSnapshotListRequest)(nil),    // 4: app.ReferrersSnapshotListRequest
	(*ReferrersSnapshotListResponse)(nil),   // 5: app.ReferrersSnapshotListResponse
	(*ReferrersSnapshotFilter)(nil),         // 6: app.ReferrersSnapshotFilter
	(*ReferrersSnapshot)(nil),               // 7: app.ReferrersSnapshot
}
var file_app_referrers_snapshot_svc_g_proto_depIdxs = []int32{
	1, // 0: app.ReferrersSnapshotGetRequest.ref:type_name -> app.ReferrersSnapshotRef
	3, // 1: app.ReferrersSnapshotGetRequest.select:type_name -> app.ReferrersSnapshotSelect
	2, // 2: app.ReferrersSnapshotRef.by_subject:type_name -> app.ReferrersSnapshotRefByBySubject
	6, // 3: app.ReferrersSnapshotListRequest.filters:type_name -> app.ReferrersSnapshotFilter
	7, // 4: app.ReferrersSnapshotListResponse.items:type_name -> app.ReferrersSnapshot
	1, // 5: app.ReferrersSnapshotFilter.ref:type_name -> app.ReferrersSnapshotRef
	0, // 6: app.ReferrersSnapshotService.Get:input_type -> app.ReferrersSnapshotGetRequest
	4, // 7: app.ReferrersSnapshotService.List:input_type -> app.ReferrersSnapshotListRequest
	7, // 8: app.ReferrersSnapshotService.Get:output_type -> app.ReferrersSnapshot
	5, // 9: app.ReferrersSnapshotService.List:output_type -> app.ReferrersSnapshotListResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_app_referrers_snapshot_svc_g_proto_init() }
func file_app_referrers_snapshot_svc_g_proto_init() {
	if File_app_referrers_snapshot_svc_g_proto != nil {
		return
	}
	file_app_referrers_snapshot_proto_init()
	file_app_referrers_snapshot_svc_g_proto_msgTypes[1].OneofWrappers = []any{
		(*referrersSnapshotRef_Id)(nil),
		(*referrersSnapshotRef_BySubject)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_referrers_snapshot_svc_g_proto_rawDesc), len(file_app_referrers_snapshot_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_referrers_snapshot_svc_g_proto_goTypes,
		DependencyIndexes: file_app_referrers_snapshot_svc_g_proto_depIdxs,
		MessageInfos:      file_app_referrers_snapshot_svc_g_proto_msgTypes,
	}.Build()
	File_app_referrers_snapshot_svc_g_proto = out.File
	file_app_referrers_snapshot_svc_g_proto_goTypes = nil
	file_app_referrers_snapshot_svc_g_proto_depIdxs = nil
}
