// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package api

import (
	bytes "bytes"
)

func (x *TagRef) Pick() *TagGetRequest {
	return TagGetRequest_builder{Ref: x}.Build()
}

func (x *Tag) Ref() *TagRef {
	if v := x.GetId(); len(v) > 0 {
		return TagById(v)
	}
	{
		v1 := x.GetRepo()
		v2 := x.GetName()
		if len(v1) > 0 && len(v2) > 0 {
			return TagByByName(v1, v2)
		}
	}

	return nil
}

func (x *Tag) Pick() *TagGetRequest {
	return x.Ref().Pick()
}

func (x *TagRef) Picks(v *Tag) bool {
	switch x.WhichKey() {
	case TagRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case TagRef_ByName_case:
		x := x.GetByName()
		return (x.GetRepo() == v.GetRepo()) &&
			(x.GetName() == v.GetName())
	default:
		return false
	}
}

func (x *TagGetRequest) WithSelect(f func(s *TagSelect)) *TagGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&TagSelect{})
	}
	f(x.GetSelect())
	return x
}

func TagById(v []byte) *TagRef {
	x := &TagRef{}
	x.SetId(v)
	return x
}

func TagGetById(v []byte) *TagGetRequest {
	return TagGetRequest_builder{Ref: TagById(v)}.Build()
}

func TagByByName(repo string, name string) *TagRef {
	x := &TagRefByByName{}
	x.SetRepo(repo)
	x.SetName(name)
	return TagRef_builder{ByName: x}.Build()
}

func TagGetByByName(repo string, name string) *TagGetRequest {
	return TagGetRequest_builder{Ref: TagByByName(repo, name)}.Build()
}
